# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
version: 2

project_name: apisix

builds:
  - id: apisix
    main: .
    binary: apisix
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    flags: [ -trimpath ]
    ldflags:
      - -s -w -X github.com/wklken/apisix-go/pkg/version.Version={{ .Version }} -X github.com/wklken/apisix-go/pkg/version.Commit={{ .Commit }} -X github.com/wklken/apisix-go/pkg/version.BuildTime={{ .Date }} -X 'github.com/wklken/apisix-go/pkg/version.GoVersion={{ .Env.GOVERSION }}'

archives:
  - formats:
      - tar.gz
    files:
      - conf/config-default.yaml

checksum:
  name_template: checksums.txt
