// Code generated by go run ./cmd/capability-gen -write; DO NOT EDIT.

package plugin

// Imports are rendered from manifest Factory facts.
import (
	acl "github.com/wklken/apisix-go/pkg/plugin/acl"
	ai "github.com/wklken/apisix-go/pkg/plugin/ai"
	ai_aliyun_content_moderation "github.com/wklken/apisix-go/pkg/plugin/ai_aliyun_content_moderation"
	ai_aws_content_moderation "github.com/wklken/apisix-go/pkg/plugin/ai_aws_content_moderation"
	ai_prompt_decorator "github.com/wklken/apisix-go/pkg/plugin/ai_prompt_decorator"
	ai_prompt_guard "github.com/wklken/apisix-go/pkg/plugin/ai_prompt_guard"
	ai_prompt_template "github.com/wklken/apisix-go/pkg/plugin/ai_prompt_template"
	ai_proxy "github.com/wklken/apisix-go/pkg/plugin/ai_proxy"
	ai_proxy_multi "github.com/wklken/apisix-go/pkg/plugin/ai_proxy_multi"
	ai_rag "github.com/wklken/apisix-go/pkg/plugin/ai_rag"
	ai_rate_limiting "github.com/wklken/apisix-go/pkg/plugin/ai_rate_limiting"
	ai_request_rewrite "github.com/wklken/apisix-go/pkg/plugin/ai_request_rewrite"
	api_breaker "github.com/wklken/apisix-go/pkg/plugin/api_breaker"
	attach_consumer_label "github.com/wklken/apisix-go/pkg/plugin/attach_consumer_label"
	authz_casbin "github.com/wklken/apisix-go/pkg/plugin/authz_casbin"
	authz_casdoor "github.com/wklken/apisix-go/pkg/plugin/authz_casdoor"
	authz_keycloak "github.com/wklken/apisix-go/pkg/plugin/authz_keycloak"
	aws_lambda "github.com/wklken/apisix-go/pkg/plugin/aws_lambda"
	azure_functions "github.com/wklken/apisix-go/pkg/plugin/azure_functions"
	basic_auth "github.com/wklken/apisix-go/pkg/plugin/basic_auth"
	batch_requests "github.com/wklken/apisix-go/pkg/plugin/batch_requests"
	body_transformer "github.com/wklken/apisix-go/pkg/plugin/body_transformer"
	brotli "github.com/wklken/apisix-go/pkg/plugin/brotli"
	cas_auth "github.com/wklken/apisix-go/pkg/plugin/cas_auth"
	chaitin_waf "github.com/wklken/apisix-go/pkg/plugin/chaitin_waf"
	clickhouse_logger "github.com/wklken/apisix-go/pkg/plugin/clickhouse_logger"
	client_control "github.com/wklken/apisix-go/pkg/plugin/client_control"
	consumer_restriction "github.com/wklken/apisix-go/pkg/plugin/consumer_restriction"
	cors "github.com/wklken/apisix-go/pkg/plugin/cors"
	csrf "github.com/wklken/apisix-go/pkg/plugin/csrf"
	data_mask "github.com/wklken/apisix-go/pkg/plugin/data_mask"
	datadog "github.com/wklken/apisix-go/pkg/plugin/datadog"
	degraphql "github.com/wklken/apisix-go/pkg/plugin/degraphql"
	dingtalk_auth "github.com/wklken/apisix-go/pkg/plugin/dingtalk_auth"
	dubbo_proxy "github.com/wklken/apisix-go/pkg/plugin/dubbo_proxy"
	echo "github.com/wklken/apisix-go/pkg/plugin/echo"
	elasticsearch_logger "github.com/wklken/apisix-go/pkg/plugin/elasticsearch_logger"
	error_log_logger "github.com/wklken/apisix-go/pkg/plugin/error_log_logger"
	error_page "github.com/wklken/apisix-go/pkg/plugin/error_page"
	example_plugin "github.com/wklken/apisix-go/pkg/plugin/example_plugin"
	exit_transformer "github.com/wklken/apisix-go/pkg/plugin/exit_transformer"
	fault_injection "github.com/wklken/apisix-go/pkg/plugin/fault_injection"
	feishu_auth "github.com/wklken/apisix-go/pkg/plugin/feishu_auth"
	file_logger "github.com/wklken/apisix-go/pkg/plugin/file_logger"
	forward_auth "github.com/wklken/apisix-go/pkg/plugin/forward_auth"
	gm "github.com/wklken/apisix-go/pkg/plugin/gm"
	google_cloud_logging "github.com/wklken/apisix-go/pkg/plugin/google_cloud_logging"
	graphql_limit_count "github.com/wklken/apisix-go/pkg/plugin/graphql_limit_count"
	graphql_proxy_cache "github.com/wklken/apisix-go/pkg/plugin/graphql_proxy_cache"
	grpc_transcode "github.com/wklken/apisix-go/pkg/plugin/grpc_transcode"
	grpc_web "github.com/wklken/apisix-go/pkg/plugin/grpc_web"
	gzip "github.com/wklken/apisix-go/pkg/plugin/gzip"
	hmac_auth "github.com/wklken/apisix-go/pkg/plugin/hmac_auth"
	http_dubbo "github.com/wklken/apisix-go/pkg/plugin/http_dubbo"
	http_logger "github.com/wklken/apisix-go/pkg/plugin/http_logger"
	ip_restriction "github.com/wklken/apisix-go/pkg/plugin/ip_restriction"
	jwe_decrypt "github.com/wklken/apisix-go/pkg/plugin/jwe_decrypt"
	jwt_auth "github.com/wklken/apisix-go/pkg/plugin/jwt_auth"
	kafka_logger "github.com/wklken/apisix-go/pkg/plugin/kafka_logger"
	kafka_proxy "github.com/wklken/apisix-go/pkg/plugin/kafka_proxy"
	key_auth "github.com/wklken/apisix-go/pkg/plugin/key_auth"
	lago "github.com/wklken/apisix-go/pkg/plugin/lago"
	ldap_auth "github.com/wklken/apisix-go/pkg/plugin/ldap_auth"
	limit_conn "github.com/wklken/apisix-go/pkg/plugin/limit_conn"
	limit_count "github.com/wklken/apisix-go/pkg/plugin/limit_count"
	limit_req "github.com/wklken/apisix-go/pkg/plugin/limit_req"
	log_rotate "github.com/wklken/apisix-go/pkg/plugin/log_rotate"
	loggly "github.com/wklken/apisix-go/pkg/plugin/loggly"
	loki_logger "github.com/wklken/apisix-go/pkg/plugin/loki_logger"
	mcp_bridge "github.com/wklken/apisix-go/pkg/plugin/mcp_bridge"
	mocking "github.com/wklken/apisix-go/pkg/plugin/mocking"
	mqtt_proxy "github.com/wklken/apisix-go/pkg/plugin/mqtt_proxy"
	multi_auth "github.com/wklken/apisix-go/pkg/plugin/multi_auth"
	node_status "github.com/wklken/apisix-go/pkg/plugin/node_status"
	oas_validator "github.com/wklken/apisix-go/pkg/plugin/oas_validator"
	opa "github.com/wklken/apisix-go/pkg/plugin/opa"
	openfunction "github.com/wklken/apisix-go/pkg/plugin/openfunction"
	openid_connect "github.com/wklken/apisix-go/pkg/plugin/openid_connect"
	openwhisk "github.com/wklken/apisix-go/pkg/plugin/openwhisk"
	otel "github.com/wklken/apisix-go/pkg/plugin/otel"
	prometheus "github.com/wklken/apisix-go/pkg/plugin/prometheus"
	proxy_buffering "github.com/wklken/apisix-go/pkg/plugin/proxy_buffering"
	proxy_cache "github.com/wklken/apisix-go/pkg/plugin/proxy_cache"
	proxy_control "github.com/wklken/apisix-go/pkg/plugin/proxy_control"
	proxy_mirror "github.com/wklken/apisix-go/pkg/plugin/proxy_mirror"
	proxy_rewrite "github.com/wklken/apisix-go/pkg/plugin/proxy_rewrite"
	public_api "github.com/wklken/apisix-go/pkg/plugin/public_api"
	real_ip "github.com/wklken/apisix-go/pkg/plugin/real_ip"
	redirect "github.com/wklken/apisix-go/pkg/plugin/redirect"
	referer_restriction "github.com/wklken/apisix-go/pkg/plugin/referer_restriction"
	request_context "github.com/wklken/apisix-go/pkg/plugin/request_context"
	request_id "github.com/wklken/apisix-go/pkg/plugin/request_id"
	request_validation "github.com/wklken/apisix-go/pkg/plugin/request_validation"
	response_rewrite "github.com/wklken/apisix-go/pkg/plugin/response_rewrite"
	rocketmq_logger "github.com/wklken/apisix-go/pkg/plugin/rocketmq_logger"
	saml_auth "github.com/wklken/apisix-go/pkg/plugin/saml_auth"
	server_info "github.com/wklken/apisix-go/pkg/plugin/server_info"
	serverless "github.com/wklken/apisix-go/pkg/plugin/serverless"
	skywalking "github.com/wklken/apisix-go/pkg/plugin/skywalking"
	skywalking_logger "github.com/wklken/apisix-go/pkg/plugin/skywalking_logger"
	sls_logger "github.com/wklken/apisix-go/pkg/plugin/sls_logger"
	splunk_hec_logging "github.com/wklken/apisix-go/pkg/plugin/splunk_hec_logging"
	syslog "github.com/wklken/apisix-go/pkg/plugin/syslog"
	tcp_logger "github.com/wklken/apisix-go/pkg/plugin/tcp_logger"
	tencent_cloud_cls "github.com/wklken/apisix-go/pkg/plugin/tencent_cloud_cls"
	traffic_label "github.com/wklken/apisix-go/pkg/plugin/traffic_label"
	traffic_split "github.com/wklken/apisix-go/pkg/plugin/traffic_split"
	ua_restriction "github.com/wklken/apisix-go/pkg/plugin/ua_restriction"
	udp_logger "github.com/wklken/apisix-go/pkg/plugin/udp_logger"
	uri_blocker "github.com/wklken/apisix-go/pkg/plugin/uri_blocker"
	wolf_rbac "github.com/wklken/apisix-go/pkg/plugin/wolf_rbac"
	workflow "github.com/wklken/apisix-go/pkg/plugin/workflow"
	zipkin "github.com/wklken/apisix-go/pkg/plugin/zipkin"
)

var pluginRegistry = map[string]func() Plugin{
	"acl":                          func() Plugin { return &acl.Plugin{} },
	"ai":                           func() Plugin { return &ai.Plugin{} },
	"ai-aliyun-content-moderation": func() Plugin { return &ai_aliyun_content_moderation.Plugin{} },
	"ai-aws-content-moderation":    func() Plugin { return &ai_aws_content_moderation.Plugin{} },
	"ai-prompt-decorator":          func() Plugin { return &ai_prompt_decorator.Plugin{} },
	"ai-prompt-guard":              func() Plugin { return &ai_prompt_guard.Plugin{} },
	"ai-prompt-template":           func() Plugin { return &ai_prompt_template.Plugin{} },
	"ai-proxy":                     func() Plugin { return &ai_proxy.Plugin{} },
	"ai-proxy-multi":               func() Plugin { return &ai_proxy_multi.Plugin{} },
	"ai-rag":                       func() Plugin { return &ai_rag.Plugin{} },
	"ai-rate-limiting":             func() Plugin { return &ai_rate_limiting.Plugin{} },
	"ai-request-rewrite":           func() Plugin { return &ai_request_rewrite.Plugin{} },
	"api-breaker":                  func() Plugin { return &api_breaker.Plugin{} },
	"attach-consumer-label":        func() Plugin { return &attach_consumer_label.Plugin{} },
	"authz-casbin":                 func() Plugin { return &authz_casbin.Plugin{} },
	"authz-casdoor":                func() Plugin { return &authz_casdoor.Plugin{} },
	"authz-keycloak":               func() Plugin { return &authz_keycloak.Plugin{} },
	"aws-lambda":                   func() Plugin { return &aws_lambda.Plugin{} },
	"azure-functions":              func() Plugin { return &azure_functions.Plugin{} },
	"basic-auth":                   func() Plugin { return &basic_auth.Plugin{} },
	"batch-requests":               func() Plugin { return &batch_requests.Plugin{} },
	"body-transformer":             func() Plugin { return &body_transformer.Plugin{} },
	"brotli":                       func() Plugin { return &brotli.Plugin{} },
	"cas-auth":                     func() Plugin { return &cas_auth.Plugin{} },
	"chaitin-waf":                  func() Plugin { return &chaitin_waf.Plugin{} },
	"clickhouse-logger":            func() Plugin { return &clickhouse_logger.Plugin{} },
	"client-control":               func() Plugin { return &client_control.Plugin{} },
	"consumer-restriction":         func() Plugin { return &consumer_restriction.Plugin{} },
	"cors":                         func() Plugin { return &cors.Plugin{} },
	"csrf":                         func() Plugin { return &csrf.Plugin{} },
	"data-mask":                    func() Plugin { return &data_mask.Plugin{} },
	"datadog":                      func() Plugin { return &datadog.Plugin{} },
	"degraphql":                    func() Plugin { return &degraphql.Plugin{} },
	"dingtalk-auth":                func() Plugin { return &dingtalk_auth.Plugin{} },
	"dubbo-proxy":                  func() Plugin { return &dubbo_proxy.Plugin{} },
	"echo":                         func() Plugin { return &echo.Plugin{} },
	"elasticsearch-logger":         func() Plugin { return &elasticsearch_logger.Plugin{} },
	"error-log-logger":             func() Plugin { return &error_log_logger.Plugin{} },
	"error-page":                   func() Plugin { return &error_page.Plugin{} },
	"example-plugin":               func() Plugin { return &example_plugin.Plugin{} },
	"exit-transformer":             func() Plugin { return &exit_transformer.Plugin{} },
	"fault-injection":              func() Plugin { return &fault_injection.Plugin{} },
	"feishu-auth":                  func() Plugin { return &feishu_auth.Plugin{} },
	"file-logger":                  func() Plugin { return &file_logger.Plugin{} },
	"forward-auth":                 func() Plugin { return &forward_auth.Plugin{} },
	"gm":                           func() Plugin { return &gm.Plugin{} },
	"google-cloud-logging":         func() Plugin { return &google_cloud_logging.Plugin{} },
	"graphql-limit-count":          func() Plugin { return &graphql_limit_count.Plugin{} },
	"graphql-proxy-cache":          func() Plugin { return &graphql_proxy_cache.Plugin{} },
	"grpc-transcode":               func() Plugin { return &grpc_transcode.Plugin{} },
	"grpc-web":                     func() Plugin { return &grpc_web.Plugin{} },
	"gzip":                         func() Plugin { return &gzip.Plugin{} },
	"hmac-auth":                    func() Plugin { return &hmac_auth.Plugin{} },
	"http-dubbo":                   func() Plugin { return &http_dubbo.Plugin{} },
	"http-logger":                  func() Plugin { return &http_logger.Plugin{} },
	"ip-restriction":               func() Plugin { return &ip_restriction.Plugin{} },
	"jwe-decrypt":                  func() Plugin { return &jwe_decrypt.Plugin{} },
	"jwt-auth":                     func() Plugin { return &jwt_auth.Plugin{} },
	"kafka-logger":                 func() Plugin { return &kafka_logger.Plugin{} },
	"kafka-proxy":                  func() Plugin { return &kafka_proxy.Plugin{} },
	"key-auth":                     func() Plugin { return &key_auth.Plugin{} },
	"lago":                         func() Plugin { return &lago.Plugin{} },
	"ldap-auth":                    func() Plugin { return &ldap_auth.Plugin{} },
	"limit-conn":                   func() Plugin { return &limit_conn.Plugin{} },
	"limit-count":                  func() Plugin { return &limit_count.Plugin{} },
	"limit-req":                    func() Plugin { return &limit_req.Plugin{} },
	"log-rotate":                   func() Plugin { return &log_rotate.Plugin{} },
	"loggly":                       func() Plugin { return &loggly.Plugin{} },
	"loki-logger":                  func() Plugin { return &loki_logger.Plugin{} },
	"mcp-bridge":                   func() Plugin { return &mcp_bridge.Plugin{} },
	"mocking":                      func() Plugin { return &mocking.Plugin{} },
	"mqtt-proxy":                   func() Plugin { return &mqtt_proxy.Plugin{} },
	"multi-auth":                   func() Plugin { return &multi_auth.Plugin{} },
	"node-status":                  func() Plugin { return &node_status.Plugin{} },
	"oas-validator":                func() Plugin { return &oas_validator.Plugin{} },
	"opa":                          func() Plugin { return &opa.Plugin{} },
	"openfunction":                 func() Plugin { return &openfunction.Plugin{} },
	"openid-connect":               func() Plugin { return &openid_connect.Plugin{} },
	"opentelemetry":                func() Plugin { return &otel.Plugin{} },
	"openwhisk":                    func() Plugin { return &openwhisk.Plugin{} },
	"otel":                         func() Plugin { return &otel.Plugin{} },
	"prometheus":                   func() Plugin { return &prometheus.Plugin{} },
	"proxy-buffering":              func() Plugin { return &proxy_buffering.Plugin{} },
	"proxy-cache":                  func() Plugin { return &proxy_cache.Plugin{} },
	"proxy-control":                func() Plugin { return &proxy_control.Plugin{} },
	"proxy-mirror":                 func() Plugin { return &proxy_mirror.Plugin{} },
	"proxy-rewrite":                func() Plugin { return &proxy_rewrite.Plugin{} },
	"public-api":                   func() Plugin { return &public_api.Plugin{} },
	"real-ip":                      func() Plugin { return &real_ip.Plugin{} },
	"redirect":                     func() Plugin { return &redirect.Plugin{} },
	"referer-restriction":          func() Plugin { return &referer_restriction.Plugin{} },
	"request-context":              func() Plugin { return &request_context.Plugin{} },
	"request-id":                   func() Plugin { return &request_id.Plugin{} },
	"request-validation":           func() Plugin { return &request_validation.Plugin{} },
	"response-rewrite":             func() Plugin { return &response_rewrite.Plugin{} },
	"rocketmq-logger":              func() Plugin { return &rocketmq_logger.Plugin{} },
	"saml-auth":                    func() Plugin { return &saml_auth.Plugin{} },
	"server-info":                  func() Plugin { return &server_info.Plugin{} },
	"serverless-post-function":     func() Plugin { return serverless.NewPostFunction() },
	"serverless-pre-function":      func() Plugin { return serverless.NewPreFunction() },
	"skywalking":                   func() Plugin { return &skywalking.Plugin{} },
	"skywalking-logger":            func() Plugin { return &skywalking_logger.Plugin{} },
	"sls-logger":                   func() Plugin { return &sls_logger.Plugin{} },
	"splunk-hec-logging":           func() Plugin { return &splunk_hec_logging.Plugin{} },
	"syslog":                       func() Plugin { return &syslog.Plugin{} },
	"tcp-logger":                   func() Plugin { return &tcp_logger.Plugin{} },
	"tencent-cloud-cls":            func() Plugin { return &tencent_cloud_cls.Plugin{} },
	"traffic-label":                func() Plugin { return &traffic_label.Plugin{} },
	"traffic-split":                func() Plugin { return &traffic_split.Plugin{} },
	"ua-restriction":               func() Plugin { return &ua_restriction.Plugin{} },
	"udp-logger":                   func() Plugin { return &udp_logger.Plugin{} },
	"uri-blocker":                  func() Plugin { return &uri_blocker.Plugin{} },
	"wolf-rbac":                    func() Plugin { return &wolf_rbac.Plugin{} },
	"workflow":                     func() Plugin { return &workflow.Plugin{} },
	"zipkin":                       func() Plugin { return &zipkin.Plugin{} },
}

func generatedCapabilityManifestEntries() map[string]capabilityManifestEntry {
	return map[string]capabilityManifestEntry{
		"acl": {
			phases: []string{"access"},
			scopes: []string{"global_rule", "route", "service"},
		},
		"ai": {
			phases: []string{},
			scopes: []string{"system"},
		},
		"ai-aliyun-content-moderation": {
			phases: []string{"access", "body_filter"},
			scopes: []string{"global_rule", "route", "service"},
		},
		"ai-aws-content-moderation": {
			phases: []string{"access"},
			scopes: []string{"global_rule", "route", "service"},
		},
		"ai-prompt-decorator": {
			phases: []string{"rewrite"},
			scopes: []string{"global_rule", "route", "service"},
		},
		"ai-prompt-guard": {
			phases: []string{"access"},
			scopes: []string{"global_rule", "route", "service"},
		},
		"ai-prompt-template": {
			phases: []string{"rewrite"},
			scopes: []string{"global_rule", "route", "service"},
		},
		"ai-proxy": {
			phases: []string{"access", "before_proxy", "protocol"},
			scopes: []string{"global_rule", "route", "service"},
		},
		"ai-proxy-multi": {
			phases: []string{"access", "before_proxy", "protocol"},
			scopes: []string{"global_rule", "route", "service"},
		},
		"ai-rag": {
			phases: []string{"rewrite"},
			scopes: []string{"global_rule", "route", "service"},
		},
		"ai-rate-limiting": {
			phases: []string{"access", "body_filter", "finalizer"},
			scopes: []string{"global_rule", "route", "service"},
		},
		"ai-request-rewrite": {
			phases: []string{"rewrite"},
			scopes: []string{"global_rule", "route", "service"},
		},
		"api-breaker": {
			phases: []string{"access", "finalizer"},
			scopes: []string{"global_rule", "route", "service"},
		},
		"attach-consumer-label": {
			phases: []string{"consumer_rewrite"},
			scopes: []string{"global_rule", "route", "service"},
		},
		"authz-casbin": {
			phases: []string{"access"},
			scopes: []string{"global_rule", "route", "service"},
		},
		"authz-casdoor": {
			phases: []string{"access"},
			scopes: []string{"global_rule", "route", "service"},
		},
		"authz-keycloak": {
			phases: []string{"access"},
			scopes: []string{"global_rule", "route", "service"},
		},
		"aws-lambda": {
			phases: []string{"access"},
			scopes: []string{"global_rule", "route", "service"},
		},
		"azure-functions": {
			phases: []string{"access"},
			scopes: []string{"global_rule", "route", "service"},
		},
		"basic-auth": {
			phases: []string{"access"},
			scopes: []string{"global_rule", "route", "service"},
		},
		"batch-requests": {
			phases: []string{},
			scopes: []string{"system"},
		},
		"body-transformer": {
			phases: []string{"rewrite", "body_filter"},
			scopes: []string{"global_rule", "route", "service"},
		},
		"brotli": {
			phases: []string{"header_filter", "body_filter"},
			scopes: []string{"global_rule", "route", "service"},
		},
		"cas-auth": {
			phases: []string{"access"},
			scopes: []string{"global_rule", "route", "service"},
		},
		"chaitin-waf": {
			phases: []string{"access"},
			scopes: []string{"global_rule", "route", "service"},
		},
		"clickhouse-logger": {
			phases: []string{"log"},
			scopes: []string{"global_rule", "route", "service"},
		},
		"client-control": {
			phases: []string{"access"},
			scopes: []string{"global_rule", "route", "service"},
		},
		"consumer-restriction": {
			phases: []string{"access"},
			scopes: []string{"global_rule", "route", "service"},
		},
		"cors": {
			phases: []string{"rewrite", "header_filter"},
			scopes: []string{"global_rule", "route", "service"},
		},
		"csrf": {
			phases: []string{"access"},
			scopes: []string{"global_rule", "route", "service"},
		},
		"data-mask": {
			phases: []string{"log"},
			scopes: []string{"global_rule", "route", "service"},
		},
		"datadog": {
			phases: []string{"log"},
			scopes: []string{"global_rule", "route", "service"},
		},
		"degraphql": {
			phases: []string{"rewrite"},
			scopes: []string{"global_rule", "route", "service"},
		},
		"dingtalk-auth": {
			phases: []string{"access"},
			scopes: []string{"global_rule", "route", "service"},
		},
		"dubbo-proxy": {
			phases: []string{"access", "before_proxy", "protocol"},
			scopes: []string{"global_rule", "route", "service"},
		},
		"echo": {
			phases: []string{"header_filter", "body_filter"},
			scopes: []string{"global_rule", "route", "service"},
		},
		"elasticsearch-logger": {
			phases: []string{"log"},
			scopes: []string{"global_rule", "route", "service"},
		},
		"error-log-logger": {
			phases: []string{},
			scopes: []string{"system"},
		},
		"error-page": {
			phases: []string{"body_filter"},
			scopes: []string{"global_rule", "route", "service"},
		},
		"example-plugin": {
			phases: []string{"rewrite"},
			scopes: []string{"system", "global_rule", "route", "service"},
		},
		"exit-transformer": {
			phases: []string{"body_filter"},
			scopes: []string{"global_rule", "route", "service"},
		},
		"fault-injection": {
			phases: []string{"rewrite"},
			scopes: []string{"global_rule", "route", "service"},
		},
		"feishu-auth": {
			phases: []string{"access"},
			scopes: []string{"global_rule", "route", "service"},
		},
		"file-logger": {
			phases: []string{"log"},
			scopes: []string{"global_rule", "route", "service"},
		},
		"forward-auth": {
			phases: []string{"access"},
			scopes: []string{"global_rule", "route", "service"},
		},
		"gm": {
			phases: []string{},
			scopes: []string{"system"},
		},
		"google-cloud-logging": {
			phases: []string{"log"},
			scopes: []string{"global_rule", "route", "service"},
		},
		"graphql-limit-count": {
			phases: []string{"access"},
			scopes: []string{"global_rule", "route", "service"},
		},
		"graphql-proxy-cache": {
			phases: []string{"access", "body_filter"},
			scopes: []string{"global_rule", "route", "service"},
		},
		"grpc-transcode": {
			phases: []string{"access", "body_filter"},
			scopes: []string{"global_rule", "route", "service"},
		},
		"grpc-web": {
			phases: []string{"access", "header_filter", "body_filter", "protocol"},
			scopes: []string{"global_rule", "route", "service"},
		},
		"gzip": {
			phases: []string{"header_filter", "body_filter"},
			scopes: []string{"global_rule", "route", "service"},
		},
		"hmac-auth": {
			phases: []string{"access"},
			scopes: []string{"global_rule", "route", "service"},
		},
		"http-dubbo": {
			phases: []string{"before_proxy", "protocol"},
			scopes: []string{"global_rule", "route", "service"},
		},
		"http-logger": {
			phases: []string{"log"},
			scopes: []string{"global_rule", "route", "service"},
		},
		"ip-restriction": {
			phases: []string{"access"},
			scopes: []string{"global_rule", "route", "service"},
		},
		"jwe-decrypt": {
			phases: []string{"rewrite"},
			scopes: []string{"global_rule", "route", "service"},
		},
		"jwt-auth": {
			phases: []string{"access"},
			scopes: []string{"global_rule", "route", "service"},
		},
		"kafka-logger": {
			phases: []string{"log"},
			scopes: []string{"global_rule", "route", "service"},
		},
		"kafka-proxy": {
			phases: []string{"access", "before_proxy", "protocol"},
			scopes: []string{"global_rule", "route", "service"},
		},
		"key-auth": {
			phases: []string{"access", "log"},
			scopes: []string{"global_rule", "route", "service"},
		},
		"lago": {
			phases: []string{"log"},
			scopes: []string{"global_rule", "route", "service"},
		},
		"ldap-auth": {
			phases: []string{"access"},
			scopes: []string{"global_rule", "route", "service"},
		},
		"limit-conn": {
			phases: []string{"access", "finalizer"},
			scopes: []string{"global_rule", "route", "service"},
		},
		"limit-count": {
			phases: []string{"access"},
			scopes: []string{"global_rule", "route", "service"},
		},
		"limit-req": {
			phases: []string{"access"},
			scopes: []string{"global_rule", "route", "service"},
		},
		"log-rotate": {
			phases: []string{"access"},
			scopes: []string{"system"},
		},
		"loggly": {
			phases: []string{"log"},
			scopes: []string{"global_rule", "route", "service"},
		},
		"loki-logger": {
			phases: []string{"log"},
			scopes: []string{"global_rule", "route", "service"},
		},
		"mcp-bridge": {
			phases: []string{"access", "protocol"},
			scopes: []string{"global_rule", "route", "service"},
		},
		"mocking": {
			phases: []string{"access"},
			scopes: []string{"global_rule", "route", "service"},
		},
		"mqtt-proxy": {
			phases: []string{"protocol"},
			scopes: []string{"route"},
		},
		"multi-auth": {
			phases: []string{"access"},
			scopes: []string{"global_rule", "route", "service"},
		},
		"node-status": {
			phases: []string{},
			scopes: []string{"system"},
		},
		"oas-validator": {
			phases: []string{"access"},
			scopes: []string{"global_rule", "route", "service"},
		},
		"opa": {
			phases: []string{"access"},
			scopes: []string{"global_rule", "route", "service"},
		},
		"openfunction": {
			phases: []string{"access"},
			scopes: []string{"global_rule", "route", "service"},
		},
		"openid-connect": {
			phases: []string{"access"},
			scopes: []string{"global_rule", "route", "service"},
		},
		"opentelemetry": {
			phases: []string{"rewrite", "finalizer"},
			scopes: []string{"global_rule", "route", "service"},
		},
		"openwhisk": {
			phases: []string{"access"},
			scopes: []string{"global_rule", "route", "service"},
		},
		"prometheus": {
			phases: []string{"log"},
			scopes: []string{"system", "global_rule", "route", "service"},
		},
		"proxy-buffering": {
			phases: []string{"rewrite", "body_filter"},
			scopes: []string{"global_rule", "route", "service"},
		},
		"proxy-cache": {
			phases: []string{"access", "body_filter"},
			scopes: []string{"global_rule", "route", "service"},
		},
		"proxy-control": {
			phases: []string{"rewrite"},
			scopes: []string{"global_rule", "route", "service"},
		},
		"proxy-mirror": {
			phases: []string{"rewrite", "before_proxy"},
			scopes: []string{"global_rule", "route", "service"},
		},
		"proxy-rewrite": {
			phases: []string{"rewrite"},
			scopes: []string{"global_rule", "route", "service"},
		},
		"public-api": {
			phases: []string{"access"},
			scopes: []string{"global_rule", "route", "service"},
		},
		"real-ip": {
			phases: []string{"rewrite"},
			scopes: []string{"global_rule", "route", "service"},
		},
		"redirect": {
			phases: []string{"rewrite"},
			scopes: []string{"global_rule", "route", "service"},
		},
		"referer-restriction": {
			phases: []string{"access"},
			scopes: []string{"global_rule", "route", "service"},
		},
		"request-context": {
			phases: []string{"rewrite"},
			scopes: []string{"system"},
		},
		"request-id": {
			phases: []string{"rewrite"},
			scopes: []string{"global_rule", "route", "service"},
		},
		"request-validation": {
			phases: []string{"access"},
			scopes: []string{"global_rule", "route", "service"},
		},
		"response-rewrite": {
			phases: []string{"header_filter", "body_filter"},
			scopes: []string{"global_rule", "route", "service"},
		},
		"rocketmq-logger": {
			phases: []string{"log"},
			scopes: []string{"global_rule", "route", "service"},
		},
		"saml-auth": {
			phases: []string{"access"},
			scopes: []string{"global_rule", "route", "service"},
		},
		"server-info": {
			phases: []string{},
			scopes: []string{"system"},
		},
		"serverless-post-function": {
			phases: []string{"rewrite", "access", "before_proxy", "header_filter", "body_filter", "log"},
			scopes: []string{"global_rule", "route", "service"},
		},
		"serverless-pre-function": {
			phases: []string{"rewrite", "access", "before_proxy", "header_filter", "body_filter", "log"},
			scopes: []string{"global_rule", "route", "service"},
		},
		"skywalking": {
			phases: []string{"rewrite", "finalizer"},
			scopes: []string{"global_rule", "route", "service"},
		},
		"skywalking-logger": {
			phases: []string{"log"},
			scopes: []string{"global_rule", "route", "service"},
		},
		"sls-logger": {
			phases: []string{"log"},
			scopes: []string{"global_rule", "route", "service"},
		},
		"splunk-hec-logging": {
			phases: []string{"log"},
			scopes: []string{"global_rule", "route", "service"},
		},
		"syslog": {
			phases: []string{"log"},
			scopes: []string{"global_rule", "route", "service"},
		},
		"tcp-logger": {
			phases: []string{"log"},
			scopes: []string{"global_rule", "route", "service"},
		},
		"tencent-cloud-cls": {
			phases: []string{"log"},
			scopes: []string{"global_rule", "route", "service"},
		},
		"traffic-label": {
			phases: []string{"rewrite"},
			scopes: []string{"global_rule", "route", "service"},
		},
		"traffic-split": {
			phases: []string{"rewrite"},
			scopes: []string{"global_rule", "route", "service"},
		},
		"ua-restriction": {
			phases: []string{"access"},
			scopes: []string{"global_rule", "route", "service"},
		},
		"udp-logger": {
			phases: []string{"log"},
			scopes: []string{"global_rule", "route", "service"},
		},
		"uri-blocker": {
			phases: []string{"access"},
			scopes: []string{"global_rule", "route", "service"},
		},
		"wolf-rbac": {
			phases: []string{"access"},
			scopes: []string{"global_rule", "route", "service"},
		},
		"workflow": {
			phases: []string{"access"},
			scopes: []string{"global_rule", "route", "service"},
		},
		"zipkin": {
			phases: []string{"rewrite", "finalizer"},
			scopes: []string{"global_rule", "route", "service"},
		},
	}
}
