package pluginintegration

const (
	differentialAzureFunctionsFixtureInvocationPolicy   = "azure-functions-fixture-invocation"
	differentialCSRFIssuedCookieComparisonPolicy        = "csrf-issued-cookie"
	differentialComparisonNodeStatusJSONCounters        = "node-status-json-counters"
	differentialComparisonPrometheusRouteStatusSeries   = "prometheus-route-status-series"
	differentialDatadogSixDatagramsPolicy               = "datadog-six-ordered-dogstatsd-datagrams"
	differentialDingTalkAuthFixtureOAuthPolicy          = "dingtalk-auth-fixture-oauth"
	differentialDubboProxyHessian2Policy                = "dubbo-proxy-hessian2-http-context"
	differentialErrorLogLoggerClickHouseDeliveryPolicy  = "error-log-logger-clickhouse-fixture-delivery"
	differentialFeishuAuthFixtureOAuthPolicy            = "feishu-auth-fixture-oauth"
	differentialGoogleCloudLoggingFixtureDeliveryPolicy = "google-cloud-logging-oauth-entry-delivery"
	differentialKafkaLoggerProducePolicy                = "kafka-logger-produce"
	differentialKafkaProxyPubSubPolicy                  = "kafka-proxy-pubsub-record"
	differentialLimitConnGlobalSharedCapacityPolicy     = "limit-conn-global-shared-capacity"
	differentialMCPBridgeSSESessionPolicy               = "mcp-bridge-sse-session"
	differentialOPAFixtureDecisionPolicy                = "opa-fixture-decision"
	differentialOpenTelemetryOTLPHTTPServerSpanPolicy   = "opentelemetry-otlp-http-server-span-core"
	differentialRocketMQLoggerPublishPolicy             = "rocketmq-logger-publish"
	differentialSLSLoggerTLSDeliveryPolicy              = "sls-logger-rfc5424-tls-delivery"
	differentialServerInfoControlAPIPolicy              = "server-info-control-api"
	differentialSkyWalkingLoggerFixtureDeliveryPolicy   = "skywalking-logger-fixture-delivery"
	differentialSkyWalkingSW8FullSamplingPolicy         = "skywalking-sw8-full-sampling"
	differentialSyslogTCPDeliveryPolicy                 = "syslog-rfc5424-tcp-delivery"
	differentialTCPLoggerFixtureDeliveryPolicy          = "tcp-logger-fixture-delivery"
	differentialUDPLoggerFixtureDeliveryPolicy          = "udp-logger-fixture-delivery"
)
