package pluginintegration

import (
	"crypto/sha256"
	"encoding/base64"
	"encoding/hex"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"net"
	"net/http"
	"os"
	"path/filepath"
	"regexp"
	"slices"
	"sort"
	"strconv"
	"strings"
	"time"

	"go.yaml.in/yaml/v3"
)

const (
	compatibilityOracleSourceCommit    = "9ef2ecab67f652d38365049613610ef649bb4ad0"
	compatibilityOracleImage           = "apache/apisix:3.17.0-debian"
	compatibilityOracleRepository      = "docker.io/apache/apisix"
	compatibilityOracleVersion         = "3.17.0"
	compatibilityOracleImageDigest     = "sha256:5a8d7dfd8382aebfc0cab7bf9d24edf8dd73a6f0eed0b789d25578a373e86f64"
	differentialSuite                  = "apisix-3.17-plugin-differential-v1"
	differentialRequiredPluginCount    = 111
	differentialFixturePlaceholder     = "{{FIXTURE.ADDR}}"
	differentialFixtureHostPlaceholder = "{{FIXTURE.HOST}}"
	differentialFixturePortPlaceholder = "{{FIXTURE.PORT}}"
	differentialSideFilePlaceholder    = "{{SIDE.FILE}}"

	// This policy is limited to errors whose representation is owned by the
	// serving platform (NGINX in APISIX, net/http in apisix-go). It never
	// relaxes status, routing, upstream, Host, SNI, retry, or security fields.
	differentialComparisonPlatformOwnedErrorRepresentation = "platform-owned-error-representation"
	// Redirect status and Location are plugin-owned, while APISIX's HTML body
	// and related content headers are generated by NGINX rather than redirect.
	differentialComparisonPlatformOwnedRedirectRepresentation = "platform-owned-redirect-representation"
	// Some plugins receive the fixture URL as their own outbound endpoint. The
	// authority is projected to different ports, while APISIX's Lua query-table
	// encoding has no stable key order. Values and all other fields stay exact.
	differentialComparisonFixtureOwnedUpstreamEndpoint = "fixture-owned-upstream-endpoint"
	// Error-page owns the response media type; the serving platform may append
	// only its UTF-8 charset parameter.
	differentialComparisonErrorPageCharsetParameter = "error-page-charset-parameter"
	// Forward-auth owns status, body, and copied headers. For an empty denied
	// response, the oracle platform alone may synthesize text/plain UTF-8.
	differentialComparisonForwardAuthEmptyErrorContentType = "forward-auth-empty-error-content-type"
	// The GraphQL plugins reject HEAD before proxying. APISIX's NGINX layer
	// alone adds text/html UTF-8 to the otherwise empty 405 response.
	differentialComparisonGraphQLHeadErrorContentType = "graphql-head-error-content-type"
	// Limit-count's fixed-window reset is a relative clock value. The pinned
	// APISIX oracle also renders a denied 503 through NGINX, while apisix-go
	// returns the same status with an empty platform response.
	differentialComparisonLimitCountFixedWindowResponse = "limit-count-fixed-window-response"
	// Cas-auth's callback rejection is otherwise exact. Go's net/http response
	// writer alone adds X-Content-Type-Options: nosniff for the plain-text 401.
	differentialComparisonCASAuthCallbackNosniff = "cas-auth-callback-nosniff"
)

var sha256DigestPattern = regexp.MustCompile(`^sha256:[0-9a-f]{64}$`)

// OracleIdentity is the complete identity needed to reproduce the official
// APISIX compatibility oracle. The image tag is descriptive; execution must
// use ImageReference, which is digest qualified.
type OracleIdentity struct {
	SchemaVersion    int    `yaml:"schema_version"           json:"schema_version"`
	ImageTag         string `yaml:"image_tag"                json:"image_tag"`
	ImageRepository  string `yaml:"image_repository"         json:"image_repository"`
	ImageIndexDigest string `yaml:"image_index_digest"       json:"image_index_digest"`
	ImageLinuxAMD64  string `yaml:"image_linux_amd64_digest" json:"image_linux_amd64_digest"`
	SourceRepository string `yaml:"source_repository"        json:"source_repository"`
	SourceCommit     string `yaml:"source_commit"            json:"source_commit"`
	ExpectedVersion  string `yaml:"expected_version"         json:"expected_version"`
}

func (identity OracleIdentity) ImageReference() string {
	return identity.ImageRepository + "@" + identity.ImageLinuxAMD64
}

func (identity OracleIdentity) Validate() error {
	if identity.SchemaVersion != 1 {
		return fmt.Errorf("oracle schema_version = %d, want 1", identity.SchemaVersion)
	}
	if identity.ImageTag != compatibilityOracleImage {
		return fmt.Errorf(
			"oracle image_tag = %q, want %q",
			identity.ImageTag,
			compatibilityOracleImage,
		)
	}
	if identity.ImageRepository != compatibilityOracleRepository {
		return fmt.Errorf(
			"oracle image_repository = %q, want %q",
			identity.ImageRepository,
			compatibilityOracleRepository,
		)
	}
	if identity.ImageLinuxAMD64 != compatibilityOracleImageDigest {
		return fmt.Errorf(
			"oracle linux/amd64 digest = %q, want %q",
			identity.ImageLinuxAMD64,
			compatibilityOracleImageDigest,
		)
	}
	if !sha256DigestPattern.MatchString(identity.ImageIndexDigest) {
		return fmt.Errorf(
			"oracle image index digest is not sha256-qualified: %q",
			identity.ImageIndexDigest,
		)
	}
	if !sha256DigestPattern.MatchString(identity.ImageLinuxAMD64) {
		return fmt.Errorf(
			"oracle linux/amd64 digest is not sha256-qualified: %q",
			identity.ImageLinuxAMD64,
		)
	}
	if identity.SourceRepository != "https://github.com/apache/apisix" {
		return fmt.Errorf("oracle source_repository = %q", identity.SourceRepository)
	}
	if identity.SourceCommit != compatibilityOracleSourceCommit {
		return fmt.Errorf(
			"oracle source_commit = %q, want %q",
			identity.SourceCommit,
			compatibilityOracleSourceCommit,
		)
	}
	if identity.ExpectedVersion != compatibilityOracleVersion {
		return fmt.Errorf(
			"oracle expected_version = %q, want %q",
			identity.ExpectedVersion,
			compatibilityOracleVersion,
		)
	}
	return nil
}

func loadOracleIdentity(path string) (OracleIdentity, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		return OracleIdentity{}, fmt.Errorf("read oracle identity %s: %w", path, err)
	}
	decoder := yaml.NewDecoder(strings.NewReader(string(data)))
	decoder.KnownFields(true)
	var identity OracleIdentity
	if err := decoder.Decode(&identity); err != nil {
		return OracleIdentity{}, fmt.Errorf("decode oracle identity %s: %w", path, err)
	}
	var extra any
	if err := decoder.Decode(&extra); !errors.Is(err, io.EOF) {
		if err == nil {
			return OracleIdentity{}, fmt.Errorf(
				"oracle identity %s contains multiple YAML documents",
				path,
			)
		}
		return OracleIdentity{}, fmt.Errorf("decode oracle identity %s: %w", path, err)
	}
	if err := identity.Validate(); err != nil {
		return OracleIdentity{}, err
	}
	return identity, nil
}

type DifferentialRequestTarget string

const (
	DifferentialRequestTargetData    DifferentialRequestTarget = ""
	DifferentialRequestTargetControl DifferentialRequestTarget = "control"
	differentialOracleDataPort                                 = 9080
	differentialOracleControlPort                              = 9090
)

type DifferentialRequest struct {
	Method  string                    `json:"method"`
	Path    string                    `json:"path"`
	Host    string                    `json:"host"`
	Target  DifferentialRequestTarget `json:"target,omitempty"`
	SNI     string                    `json:"sni,omitempty"`
	Headers map[string]string         `json:"headers,omitempty"`
	Body    string                    `json:"body,omitempty"`
}

type DifferentialFixture struct {
	Name                     string                      `json:"name"`
	WireProtocol             string                      `json:"wire_protocol,omitempty"`
	Response                 DifferentialFixtureResponse `json:"response"`
	ExpectedCalls            int                         `json:"expected_calls"`
	CaptureAllCalls          bool                        `json:"capture_all_calls,omitempty"`
	OmitHTTPOriginCall       bool                        `json:"omit_http_origin_call,omitempty"`
	CollectTimeoutMillis     int                         `json:"collect_timeout_millis,omitempty"`
	RequestWindowQuietMillis int                         `json:"request_window_quiet_millis,omitempty"`
	SemanticHeaders          []string                    `json:"semantic_headers,omitempty"`
}

func validateDifferentialFixtureRequestWindow(fixture DifferentialFixture) error {
	if fixture.RequestWindowQuietMillis < 0 || fixture.RequestWindowQuietMillis > 10_000 {
		return fmt.Errorf(
			"differential fixture request_window_quiet_millis = %d, want 0..10000",
			fixture.RequestWindowQuietMillis,
		)
	}
	if fixture.RequestWindowQuietMillis == 0 {
		return nil
	}
	if fixture.ExpectedCalls <= 0 {
		return fmt.Errorf(
			"differential fixture request window expected_calls = %d, want greater than 0",
			fixture.ExpectedCalls,
		)
	}
	if fixture.CollectTimeoutMillis > 0 &&
		fixture.RequestWindowQuietMillis >= fixture.CollectTimeoutMillis {
		return fmt.Errorf(
			"differential fixture request_window_quiet_millis = %d, want less than collect_timeout_millis %d",
			fixture.RequestWindowQuietMillis,
			fixture.CollectTimeoutMillis,
		)
	}
	return nil
}

type DifferentialFixtureResponse struct {
	Status      int               `json:"status"`
	Headers     map[string]string `json:"headers,omitempty"`
	Body        string            `json:"body,omitempty"`
	DelayMillis int               `json:"delay_millis,omitempty"`
}

// DifferentialStep is one request in a stateful plugin case. All steps run
// against the same candidate or oracle process and share the same fixture.
type DifferentialStep struct {
	Request            DifferentialRequest   `json:"request"`
	ConcurrentRequests []DifferentialRequest `json:"concurrent_requests,omitempty"`
	SecurityDecision   string                `json:"security_decision"`
	DelayBeforeMillis  int                   `json:"delay_before_millis,omitempty"`
}

type DifferentialCase struct {
	Name             string                   `json:"name"`
	Plugin           string                   `json:"plugin"`
	RouteID          string                   `json:"route_id"`
	ComparisonPolicy string                   `json:"comparison_policy,omitempty"`
	Config           map[string]any           `json:"-"`
	Request          DifferentialRequest      `json:"request"`
	Steps            []DifferentialStep       `json:"steps,omitempty"`
	Fixture          DifferentialFixture      `json:"fixture"`
	File             *DifferentialFileCapture `json:"file,omitempty"`
	SecurityDecision string                   `json:"security_decision"`
}

type DifferentialFileCapture struct {
	Name              string `json:"name"`
	MaxBytes          int64  `json:"max_bytes"`
	WaitTimeoutMillis int    `json:"wait_timeout_millis"`
	ExpectedLines     int    `json:"expected_lines"`
}

type DifferentialFileObservation struct {
	Name      string `json:"name"`
	Exists    bool   `json:"exists"`
	Size      int64  `json:"size"`
	Content   string `json:"content,omitempty"`
	Truncated bool   `json:"truncated,omitempty"`
}

type DifferentialUpstreamObservation struct {
	Received bool                `json:"received"`
	Fixture  string              `json:"fixture,omitempty"`
	Method   string              `json:"method,omitempty"`
	Path     string              `json:"path,omitempty"`
	Host     string              `json:"host,omitempty"`
	Headers  map[string][]string `json:"headers,omitempty"`
	Body     string              `json:"body,omitempty"`
}

type DifferentialStepObservation struct {
	Status           int                 `json:"status"`
	Headers          map[string][]string `json:"headers"`
	Body             string              `json:"body"`
	Host             string              `json:"host"`
	SNI              string              `json:"sni,omitempty"`
	SecurityDecision string              `json:"security_decision"`
}

// DifferentialObservation intentionally keeps semantic fields separate from
// the transport headers. Normalization only touches the latter and a mapped
// fixture endpoint; status, body, route/upstream choice, retry count, Host,
// SNI, and security decision remain exact comparisons.
type DifferentialObservation struct {
	Steps            []DifferentialStepObservation     `json:"steps,omitempty"`
	Status           int                               `json:"status"`
	Headers          map[string][]string               `json:"headers"`
	Body             string                            `json:"body"`
	RouteObserver    map[string][]string               `json:"route_observer,omitempty"`
	UpstreamFixture  string                            `json:"upstream_fixture,omitempty"`
	UpstreamAddress  string                            `json:"upstream_address,omitempty"`
	RetryCount       int                               `json:"retry_count"`
	Host             string                            `json:"host"`
	SNI              string                            `json:"sni,omitempty"`
	SecurityDecision string                            `json:"security_decision"`
	Upstream         DifferentialUpstreamObservation   `json:"upstream"`
	UpstreamCalls    []DifferentialUpstreamObservation `json:"upstream_calls,omitempty"`
	File             *DifferentialFileObservation      `json:"file,omitempty"`
}

type DifferentialCaseResult struct {
	Name             string                   `json:"name"`
	Plugin           string                   `json:"plugin"`
	Obligation       string                   `json:"obligation"`
	ComparisonPolicy string                   `json:"comparison_policy,omitempty"`
	FirstAttempt     bool                     `json:"first_attempt"`
	Passed           bool                     `json:"passed"`
	Candidate        *DifferentialObservation `json:"candidate,omitempty"`
	Oracle           *DifferentialObservation `json:"oracle,omitempty"`
	CandidateHash    string                   `json:"candidate_hash,omitempty"`
	OracleHash       string                   `json:"oracle_hash,omitempty"`
	Error            string                   `json:"error,omitempty"`
}

type DifferentialSelection struct {
	Plugins    []string `json:"plugins"`
	Cases      []string `json:"cases"`
	ShardIndex int      `json:"shard_index"`
	ShardCount int      `json:"shard_count"`
}

func selectDifferentialCases(
	all []DifferentialCase,
	selection DifferentialSelection,
) ([]DifferentialCase, DifferentialSelection, error) {
	if selection.ShardCount < 1 {
		return nil, DifferentialSelection{}, fmt.Errorf(
			"differential shard count = %d, want at least 1",
			selection.ShardCount,
		)
	}
	if selection.ShardIndex < 0 || selection.ShardIndex >= selection.ShardCount {
		return nil, DifferentialSelection{}, fmt.Errorf(
			"differential shard index = %d, want 0 <= index < %d",
			selection.ShardIndex,
			selection.ShardCount,
		)
	}

	caseByName := make(map[string]DifferentialCase, len(all))
	knownPlugins := make(map[string]struct{}, len(all))
	for _, spec := range all {
		if strings.TrimSpace(spec.Name) == "" || strings.TrimSpace(spec.Plugin) == "" {
			return nil, DifferentialSelection{}, fmt.Errorf(
				"runtime differential case has incomplete identity: name=%q plugin=%q",
				spec.Name,
				spec.Plugin,
			)
		}
		if _, exists := caseByName[spec.Name]; exists {
			return nil, DifferentialSelection{}, fmt.Errorf(
				"runtime differential cases contain duplicate case %q",
				spec.Name,
			)
		}
		caseByName[spec.Name] = spec
		knownPlugins[spec.Plugin] = struct{}{}
	}
	if len(caseByName) == 0 {
		return nil, DifferentialSelection{}, errors.New("runtime differential cases are empty")
	}

	plugins, err := normalizeDifferentialSelectors("plugin", selection.Plugins, knownPlugins)
	if err != nil {
		return nil, DifferentialSelection{}, err
	}
	knownCases := make(map[string]struct{}, len(caseByName))
	for name := range caseByName {
		knownCases[name] = struct{}{}
	}
	cases, err := normalizeDifferentialSelectors("case", selection.Cases, knownCases)
	if err != nil {
		return nil, DifferentialSelection{}, err
	}
	normalized := DifferentialSelection{
		Plugins:    plugins,
		Cases:      cases,
		ShardIndex: selection.ShardIndex,
		ShardCount: selection.ShardCount,
	}

	pluginFilter := makeStringSet(plugins)
	caseFilter := makeStringSet(cases)
	sorted := append([]DifferentialCase(nil), all...)
	sort.Slice(sorted, func(i, j int) bool { return sorted[i].Name < sorted[j].Name })
	filtered := make([]DifferentialCase, 0, len(sorted))
	for _, spec := range sorted {
		if len(pluginFilter) > 0 {
			if _, selected := pluginFilter[spec.Plugin]; !selected {
				continue
			}
		}
		if len(caseFilter) > 0 {
			if _, selected := caseFilter[spec.Name]; !selected {
				continue
			}
		}
		filtered = append(filtered, spec)
	}
	if len(filtered) == 0 {
		return nil, DifferentialSelection{}, errors.New("differential selection selects no differential cases")
	}

	selected := make([]DifferentialCase, 0, len(filtered))
	for index, spec := range filtered {
		if index%normalized.ShardCount == normalized.ShardIndex {
			selected = append(selected, spec)
		}
	}
	if len(selected) == 0 {
		return nil, DifferentialSelection{}, errors.New("differential shard selects no differential cases")
	}
	return selected, normalized, nil
}

func normalizeDifferentialSelectors(
	kind string,
	selectors []string,
	known map[string]struct{},
) ([]string, error) {
	normalized := make([]string, 0, len(selectors))
	seen := make(map[string]struct{}, len(selectors))
	for _, raw := range selectors {
		selector := strings.TrimSpace(raw)
		if selector == "" {
			return nil, fmt.Errorf("blank %s selector", kind)
		}
		if _, exists := seen[selector]; exists {
			return nil, fmt.Errorf("duplicate %s selector %q", kind, selector)
		}
		if _, exists := known[selector]; !exists {
			return nil, fmt.Errorf("unknown %s selector %q", kind, selector)
		}
		seen[selector] = struct{}{}
		normalized = append(normalized, selector)
	}
	sort.Strings(normalized)
	return normalized, nil
}

func makeStringSet(values []string) map[string]struct{} {
	set := make(map[string]struct{}, len(values))
	for _, value := range values {
		set[value] = struct{}{}
	}
	return set
}

type DifferentialArtifact struct {
	SchemaVersion int                           `json:"schema_version"`
	Suite         string                        `json:"suite"`
	CatalogSHA256 string                        `json:"catalog_sha256"`
	Selection     DifferentialArtifactSelection `json:"selection"`
	Attempt       int                           `json:"attempt"`
	FirstAttempt  bool                          `json:"first_attempt"`
	Candidate     DifferentialCandidateID       `json:"candidate"`
	Oracle        OracleIdentity                `json:"oracle"`
	Cases         []DifferentialCaseResult      `json:"cases"`
	Coverage      DifferentialCoverage          `json:"coverage"`
	Plugins       []DifferentialPluginResult    `json:"plugins"`
	Passed        int                           `json:"passed"`
	Failed        int                           `json:"failed"`
	Result        string                        `json:"result"`
}

type DifferentialArtifactSelection struct {
	Plugins           []string `json:"plugins"`
	Cases             []string `json:"cases"`
	ShardIndex        int      `json:"shard_index"`
	ShardCount        int      `json:"shard_count"`
	SelectedCaseCount int      `json:"selected_case_count"`
	FullCatalogRun    bool     `json:"full_catalog_run"`
}

type DifferentialCoverage struct {
	RequiredPlugins []string `json:"required_plugins"`
	CoveredPlugins  []string `json:"covered_plugins"`
	RequiredCount   int      `json:"required_count"`
	CoveredCount    int      `json:"covered_count"`
}

type DifferentialPluginResult struct {
	Plugin          string   `json:"plugin"`
	ObligationNames []string `json:"obligation_names"`
	CaseNames       []string `json:"case_names"`
	Obligations     int      `json:"obligations"`
	FirstAttempt    bool     `json:"first_attempt"`
	Passed          int      `json:"passed"`
	Failed          int      `json:"failed"`
	Result          string   `json:"result"`
}

type DifferentialCatalog struct {
	SchemaVersion    int                       `yaml:"schema_version"`
	Suite            string                    `yaml:"suite"`
	RequiredPlugins  []string                  `yaml:"-"`
	Cases            []DifferentialCatalogCase `yaml:"cases"`
	CatalogSHA256    string                    `yaml:"-"`
	fullCases        []DifferentialCatalogCase
	fullRuntimeCases []DifferentialCase
}

type DifferentialCatalogCase struct {
	Plugin     string `yaml:"plugin"`
	Obligation string `yaml:"obligation"`
	Case       string `yaml:"case"`
}

type DifferentialCandidateID struct {
	SourceCommit string `json:"source_commit"`
	BinarySHA256 string `json:"binary_sha256"`
}

func loadDifferentialCatalog(
	path string,
	runtimeCases []DifferentialCase,
) (DifferentialCatalog, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		return DifferentialCatalog{}, fmt.Errorf("read differential catalog %s: %w", path, err)
	}
	decoder := yaml.NewDecoder(strings.NewReader(string(data)))
	decoder.KnownFields(true)
	var catalog DifferentialCatalog
	if err := decoder.Decode(&catalog); err != nil {
		return DifferentialCatalog{}, fmt.Errorf("decode differential catalog %s: %w", path, err)
	}
	var extra any
	if err := decoder.Decode(&extra); !errors.Is(err, io.EOF) {
		if err == nil {
			return DifferentialCatalog{}, fmt.Errorf(
				"differential catalog %s contains multiple YAML documents",
				path,
			)
		}
		return DifferentialCatalog{}, fmt.Errorf("decode differential catalog %s: %w", path, err)
	}
	catalog.RequiredPlugins = differentialRequiredPlugins(catalog.Cases)
	if err := validateDifferentialCatalog(catalog, runtimeCases); err != nil {
		return DifferentialCatalog{}, err
	}
	digest := sha256.Sum256(data)
	catalog.CatalogSHA256 = "sha256:" + hex.EncodeToString(digest[:])
	catalog.fullCases = append([]DifferentialCatalogCase(nil), catalog.Cases...)
	catalog.fullRuntimeCases = append([]DifferentialCase(nil), runtimeCases...)
	return catalog, nil
}

func differentialRequiredPlugins(cases []DifferentialCatalogCase) []string {
	required := make(map[string]struct{}, len(cases))
	for _, row := range cases {
		if row.Plugin != "" {
			required[row.Plugin] = struct{}{}
		}
	}
	plugins := make([]string, 0, len(required))
	for plugin := range required {
		plugins = append(plugins, plugin)
	}
	sort.Strings(plugins)
	return plugins
}

func validateDifferentialCatalog(
	catalog DifferentialCatalog,
	runtimeCases []DifferentialCase,
) error {
	if catalog.SchemaVersion != 2 {
		return fmt.Errorf("differential catalog schema_version = %d, want 2", catalog.SchemaVersion)
	}
	if catalog.Suite != differentialSuite {
		return fmt.Errorf(
			"differential catalog suite = %q, want %q",
			catalog.Suite,
			differentialSuite,
		)
	}
	if len(catalog.RequiredPlugins) != differentialRequiredPluginCount {
		return fmt.Errorf(
			"differential catalog required plugins = %d, want %d",
			len(catalog.RequiredPlugins),
			differentialRequiredPluginCount,
		)
	}
	if !slices.IsSorted(catalog.RequiredPlugins) {
		return errors.New("differential catalog required_plugins must be sorted")
	}
	required := make(map[string]struct{}, len(catalog.RequiredPlugins))
	for _, plugin := range catalog.RequiredPlugins {
		if strings.TrimSpace(plugin) == "" {
			return errors.New("differential catalog required_plugins contains a blank plugin")
		}
		if _, exists := required[plugin]; exists {
			return fmt.Errorf("differential catalog contains duplicate required plugin %q", plugin)
		}
		required[plugin] = struct{}{}
	}
	runtimeByName := make(map[string]DifferentialCase, len(runtimeCases))
	for _, runtimeCase := range runtimeCases {
		if err := validateDifferentialFixtureRequestWindow(runtimeCase.Fixture); err != nil {
			return fmt.Errorf("runtime differential case %q: %w", runtimeCase.Name, err)
		}
		if _, exists := runtimeByName[runtimeCase.Name]; exists {
			return fmt.Errorf(
				"runtime differential cases contain duplicate case %q",
				runtimeCase.Name,
			)
		}
		runtimeByName[runtimeCase.Name] = runtimeCase
	}
	seenKeys := make(map[string]struct{}, len(catalog.Cases))
	seenCases := make(map[string]struct{}, len(catalog.Cases))
	for _, row := range catalog.Cases {
		if row.Plugin == "" || row.Obligation == "" || row.Case == "" {
			return fmt.Errorf("differential catalog contains incomplete row: %#v", row)
		}
		if _, exists := required[row.Plugin]; !exists {
			return fmt.Errorf(
				"differential catalog plugin %q is not required by %s",
				row.Plugin,
				catalog.Suite,
			)
		}
		key := row.Plugin + "\x00" + row.Obligation
		if _, exists := seenKeys[key]; exists {
			return fmt.Errorf(
				"differential catalog contains duplicate plugin/obligation %q/%q",
				row.Plugin,
				row.Obligation,
			)
		}
		seenKeys[key] = struct{}{}
		if _, exists := seenCases[row.Case]; exists {
			return fmt.Errorf("differential catalog case %q is referenced more than once", row.Case)
		}
		seenCases[row.Case] = struct{}{}
		runtimeCase, exists := runtimeByName[row.Case]
		if !exists {
			return fmt.Errorf("differential catalog case %q has no runtime case", row.Case)
		}
		if runtimeCase.Plugin != row.Plugin {
			return fmt.Errorf(
				"differential catalog case %q plugin = %q, runtime plugin = %q",
				row.Case,
				row.Plugin,
				runtimeCase.Plugin,
			)
		}
	}
	if len(seenCases) != len(runtimeByName) {
		return fmt.Errorf(
			"differential catalog references %d/%d runtime cases",
			len(seenCases),
			len(runtimeByName),
		)
	}
	return nil
}

func selectDifferentialCatalog(
	full DifferentialCatalog,
	selected []DifferentialCase,
) (DifferentialCatalog, error) {
	selectedByName := make(map[string]DifferentialCase, len(selected))
	for _, spec := range selected {
		if strings.TrimSpace(spec.Name) == "" || strings.TrimSpace(spec.Plugin) == "" {
			return DifferentialCatalog{}, fmt.Errorf(
				"selected differential case has incomplete identity: name=%q plugin=%q",
				spec.Name,
				spec.Plugin,
			)
		}
		if _, exists := selectedByName[spec.Name]; exists {
			return DifferentialCatalog{}, fmt.Errorf(
				"selected differential cases contain duplicate case %q",
				spec.Name,
			)
		}
		selectedByName[spec.Name] = spec
	}
	if len(selectedByName) == 0 {
		return DifferentialCatalog{}, errors.New("selected differential cases are empty")
	}

	rows := make([]DifferentialCatalogCase, 0, len(selectedByName))
	for _, row := range full.Cases {
		spec, selected := selectedByName[row.Case]
		if !selected {
			continue
		}
		if spec.Plugin != row.Plugin {
			return DifferentialCatalog{}, fmt.Errorf(
				"selected differential case %q plugin = %q, catalog plugin = %q",
				row.Case,
				spec.Plugin,
				row.Plugin,
			)
		}
		rows = append(rows, row)
		delete(selectedByName, row.Case)
	}
	if len(selectedByName) != 0 {
		missing := make([]string, 0, len(selectedByName))
		for name := range selectedByName {
			missing = append(missing, name)
		}
		sort.Strings(missing)
		return DifferentialCatalog{}, fmt.Errorf(
			"selected differential cases are absent from the catalog: %s",
			strings.Join(missing, ", "),
		)
	}
	sort.Slice(rows, func(i, j int) bool { return rows[i].Case < rows[j].Case })
	selectedCatalog := full
	selectedCatalog.RequiredPlugins = append([]string(nil), full.RequiredPlugins...)
	selectedCatalog.Cases = rows
	return selectedCatalog, nil
}

func buildDifferentialArtifact(
	catalog DifferentialCatalog,
	candidate DifferentialCandidateID,
	oracle OracleIdentity,
	results []DifferentialCaseResult,
) (DifferentialArtifact, error) {
	return buildSelectedDifferentialArtifact(
		catalog,
		differentialCases(),
		DifferentialSelection{ShardIndex: 0, ShardCount: 1},
		candidate,
		oracle,
		results,
	)
}

func buildSelectedDifferentialArtifact(
	catalog DifferentialCatalog,
	runtimeCases []DifferentialCase,
	selection DifferentialSelection,
	candidate DifferentialCandidateID,
	oracle OracleIdentity,
	results []DifferentialCaseResult,
) (DifferentialArtifact, error) {
	if err := validateDifferentialCatalog(catalog, runtimeCases); err != nil {
		return DifferentialArtifact{}, err
	}
	if err := validateNormalizedDifferentialSelection(selection); err != nil {
		return DifferentialArtifact{}, err
	}
	if !sha256DigestPattern.MatchString(catalog.CatalogSHA256) {
		return DifferentialArtifact{}, fmt.Errorf(
			"differential catalog hash is not sha256-qualified: %q",
			catalog.CatalogSHA256,
		)
	}
	if err := validateDifferentialSelectionBinding(catalog, runtimeCases, selection); err != nil {
		return DifferentialArtifact{}, err
	}
	rowsByCase := make(map[string]DifferentialCatalogCase, len(catalog.Cases))
	runtimeByCase := make(map[string]DifferentialCase, len(runtimeCases))
	for _, spec := range runtimeCases {
		runtimeByCase[spec.Name] = spec
	}
	coveredSet := make(map[string]struct{}, len(catalog.Cases))
	for _, row := range catalog.Cases {
		rowsByCase[row.Case] = row
		coveredSet[row.Plugin] = struct{}{}
	}
	seenResults := make(map[string]struct{}, len(results))
	annotated := make([]DifferentialCaseResult, 0, len(results))
	aggregates := make(map[string]*DifferentialPluginResult, len(coveredSet))
	passed := 0
	firstAttempt := true
	for _, result := range results {
		row, exists := rowsByCase[result.Name]
		if !exists {
			return DifferentialArtifact{}, fmt.Errorf(
				"differential result %q is absent from the catalog",
				result.Name,
			)
		}
		if _, exists := seenResults[result.Name]; exists {
			return DifferentialArtifact{}, fmt.Errorf(
				"duplicate differential result %q",
				result.Name,
			)
		}
		seenResults[result.Name] = struct{}{}
		if result.Plugin != row.Plugin {
			return DifferentialArtifact{}, fmt.Errorf(
				"differential result %q plugin = %q, runtime plugin = %q",
				result.Name,
				result.Plugin,
				runtimeByCase[result.Name].Plugin,
			)
		}
		if result.ComparisonPolicy != runtimeByCase[result.Name].ComparisonPolicy {
			return DifferentialArtifact{}, fmt.Errorf(
				"differential result %q comparison policy = %q, runtime comparison policy = %q",
				result.Name,
				result.ComparisonPolicy,
				runtimeByCase[result.Name].ComparisonPolicy,
			)
		}
		result.Obligation = row.Obligation
		annotated = append(annotated, result)
		aggregate := aggregates[row.Plugin]
		if aggregate == nil {
			aggregate = &DifferentialPluginResult{
				Plugin:       row.Plugin,
				FirstAttempt: true,
				Result:       "pass",
			}
			aggregates[row.Plugin] = aggregate
		}
		aggregate.ObligationNames = append(aggregate.ObligationNames, row.Obligation)
		aggregate.CaseNames = append(aggregate.CaseNames, row.Case)
		aggregate.Obligations++
		aggregate.FirstAttempt = aggregate.FirstAttempt && result.FirstAttempt
		if result.Passed {
			aggregate.Passed++
			passed++
		} else {
			aggregate.Failed++
			aggregate.Result = "fail"
		}
		if !result.FirstAttempt {
			aggregate.Result = "fail"
		}
		firstAttempt = firstAttempt && result.FirstAttempt
	}
	if len(seenResults) != len(catalog.Cases) {
		return DifferentialArtifact{}, fmt.Errorf(
			"differential results cover %d/%d catalog cases",
			len(seenResults),
			len(catalog.Cases),
		)
	}
	sort.Slice(annotated, func(i, j int) bool { return annotated[i].Name < annotated[j].Name })
	coveredPlugins := make([]string, 0, len(coveredSet))
	pluginResults := make([]DifferentialPluginResult, 0, len(aggregates))
	for plugin := range coveredSet {
		coveredPlugins = append(coveredPlugins, plugin)
		pluginResult := *aggregates[plugin]
		sort.Strings(pluginResult.ObligationNames)
		sort.Strings(pluginResult.CaseNames)
		pluginResults = append(pluginResults, pluginResult)
	}
	sort.Strings(coveredPlugins)
	sort.Slice(
		pluginResults,
		func(i, j int) bool { return pluginResults[i].Plugin < pluginResults[j].Plugin },
	)
	failed := len(annotated) - passed
	result := "fail"
	if failed == 0 && firstAttempt {
		result = "pass"
	}
	return DifferentialArtifact{
		SchemaVersion: 3,
		Suite:         catalog.Suite,
		CatalogSHA256: catalog.CatalogSHA256,
		Selection: DifferentialArtifactSelection{
			Plugins:           append([]string{}, selection.Plugins...),
			Cases:             append([]string{}, selection.Cases...),
			ShardIndex:        selection.ShardIndex,
			ShardCount:        selection.ShardCount,
			SelectedCaseCount: len(runtimeCases),
			FullCatalogRun: len(selection.Plugins) == 0 && len(selection.Cases) == 0 &&
				selection.ShardIndex == 0 && selection.ShardCount == 1,
		},
		Attempt:      1,
		FirstAttempt: firstAttempt,
		Candidate:    candidate,
		Oracle:       oracle,
		Cases:        annotated,
		Coverage: DifferentialCoverage{
			RequiredPlugins: append([]string(nil), catalog.RequiredPlugins...),
			CoveredPlugins:  coveredPlugins,
			RequiredCount:   len(catalog.RequiredPlugins),
			CoveredCount:    len(coveredPlugins),
		},
		Plugins: pluginResults,
		Passed:  passed,
		Failed:  failed,
		Result:  result,
	}, nil
}

func validateDifferentialSelectionBinding(
	catalog DifferentialCatalog,
	runtimeCases []DifferentialCase,
	selection DifferentialSelection,
) error {
	if len(catalog.fullCases) == 0 || len(catalog.fullRuntimeCases) == 0 {
		return errors.New("differential selection has no complete catalog/runtime source")
	}
	fullCatalog := catalog
	fullCatalog.Cases = append([]DifferentialCatalogCase(nil), catalog.fullCases...)
	if err := validateDifferentialCatalog(fullCatalog, catalog.fullRuntimeCases); err != nil {
		return fmt.Errorf("validate complete differential selection source: %w", err)
	}
	expectedCases, _, err := selectDifferentialCases(catalog.fullRuntimeCases, selection)
	if err != nil {
		return fmt.Errorf("apply differential selection: %w", err)
	}
	expectedCatalog, err := selectDifferentialCatalog(fullCatalog, expectedCases)
	if err != nil {
		return fmt.Errorf("select differential catalog rows: %w", err)
	}
	if !slices.Equal(
		differentialCaseIdentityKeys(expectedCases),
		differentialCaseIdentityKeys(runtimeCases),
	) {
		return errors.New("selected differential runtime cases do not match selection")
	}
	actualRows := append([]DifferentialCatalogCase(nil), catalog.Cases...)
	sort.Slice(actualRows, func(i, j int) bool { return actualRows[i].Case < actualRows[j].Case })
	if !slices.Equal(expectedCatalog.Cases, actualRows) {
		return errors.New("selected differential catalog rows do not match selection")
	}
	return nil
}

func differentialCaseIdentityKeys(cases []DifferentialCase) []string {
	keys := make([]string, 0, len(cases))
	for _, spec := range cases {
		keys = append(keys, spec.Name+"\x00"+spec.Plugin+"\x00"+spec.ComparisonPolicy)
	}
	sort.Strings(keys)
	return keys
}

func validateNormalizedDifferentialSelection(selection DifferentialSelection) error {
	if selection.ShardCount < 1 {
		return fmt.Errorf("differential shard count = %d, want at least 1", selection.ShardCount)
	}
	if selection.ShardIndex < 0 || selection.ShardIndex >= selection.ShardCount {
		return fmt.Errorf(
			"differential shard index = %d, want 0 <= index < %d",
			selection.ShardIndex,
			selection.ShardCount,
		)
	}
	for kind, selectors := range map[string][]string{
		"plugin": selection.Plugins,
		"case":   selection.Cases,
	} {
		if !slices.IsSorted(selectors) {
			return fmt.Errorf("differential %s selectors are not normalized", kind)
		}
		for index, selector := range selectors {
			if selector == "" || strings.TrimSpace(selector) != selector {
				return fmt.Errorf("differential %s selectors are not normalized", kind)
			}
			if index > 0 && selectors[index-1] == selector {
				return fmt.Errorf("duplicate %s selector %q", kind, selector)
			}
		}
	}
	return nil
}

type NormalizationPolicy struct {
	SchemaVersion          int                       `yaml:"schema_version"`
	Headers                HeaderNormalizationPolicy `yaml:"headers"`
	FixtureEndpointMapping bool                      `yaml:"fixture_endpoint_mapping"`
}

type HeaderNormalizationPolicy struct {
	CanonicalizeNames        bool     `yaml:"canonicalize_names"`
	Ignore                   []string `yaml:"ignore,omitempty"`
	StripHopByHop            bool     `yaml:"strip_hop_by_hop"`
	ContentLengthIfBodyEqual bool     `yaml:"content_length_if_body_equal"`
}

var hopByHopHeaders = map[string]struct{}{
	"connection": {}, "keep-alive": {}, "proxy-authenticate": {},
	"proxy-authorization": {}, "te": {}, "trailer": {},
	"transfer-encoding": {}, "upgrade": {},
}

func loadNormalizationPolicy(path string) (NormalizationPolicy, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		return NormalizationPolicy{}, fmt.Errorf("read normalization policy %s: %w", path, err)
	}
	decoder := yaml.NewDecoder(strings.NewReader(string(data)))
	decoder.KnownFields(true)
	var policy NormalizationPolicy
	if err := decoder.Decode(&policy); err != nil {
		return NormalizationPolicy{}, fmt.Errorf("decode normalization policy %s: %w", path, err)
	}
	if err := validateNormalizationPolicy(policy); err != nil {
		return NormalizationPolicy{}, err
	}
	return policy, nil
}

func validateNormalizationPolicy(policy NormalizationPolicy) error {
	if policy.SchemaVersion != 1 {
		return fmt.Errorf("normalization schema_version = %d, want 1", policy.SchemaVersion)
	}
	if !policy.Headers.CanonicalizeNames {
		return errors.New("normalization must canonicalize header names")
	}
	for _, name := range policy.Headers.Ignore {
		name = strings.ToLower(strings.TrimSpace(name))
		if name != "date" && name != "server" {
			return fmt.Errorf("normalization cannot ignore semantic header %q", name)
		}
	}
	if !policy.Headers.StripHopByHop {
		return errors.New("normalization must declare hop-by-hop framing removal")
	}
	if !policy.Headers.ContentLengthIfBodyEqual {
		return errors.New("normalization must declare conditional content-length handling")
	}
	if !policy.FixtureEndpointMapping {
		return errors.New("normalization must declare exact fixture endpoint mapping")
	}
	return nil
}

func normalizeObservationPair(
	left DifferentialObservation,
	right DifferentialObservation,
	policy NormalizationPolicy,
) (DifferentialObservation, DifferentialObservation, error) {
	if err := validateNormalizationPolicy(policy); err != nil {
		return DifferentialObservation{}, DifferentialObservation{}, err
	}
	left.Headers = normalizeHeaders(left.Headers, policy.Headers)
	right.Headers = normalizeHeaders(right.Headers, policy.Headers)
	left.RouteObserver = normalizeHeaders(left.RouteObserver, policy.Headers)
	right.RouteObserver = normalizeHeaders(right.RouteObserver, policy.Headers)
	left.Upstream.Headers = normalizeHeaders(left.Upstream.Headers, policy.Headers)
	right.Upstream.Headers = normalizeHeaders(right.Upstream.Headers, policy.Headers)
	if len(left.UpstreamCalls) != len(right.UpstreamCalls) {
		return DifferentialObservation{}, DifferentialObservation{}, fmt.Errorf(
			"differential upstream call count differs: %d and %d",
			len(left.UpstreamCalls),
			len(right.UpstreamCalls),
		)
	}
	for index := range left.UpstreamCalls {
		left.UpstreamCalls[index].Headers = normalizeHeaders(
			left.UpstreamCalls[index].Headers,
			policy.Headers,
		)
		right.UpstreamCalls[index].Headers = normalizeHeaders(
			right.UpstreamCalls[index].Headers,
			policy.Headers,
		)
	}
	if len(left.Steps) != len(right.Steps) {
		return DifferentialObservation{}, DifferentialObservation{}, fmt.Errorf(
			"differential sequence step count differs: %d and %d",
			len(left.Steps),
			len(right.Steps),
		)
	}
	for index := range left.Steps {
		left.Steps[index].Headers = normalizeHeaders(left.Steps[index].Headers, policy.Headers)
		right.Steps[index].Headers = normalizeHeaders(right.Steps[index].Headers, policy.Headers)
		if policy.Headers.ContentLengthIfBodyEqual && left.Steps[index].Body == right.Steps[index].Body &&
			!slices.Equal(left.Steps[index].Headers["content-length"], right.Steps[index].Headers["content-length"]) {
			delete(left.Steps[index].Headers, "content-length")
			delete(right.Steps[index].Headers, "content-length")
		}
	}
	if policy.Headers.ContentLengthIfBodyEqual && left.Body == right.Body {
		if !slices.Equal(left.Headers["content-length"], right.Headers["content-length"]) {
			delete(left.Headers, "content-length")
			delete(right.Headers, "content-length")
		}
	}
	if policy.FixtureEndpointMapping {
		// The endpoint is deliberately projected to different network names:
		// 127.0.0.1 for the candidate and host.containers.internal for the
		// container. The fixture identity is retained as the semantic value.
		left.UpstreamAddress = "fixture:" + left.UpstreamFixture
		right.UpstreamAddress = "fixture:" + right.UpstreamFixture
	}
	return left, right, nil
}

func normalizeHeaders(
	headers map[string][]string,
	policy HeaderNormalizationPolicy,
) map[string][]string {
	if headers == nil {
		return nil
	}
	ignored := make(map[string]struct{}, len(policy.Ignore))
	for _, name := range policy.Ignore {
		ignored[strings.ToLower(strings.TrimSpace(name))] = struct{}{}
	}
	normalized := make(map[string][]string, len(headers))
	for name, values := range headers {
		name = strings.ToLower(http.CanonicalHeaderKey(name))
		if _, ok := ignored[name]; ok {
			continue
		}
		if policy.StripHopByHop {
			if _, ok := hopByHopHeaders[name]; ok {
				continue
			}
		}
		normalized[name] = append([]string(nil), values...)
	}
	return normalized
}

func compareNormalizedObservations(
	left DifferentialObservation,
	right DifferentialObservation,
	policy NormalizationPolicy,
) (bool, string, error) {
	left, right, err := normalizeObservationPair(left, right, policy)
	if err != nil {
		return false, "", err
	}
	leftJSON, err := json.Marshal(left)
	if err != nil {
		return false, "", fmt.Errorf("marshal candidate observation: %w", err)
	}
	rightJSON, err := json.Marshal(right)
	if err != nil {
		return false, "", fmt.Errorf("marshal oracle observation: %w", err)
	}
	if string(leftJSON) == string(rightJSON) {
		return true, "", nil
	}
	return false, fmt.Sprintf("candidate=%s oracle=%s", leftJSON, rightJSON), nil
}

func normalizeDifferentialCSRFCookie(
	spec DifferentialCase,
	observation DifferentialObservation,
) (DifferentialObservation, error) {
	observation = copyDifferentialObservation(observation)
	config, err := differentialCSRFComparisonConfig(spec)
	if err != nil {
		return DifferentialObservation{}, err
	}
	var values []string
	for name, current := range observation.Headers {
		if strings.EqualFold(name, "Set-Cookie") {
			values = append(values, current...)
			delete(observation.Headers, name)
		}
	}
	if len(values) != 1 {
		return DifferentialObservation{}, fmt.Errorf("Set-Cookie count = %d, want 1", len(values))
	}
	cookie, err := http.ParseSetCookie(values[0])
	if err != nil {
		return DifferentialObservation{}, fmt.Errorf("parse Set-Cookie: %w", err)
	}
	if cookie.Name != config.Name {
		return DifferentialObservation{}, fmt.Errorf("cookie name = %q, want %s", cookie.Name, config.Name)
	}
	timestamp, err := validateDifferentialCSRFToken(cookie.Value, config.Key)
	if err != nil {
		return DifferentialObservation{}, err
	}
	if cookie.Expires.IsZero() {
		return DifferentialObservation{}, errors.New("cookie is missing Expires")
	}
	wantExpires := time.Unix(timestamp+config.Expires, 0).UTC()
	delta := cookie.Expires.Unix() - wantExpires.Unix()
	if delta < 0 || delta > 1 {
		return DifferentialObservation{}, fmt.Errorf(
			"cookie Expires = %s, want token timestamp + configured expiry %s (or one second later)",
			cookie.Expires.UTC().Format(http.TimeFormat),
			wantExpires.Format(http.TimeFormat),
		)
	}
	unparsed := append([]string(nil), cookie.Unparsed...)
	sort.Strings(unparsed)
	observation.Headers["Set-Cookie"] = []string{
		fmt.Sprintf(
			"name=%s; quoted=%t; path=%q; domain=%q; max_age=%d; secure=%t; http_only=%t; same_site=%d; partitioned=%t; unparsed=%q",
			cookie.Name,
			cookie.Quoted,
			cookie.Path,
			cookie.Domain,
			cookie.MaxAge,
			cookie.Secure,
			cookie.HttpOnly,
			cookie.SameSite,
			cookie.Partitioned,
			unparsed,
		),
	}
	return observation, nil
}

type differentialCSRFConfig struct {
	Key     string
	Name    string
	Expires int64
}

func differentialCSRFComparisonConfig(spec DifferentialCase) (differentialCSRFConfig, error) {
	routes, ok := spec.Config["routes"].([]any)
	if !ok || len(routes) != 1 {
		return differentialCSRFConfig{}, errors.New("CSRF comparison requires exactly one route")
	}
	route, ok := routes[0].(map[string]any)
	if !ok {
		return differentialCSRFConfig{}, errors.New("CSRF comparison route is not an object")
	}
	plugins, ok := route["plugins"].(map[string]any)
	if !ok {
		return differentialCSRFConfig{}, errors.New("CSRF comparison route plugins are not an object")
	}
	pluginConfig, ok := plugins["csrf"].(map[string]any)
	if !ok {
		return differentialCSRFConfig{}, errors.New("CSRF comparison config is not an object")
	}
	key, ok := pluginConfig["key"].(string)
	if !ok || key == "" {
		return differentialCSRFConfig{}, errors.New("CSRF comparison key is missing")
	}
	name := "apisix-csrf-token"
	if configured, exists := pluginConfig["name"]; exists {
		var valid bool
		name, valid = configured.(string)
		if !valid || name == "" {
			return differentialCSRFConfig{}, errors.New("CSRF comparison cookie name is invalid")
		}
	}
	expires := int64(7200)
	if configured, exists := pluginConfig["expires"]; exists {
		var valid bool
		expires, valid = differentialInt64(configured)
		if !valid {
			return differentialCSRFConfig{}, errors.New("CSRF comparison expires is not an integer")
		}
	}
	return differentialCSRFConfig{Key: key, Name: name, Expires: expires}, nil
}

func differentialInt64(value any) (int64, bool) {
	switch typed := value.(type) {
	case int:
		return int64(typed), true
	case int64:
		return typed, true
	case float64:
		converted := int64(typed)
		return converted, float64(converted) == typed
	default:
		return 0, false
	}
}

func validateDifferentialCSRFToken(value, key string) (int64, error) {
	decoded, err := base64.StdEncoding.DecodeString(value)
	if err != nil {
		decoded, err = base64.RawStdEncoding.DecodeString(value)
	}
	if err != nil {
		return 0, fmt.Errorf("token is not base64: %w", err)
	}
	var fields map[string]json.RawMessage
	if err := json.Unmarshal(decoded, &fields); err != nil {
		return 0, fmt.Errorf("decode token JSON: %w", err)
	}
	if len(fields) != 3 || fields["random"] == nil || fields["expires"] == nil || fields["sign"] == nil {
		return 0, errors.New("token JSON must contain exactly random, expires, and sign")
	}
	var payload struct {
		Random  *float64 `json:"random"`
		Expires *int64   `json:"expires"`
		Sign    string   `json:"sign"`
	}
	if err := json.Unmarshal(decoded, &payload); err != nil {
		return 0, fmt.Errorf("decode token JSON: %w", err)
	}
	if payload.Random == nil || payload.Expires == nil || *payload.Expires <= 0 {
		return 0, errors.New("token is missing random or positive expires fields")
	}
	if *payload.Random < 0 || *payload.Random >= 1 {
		return 0, errors.New("token random must be in [0,1)")
	}
	if matched, _ := regexp.MatchString(`^[0-9a-f]{64}$`, payload.Sign); !matched {
		return 0, errors.New("token sign is not a lowercase SHA-256 digest")
	}
	want := sha256.Sum256(fmt.Appendf(nil,
		"{expires:%d,random:%v,key:%s}", *payload.Expires, *payload.Random, key,
	))
	if payload.Sign != hex.EncodeToString(want[:]) {
		return 0, errors.New("token signature does not match configured key")
	}
	return *payload.Expires, nil
}

func copyDifferentialObservation(observation DifferentialObservation) DifferentialObservation {
	observation.Steps = append([]DifferentialStepObservation(nil), observation.Steps...)
	for index := range observation.Steps {
		observation.Steps[index].Headers = copyDifferentialHeaders(observation.Steps[index].Headers)
	}
	observation.Headers = copyDifferentialHeaders(observation.Headers)
	observation.RouteObserver = copyDifferentialHeaders(observation.RouteObserver)
	observation.Upstream.Headers = copyDifferentialHeaders(observation.Upstream.Headers)
	observation.UpstreamCalls = append(
		[]DifferentialUpstreamObservation(nil),
		observation.UpstreamCalls...,
	)
	for index := range observation.UpstreamCalls {
		observation.UpstreamCalls[index].Headers = copyDifferentialHeaders(
			observation.UpstreamCalls[index].Headers,
		)
	}
	if observation.File != nil {
		file := *observation.File
		observation.File = &file
	}
	return observation
}

func copyDifferentialHeaders(headers map[string][]string) map[string][]string {
	if headers == nil {
		return nil
	}
	result := make(map[string][]string, len(headers))
	for name, values := range headers {
		result[name] = append([]string(nil), values...)
	}
	return result
}

func hashObservation(
	observation DifferentialObservation,
	policy NormalizationPolicy,
) (string, error) {
	observation = copyDifferentialObservation(observation)
	observation, _, err := normalizeObservationPair(observation, observation, policy)
	if err != nil {
		return "", err
	}
	data, err := json.Marshal(observation)
	if err != nil {
		return "", err
	}
	digest := sha256.Sum256(data)
	return "sha256:" + hex.EncodeToString(digest[:]), nil
}

func differentialCases() []DifferentialCase {
	cases := []DifferentialCase{
		{
			Name:    "proxy-rewrite-rewrite-host",
			Plugin:  "proxy-rewrite",
			RouteID: "differential-proxy-rewrite",
			Config: map[string]any{
				"routes": []any{map[string]any{
					"id": "differential-proxy-rewrite", "uri": "/hello",
					"plugins": map[string]any{"proxy-rewrite": map[string]any{
						"uri": "/rewritten", "host": "rewritten.example.test",
					}},
					"upstream": differentialUpstream(),
				}},
			},
			Request: DifferentialRequest{
				Method: http.MethodGet, Path: "/hello", Host: "gateway.example.test",
			},
			Fixture: DifferentialFixture{
				Name: "primary", ExpectedCalls: 1,
				Response: DifferentialFixtureResponse{Status: 200, Body: "proxy-rewrite"},
			},
			SecurityDecision: "allow",
		},
		{
			Name:    "cors-default-response-headers",
			Plugin:  "cors",
			RouteID: "differential-cors",
			Config: map[string]any{
				"routes": []any{map[string]any{
					"id": "differential-cors", "uri": "/hello",
					"plugins":  map[string]any{"cors": map[string]any{}},
					"upstream": differentialUpstream(),
				}},
			},
			Request: DifferentialRequest{
				Method: http.MethodGet,
				Path:   "/hello",
				Host:   "gateway.example.test",
			},
			Fixture: DifferentialFixture{
				Name: "primary", ExpectedCalls: 1,
				Response: DifferentialFixtureResponse{Status: 200, Body: "cors"},
			},
			SecurityDecision: "not_applicable",
		},
		{
			Name:    "key-auth-valid",
			Plugin:  "key-auth",
			RouteID: "differential-key-auth-valid",
			Config: map[string]any{
				"consumers": []any{map[string]any{
					"username": "differential-user",
					"plugins": map[string]any{
						"key-auth": map[string]any{"key": "differential-key"},
					},
				}},
				"routes": []any{map[string]any{
					"id": "differential-key-auth-valid", "uri": "/hello",
					"plugins":  map[string]any{"key-auth": map[string]any{}},
					"upstream": differentialUpstream(),
				}},
			},
			Request: DifferentialRequest{
				Method: http.MethodGet, Path: "/hello", Host: "gateway.example.test",
				Headers: map[string]string{"apikey": "differential-key"},
			},
			Fixture: DifferentialFixture{
				Name: "primary", ExpectedCalls: 1,
				Response: DifferentialFixtureResponse{Status: 200, Body: "key-auth"},
			},
			SecurityDecision: "allow",
		},
		{
			Name:    "key-auth-missing",
			Plugin:  "key-auth",
			RouteID: "differential-key-auth-missing",
			Config: map[string]any{
				"consumers": []any{map[string]any{
					"username": "differential-user",
					"plugins": map[string]any{
						"key-auth": map[string]any{"key": "differential-key"},
					},
				}},
				"routes": []any{map[string]any{
					"id": "differential-key-auth-missing", "uri": "/hello",
					"plugins":  map[string]any{"key-auth": map[string]any{}},
					"upstream": differentialUpstream(),
				}},
			},
			Request: DifferentialRequest{
				Method: http.MethodGet,
				Path:   "/hello",
				Host:   "gateway.example.test",
			},
			Fixture: DifferentialFixture{
				Name: "primary", ExpectedCalls: 0,
				Response: DifferentialFixtureResponse{Status: 200, Body: "unused"},
			},
			SecurityDecision: "deny",
		},
		{
			Name:    "request-validation-empty-header",
			Plugin:  "request-validation",
			RouteID: "differential-request-validation",
			Config: map[string]any{
				"routes": []any{map[string]any{
					"id": "differential-request-validation", "uri": "/validate",
					"plugins": map[string]any{"request-validation": map[string]any{
						"header_schema": map[string]any{
							"type": "object", "required": []any{"x-required"},
							"properties": map[string]any{
								"x-required": map[string]any{"type": "string"},
							},
						},
					}},
					"upstream": differentialUpstream(),
				}},
			},
			Request: DifferentialRequest{
				Method: http.MethodGet,
				Path:   "/validate",
				Host:   "gateway.example.test",
			},
			Fixture: DifferentialFixture{
				Name: "primary", ExpectedCalls: 0,
				Response: DifferentialFixtureResponse{Status: 200, Body: "unused"},
			},
			SecurityDecision: "deny",
		},
		{
			Name:    "response-rewrite-body-and-headers",
			Plugin:  "response-rewrite",
			RouteID: "differential-response-rewrite",
			Config: map[string]any{
				"routes": []any{map[string]any{
					"id": "differential-response-rewrite", "uri": "/response",
					"plugins": map[string]any{"response-rewrite": map[string]any{
						"body":    "rewritten response body",
						"headers": map[string]any{"X-Differential-Rewrite": "yes"},
					}},
					"upstream": differentialUpstream(),
				}},
			},
			Request: DifferentialRequest{
				Method: http.MethodGet,
				Path:   "/response",
				Host:   "gateway.example.test",
			},
			Fixture: DifferentialFixture{
				Name: "primary", ExpectedCalls: 1,
				Response: DifferentialFixtureResponse{Status: 200, Body: "upstream response"},
			},
			SecurityDecision: "allow",
		},
	}
	cases = append(cases, differentialEchoCases()...)
	cases = append(cases, differentialBasicAuthCases()...)
	cases = append(cases, differentialRefererRestrictionCases()...)
	cases = append(cases, differentialAttachConsumerLabelCases()...)
	cases = append(cases, differentialClientControlCases()...)
	cases = append(cases, differentialConsumerRestrictionCases()...)
	cases = append(cases, differentialCSRFCases()...)
	cases = append(cases, differentialDataMaskCases()...)
	cases = append(cases, differentialErrorLogLoggerCases()...)
	cases = append(cases, differentialGoogleCloudLoggingCases()...)
	cases = append(cases, differentialDegraphqlCases()...)
	cases = append(cases, differentialIPRestrictionCases()...)
	cases = append(cases, differentialRealIPCases()...)
	cases = append(cases, differentialRequestIDCases()...)
	cases = append(cases, differentialACLCases()...)
	cases = append(cases, differentialAIPromptDecoratorCases()...)
	cases = append(cases, differentialAIPromptGuardCases()...)
	cases = append(cases, differentialAIPromptTemplateCases()...)
	cases = append(cases, differentialBodyTransformerCases()...)
	cases = append(cases, differentialExamplePluginCases()...)
	cases = append(cases, differentialFaultInjectionCases()...)
	cases = append(cases, differentialJWEDecryptCases()...)
	cases = append(cases, differentialJWTAuthCases()...)
	cases = append(cases, differentialMockingCases()...)
	cases = append(cases, differentialMultiAuthCases()...)
	cases = append(cases, differentialOASValidatorCases()...)
	cases = append(cases, differentialOpenFunctionCases()...)
	cases = append(cases, differentialOpenWhiskCases()...)
	cases = append(cases, differentialRedirectCases()...)
	cases = append(cases, differentialServerlessPostFunctionCases()...)
	cases = append(cases, differentialTrafficLabelCases()...)
	cases = append(cases, differentialUARestrictionCases()...)
	cases = append(cases, differentialURIBlockerCases()...)
	cases = append(cases, differentialWorkflowCases()...)
	cases = append(cases, differentialZipkinCases()...)
	cases = append(cases, differentialHMACAuthCases()...)
	cases = append(cases, differentialAuthzCasbinCases()...)
	cases = append(cases, differentialAuthzCasdoorCases()...)
	cases = append(cases, differentialAuthzKeycloakCases()...)
	cases = append(cases, differentialForwardAuthCases()...)
	cases = append(cases, differentialLDAPAuthCases()...)
	cases = append(cases, differentialOpenIDConnectCases()...)
	cases = append(cases, differentialOpenTelemetryCases()...)
	cases = append(cases, differentialSkyWalkingLoggerCases()...)
	cases = append(cases, differentialSAMLAuthCases()...)
	cases = append(cases, differentialTrafficSplitCases()...)
	cases = append(cases, differentialProxyCacheCases()...)
	cases = append(cases, differentialProxyControlCases()...)
	cases = append(cases, differentialErrorPageCases()...)
	cases = append(cases, differentialExitTransformerCases()...)
	cases = append(cases, differentialBatchRequestsCases()...)
	cases = append(cases, differentialGraphQLLimitCountCases()...)
	cases = append(cases, differentialGraphQLProxyCacheCases()...)
	cases = append(cases, differentialPublicAPICases()...)
	cases = append(cases, differentialLimitCountCases()...)
	cases = append(cases, differentialLimitConnCases()...)
	cases = append(cases, differentialCASAuthCases()...)
	cases = append(cases, differentialGRPCWebCases()...)
	cases = append(cases, differentialGRPCTranscodeCases()...)
	cases = append(cases, differentialAIAliyunContentModerationCases()...)
	cases = append(cases, differentialAIRAGCases()...)
	cases = append(cases, differentialWolfRBACCases()...)
	cases = append(cases, differentialAIProxyCases()...)
	cases = append(cases, differentialAIProxyMultiCases()...)
	cases = append(cases, differentialGzipCases()...)
	cases = append(cases, differentialBrotliCases()...)
	cases = append(cases, differentialProxyMirrorCases()...)
	cases = append(cases, differentialLimitReqCases()...)
	cases = append(cases, differentialAIRateLimitingCases()...)
	cases = append(cases, differentialChaitinWAFCases()...)
	cases = append(cases, differentialAPIBreakerCases()...)
	cases = append(cases, differentialNodeStatusCases()...)
	cases = append(cases, differentialPrometheusCases()...)
	cases = append(cases, differentialAIAWSContentModerationCases()...)
	cases = append(cases, differentialAIRequestRewriteCases()...)
	cases = append(cases, differentialAWSLambdaCases()...)
	cases = append(cases, differentialServerlessPreFunctionCases()...)
	cases = append(cases, differentialAzureFunctionsCases()...)
	cases = append(cases, differentialOPACases()...)
	cases = append(cases, differentialDingTalkAuthCases()...)
	cases = append(cases, differentialFeishuAuthCases()...)
	cases = append(cases, differentialClickHouseLoggerCases()...)
	cases = append(cases, differentialElasticsearchLoggerCases()...)
	cases = append(cases, differentialHTTPLoggerCases()...)
	cases = append(cases, differentialLagoCases()...)
	cases = append(cases, differentialLogglyCases()...)
	cases = append(cases, differentialLogRotateCases()...)
	cases = append(cases, differentialLokiLoggerCases()...)
	cases = append(cases, differentialSplunkHECLoggingCases()...)
	cases = append(cases, differentialTencentCloudCLSCases()...)
	cases = append(cases, differentialDatadogCases()...)
	cases = append(cases, differentialTCPLoggerCases()...)
	cases = append(cases, differentialUDPLoggerCases()...)
	cases = append(cases, differentialSyslogCases()...)
	cases = append(cases, differentialSLSLoggerCases()...)
	cases = append(cases, differentialFileLoggerCases()...)
	cases = append(cases, differentialServerInfoCases()...)
	cases = append(cases, differentialSkyWalkingCases()...)
	cases = append(cases, differentialKafkaLoggerCases()...)
	cases = append(cases, differentialKafkaProxyCases()...)
	cases = append(cases, differentialProxyBufferingStreamingCaseSpecs()...)
	cases = append(cases, differentialMCPBridgeCases()...)
	cases = append(cases, differentialHTTPDubboCases()...)
	cases = append(cases, differentialMQTTProxyCaseSpecs()...)
	cases = append(cases, differentialRocketMQLoggerCases()...)
	cases = append(cases, differentialDubboProxyCases()...)
	return cases
}

func differentialUpstream() map[string]any {
	return map[string]any{
		"type": "roundrobin", "pass_host": "rewrite", "upstream_host": "differential.example.test",
		"nodes": map[string]any{differentialFixturePlaceholder: 1},
	}
}

func projectDifferentialConfig(config map[string]any, endpoint string) (map[string]any, error) {
	data, err := yaml.Marshal(config)
	if err != nil {
		return nil, fmt.Errorf("marshal differential config: %w", err)
	}
	var projected map[string]any
	if err := yaml.Unmarshal(data, &projected); err != nil {
		return nil, fmt.Errorf("clone differential config: %w", err)
	}
	if endpoint == "" {
		serialized := string(data)
		if strings.Contains(serialized, differentialFixturePlaceholder) ||
			strings.Contains(serialized, differentialFixtureHostPlaceholder) ||
			strings.Contains(serialized, differentialFixturePortPlaceholder) {
			return nil, errors.New("differential fixture endpoint is required for unresolved placeholders")
		}
		return projected, nil
	}
	host, portText, err := net.SplitHostPort(endpoint)
	if err != nil {
		return nil, fmt.Errorf("split differential fixture endpoint %q: %w", endpoint, err)
	}
	port, err := strconv.Atoi(portText)
	if err != nil {
		return nil, fmt.Errorf("parse differential fixture port %q: %w", portText, err)
	}
	replaceDifferentialPlaceholders(projected, endpoint, host, portText, port)
	return projected, nil
}

func replaceDifferentialPlaceholders(value any, endpoint, host, portText string, port int) {
	switch typed := value.(type) {
	case map[string]any:
		for key, child := range typed {
			projectedKey := replaceDifferentialFixtureStrings(key, endpoint, host, portText)
			if projectedKey != key {
				delete(typed, key)
				typed[projectedKey] = child
				key = projectedKey
			}
			if stringValue, ok := child.(string); ok {
				if stringValue == differentialFixturePortPlaceholder {
					typed[key] = port
				} else {
					typed[key] = replaceDifferentialFixtureStrings(stringValue, endpoint, host, portText)
				}
				continue
			}
			replaceDifferentialPlaceholders(child, endpoint, host, portText, port)
		}
	case []any:
		for i, child := range typed {
			if stringValue, ok := child.(string); ok {
				if stringValue == differentialFixturePortPlaceholder {
					typed[i] = port
				} else {
					typed[i] = replaceDifferentialFixtureStrings(stringValue, endpoint, host, portText)
				}
				continue
			}
			replaceDifferentialPlaceholders(child, endpoint, host, portText, port)
		}
	}
}

func replaceDifferentialFixtureStrings(value, endpoint, host, port string) string {
	value = strings.ReplaceAll(value, differentialFixturePlaceholder, endpoint)
	value = strings.ReplaceAll(value, differentialFixtureHostPlaceholder, host)
	return strings.ReplaceAll(value, differentialFixturePortPlaceholder, port)
}

func renderDifferentialCandidateRuntime(
	port, statusPort, controlPort int,
	workDir string,
	plugins []string,
) ([]byte, error) {
	return renderDifferentialCandidateRuntimeWithOverlay(
		port, statusPort, controlPort, workDir, plugins, nil,
	)
}

func renderDifferentialCandidateRuntimeWithOverlay(
	port, statusPort, controlPort int,
	workDir string,
	plugins []string,
	overlay map[string]any,
) ([]byte, error) {
	pluginValues := make([]any, 0, len(plugins))
	prometheusEnabled := false
	for _, plugin := range plugins {
		pluginValues = append(pluginValues, plugin)
		prometheusEnabled = prometheusEnabled || plugin == "prometheus"
	}
	runtime := map[string]any{
		"apisix": map[string]any{
			"enable_admin":   false,
			"enable_control": true,
			"control":        map[string]any{"ip": "127.0.0.1", "port": controlPort},
			"proxy_mode":     "http",
			"ssl":            map[string]any{"enable": false},
			"node_listen":    []any{map[string]any{"ip": "127.0.0.1", "port": port}},
			"status":         map[string]any{"ip": "127.0.0.1", "port": statusPort},
		},
		"deployment": map[string]any{
			"role": "data_plane", "role_data_plane": map[string]any{"config_provider": "yaml"},
		},
		"plugins": pluginValues,
		"apisix_go": map[string]any{"runtime_paths": map[string]any{
			"data_dir":    filepath.Join(workDir, "data"),
			"runtime_dir": filepath.Join(workDir, "run"),
			"log_dir":     filepath.Join(workDir, "log"),
			"temp_dir":    filepath.Join(workDir, "tmp"),
		}},
	}
	if prometheusEnabled {
		runtime["plugin_attr"] = map[string]any{
			"prometheus": map[string]any{
				"enable_export_server": false,
				"refresh_interval":     0.1,
			},
		}
	}
	if err := mergeDifferentialRuntimeOverlay(runtime, overlay); err != nil {
		return nil, err
	}
	return yaml.Marshal(runtime)
}

func renderDifferentialOracleRuntime(plugins []string) ([]byte, error) {
	return renderDifferentialOracleRuntimeWithOverlay(plugins, nil)
}

func renderDifferentialOracleRuntimeWithOverlay(
	plugins []string,
	overlay map[string]any,
) ([]byte, error) {
	pluginValues := make([]any, 0, len(plugins))
	prometheusEnabled := false
	for _, plugin := range plugins {
		pluginValues = append(pluginValues, plugin)
		prometheusEnabled = prometheusEnabled || plugin == "prometheus"
	}
	runtime := map[string]any{
		"apisix": map[string]any{
			"enable_admin":   false,
			"enable_control": true,
			"control": map[string]any{
				"ip": "127.0.0.1", "port": differentialOracleControlPort,
			},
			"node_listen": differentialOracleDataPort,
		},
		"deployment": map[string]any{
			"role": "data_plane", "role_data_plane": map[string]any{"config_provider": "yaml"},
		},
		"plugins": pluginValues,
	}
	if prometheusEnabled {
		runtime["plugin_attr"] = map[string]any{
			"prometheus": map[string]any{
				"enable_export_server": false,
				"refresh_interval":     0.1,
			},
		}
	}
	if err := mergeDifferentialRuntimeOverlay(runtime, overlay); err != nil {
		return nil, err
	}
	return yaml.Marshal(runtime)
}

func mergeDifferentialRuntimeOverlay(runtime, overlay map[string]any) error {
	for key, value := range overlay {
		if key != "plugin_attr" && key != "nginx_config" {
			return fmt.Errorf("differential runtime overlay may not replace harness-owned %q", key)
		}
		source, ok := value.(map[string]any)
		if !ok {
			return fmt.Errorf("differential runtime overlay %q must be an object", key)
		}
		target, ok := runtime[key].(map[string]any)
		if !ok {
			target = make(map[string]any)
			runtime[key] = target
		}
		mergeDifferentialRuntimeMap(target, source)
	}
	return nil
}

func mergeDifferentialRuntimeMap(target, source map[string]any) {
	for key, value := range source {
		sourceMap, sourceIsMap := value.(map[string]any)
		targetMap, targetIsMap := target[key].(map[string]any)
		if sourceIsMap && targetIsMap {
			mergeDifferentialRuntimeMap(targetMap, sourceMap)
			continue
		}
		target[key] = value
	}
}

func renderDifferentialStandalone(config map[string]any, endpoint string) ([]byte, error) {
	projected, err := projectDifferentialConfig(config, endpoint)
	if err != nil {
		return nil, err
	}
	data, err := yaml.Marshal(projected)
	if err != nil {
		return nil, err
	}
	return append(data, []byte("#END\n")...), nil
}

func writeDifferentialArtifact(path string, artifact DifferentialArtifact) error {
	if path == "" {
		return errors.New("differential artifact path is empty")
	}
	if _, err := os.Stat(path); err == nil {
		return fmt.Errorf("differential artifact already exists: %s", path)
	} else if !errors.Is(err, os.ErrNotExist) {
		return fmt.Errorf("inspect differential artifact %s: %w", path, err)
	}
	data, err := json.MarshalIndent(artifact, "", "  ")
	if err != nil {
		return fmt.Errorf("marshal differential artifact: %w", err)
	}
	data = append(data, '\n')
	if err := os.MkdirAll(filepath.Dir(path), 0o700); err != nil {
		return fmt.Errorf("create differential artifact directory: %w", err)
	}
	temp, err := os.CreateTemp(filepath.Dir(path), ".differential-artifact-*")
	if err != nil {
		return fmt.Errorf("create differential artifact temp: %w", err)
	}
	tempPath := temp.Name()
	defer func() {
		_ = temp.Close()
		_ = os.Remove(tempPath)
	}()
	if err := temp.Chmod(0o600); err != nil {
		return fmt.Errorf("chmod differential artifact: %w", err)
	}
	if _, err := temp.Write(data); err != nil {
		return fmt.Errorf("write differential artifact: %w", err)
	}
	if err := temp.Sync(); err != nil {
		return fmt.Errorf("sync differential artifact: %w", err)
	}
	if err := temp.Close(); err != nil {
		return fmt.Errorf("close differential artifact: %w", err)
	}
	if err := os.Link(tempPath, path); errors.Is(err, os.ErrExist) {
		return fmt.Errorf("differential artifact already exists: %s", path)
	} else if err != nil {
		return fmt.Errorf("publish differential artifact: %w", err)
	}
	if err := os.Remove(tempPath); err != nil {
		return fmt.Errorf("clean published differential artifact temp: %w", err)
	}
	return nil
}

func repositoryRootFromWorkingDirectory() (string, error) {
	if configured := strings.TrimSpace(os.Getenv("APISIX_GO_REPO_ROOT")); configured != "" {
		return filepath.Abs(configured)
	}
	workingDirectory, err := os.Getwd()
	if err != nil {
		return "", err
	}
	for current := workingDirectory; ; current = filepath.Dir(current) {
		if _, err := os.Stat(filepath.Join(current, "validation", "oracle.yaml")); err == nil {
			return current, nil
		}
		parent := filepath.Dir(current)
		if parent == current {
			break
		}
	}
	return "", fmt.Errorf("cannot locate repository root from %s", workingDirectory)
}

func differentialOraclePath(repoRoot string) string {
	if configured := strings.TrimSpace(os.Getenv("APISIX_GO_ORACLE_FILE")); configured != "" {
		return configured
	}
	return filepath.Join(repoRoot, "validation", "oracle.yaml")
}

func differentialCatalogPath(repoRoot string) string {
	if configured := strings.TrimSpace(os.Getenv("APISIX_GO_DIFFERENTIAL_CATALOG")); configured != "" {
		return configured
	}
	return filepath.Join(repoRoot, "validation", "differential-cases.yaml")
}

func differentialNormalizationPath(repoRoot string) string {
	if configured := strings.TrimSpace(os.Getenv("APISIX_GO_NORMALIZATION_FILE")); configured != "" {
		return configured
	}
	return filepath.Join(repoRoot, "t", "plugin", "testdata", "normalization.yaml")
}

func candidateSourceCommit() string {
	if configured := strings.TrimSpace(os.Getenv("APISIX_GO_CANDIDATE_SOURCE_COMMIT")); configured != "" {
		return configured
	}
	return "unknown"
}
