package main

import (
	"bytes"
	"errors"
	"flag"
	"fmt"
	"go/format"
	"go/token"
	"io"
	"os"
	"path/filepath"
	"sort"
	"strconv"
	"strings"

	"github.com/wklken/apisix-go/pkg/capability"
	"go.yaml.in/yaml/v3"
)

const (
	registryOutputPath        = "pkg/plugin/registry_gen.go"
	pluginsOutputPath         = "docs/plugins.md"
	readmeOutputPath          = "README.md"
	readmeChineseOutputPath   = "README.zh-CN.md"
	generatedSummaryBegin     = "<!-- BEGIN GENERATED CAPABILITY SUMMARY -->"
	generatedSummaryEnd       = "<!-- END GENERATED CAPABILITY SUMMARY -->"
	generatedSummaryNotice    = "<!-- Code generated by go run ./cmd/capability-gen -write; DO NOT EDIT. -->"
	qualificationProfileName  = "http-data-plane-v1"
	generatedDocumentPreamble = "<!-- Code generated by go run ./cmd/capability-gen -write; DO NOT EDIT. -->\n"
	adrDirectoryPath          = "docs/architecture/adr"
	adrTemplatePath           = "docs/architecture/adr/0000-template.md"
)

type readmeLocale string

const (
	readmeEnglish readmeLocale = "en"
	readmeChinese readmeLocale = "zh-CN"
)

type capabilityCounts struct {
	total                 int
	defaults              int
	applicableDefaults    int
	fullDefaults          int
	partialDefaults       int
	deferredDefaults      int
	notApplicableDefaults int
	qualified             int
	required              int
}

type generatedOutput struct {
	relativePath string
	content      []byte
}

type adrFrontMatter struct {
	ID                  string   `yaml:"id"`
	Title               string   `yaml:"title"`
	Status              string   `yaml:"status"`
	CompatibilityTarget string   `yaml:"compatibility_target"`
	DivergenceIDs       []string `yaml:"divergence_ids"`
	Owner               string   `yaml:"owner"`
	OwnerApprovalRef    string   `yaml:"owner_approval_ref"`
	Date                string   `yaml:"date"`
}

func main() {
	if err := run(os.Args[1:], os.Stderr); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}

func run(args []string, stderr io.Writer) error {
	flags := flag.NewFlagSet("capability-gen", flag.ContinueOnError)
	flags.SetOutput(stderr)
	repoRoot := flags.String("repo-root", ".", "repository root containing generated outputs")
	check := flags.Bool("check", false, "fail when generated outputs differ from disk")
	write := flags.Bool("write", false, "write generated outputs")
	if err := flags.Parse(args); err != nil {
		return err
	}
	if flags.NArg() != 0 {
		return fmt.Errorf("unexpected arguments: %s", strings.Join(flags.Args(), " "))
	}
	if *check == *write {
		return errors.New("exactly one of -check or -write must be set")
	}

	manifest, err := capability.Load()
	if err != nil {
		return fmt.Errorf("load capability manifest: %w", err)
	}
	outputs, err := buildOutputs(*repoRoot, manifest)
	if err != nil {
		return err
	}
	if *write {
		return writeOutputs(*repoRoot, outputs)
	}
	return checkOutputs(*repoRoot, outputs)
}

func buildOutputs(repoRoot string, manifest *capability.Manifest) ([]generatedOutput, error) {
	if manifest == nil {
		return nil, errors.New("build outputs: capability manifest must not be nil")
	}
	if err := validateDivergenceADRs(repoRoot, manifest); err != nil {
		return nil, err
	}
	registry, err := renderRegistry(manifest)
	if err != nil {
		return nil, err
	}
	plugins, err := renderPluginsMarkdown(manifest)
	if err != nil {
		return nil, err
	}

	root, err := openOutputRoot(repoRoot)
	if err != nil {
		return nil, err
	}
	defer func() { _ = root.Close() }()

	englishSource, err := readRootedFile(root, readmeOutputPath)
	if err != nil {
		return nil, err
	}
	englishSummary, err := renderReadmeSummary(manifest, readmeEnglish)
	if err != nil {
		return nil, err
	}
	english, err := replaceGeneratedReadmeBlock(englishSource, englishSummary)
	if err != nil {
		return nil, fmt.Errorf("replace %s generated summary: %w", readmeOutputPath, err)
	}

	chineseSource, err := readRootedFile(root, readmeChineseOutputPath)
	if err != nil {
		return nil, err
	}
	chineseSummary, err := renderReadmeSummary(manifest, readmeChinese)
	if err != nil {
		return nil, err
	}
	chinese, err := replaceGeneratedReadmeBlock(chineseSource, chineseSummary)
	if err != nil {
		return nil, fmt.Errorf("replace %s generated summary: %w", readmeChineseOutputPath, err)
	}

	return []generatedOutput{
		{relativePath: registryOutputPath, content: registry},
		{relativePath: pluginsOutputPath, content: plugins},
		{relativePath: readmeOutputPath, content: english},
		{relativePath: readmeChineseOutputPath, content: chinese},
	}, nil
}

func validateDivergenceADR(repoRoot string, divergence capability.Divergence) error {
	root, err := openOutputRoot(repoRoot)
	if err != nil {
		return fmt.Errorf("divergence %q: %w", divergence.ID, err)
	}
	defer func() { _ = root.Close() }()

	_, err = validateDivergenceADRInRoot(root, divergence)
	return err
}

func validateDivergenceADRs(repoRoot string, manifest *capability.Manifest) error {
	if manifest == nil {
		return errors.New("validate divergence ADRs: capability manifest must not be nil")
	}

	referenced := make(map[string]map[string]struct{})
	for _, divergence := range manifest.Divergences {
		if divergence.Status != capability.DivergenceAccepted {
			continue
		}
		if divergence.Compatibility != manifest.Target.Name {
			return fmt.Errorf(
				"divergence %q: compatibility_target %q does not match manifest target %q",
				divergence.ID,
				divergence.Compatibility,
				manifest.Target.Name,
			)
		}
		relativePath, err := validateADRRelativePath(divergence.ADR)
		if err != nil {
			return fmt.Errorf("divergence %q: %w", divergence.ID, err)
		}
		if err := validateDivergenceADR(repoRoot, divergence); err != nil {
			return err
		}
		if referenced[relativePath] == nil {
			referenced[relativePath] = make(map[string]struct{})
		}
		referenced[relativePath][divergence.ID] = struct{}{}
	}

	root, err := openOutputRoot(repoRoot)
	if err != nil {
		return err
	}
	defer func() { _ = root.Close() }()

	if err := rejectRootedSymlinks(root, adrDirectoryPath, "ADR directory"); err != nil {
		return err
	}
	directory, err := root.Open(adrDirectoryPath)
	if errors.Is(err, os.ErrNotExist) {
		return fmt.Errorf("ADR directory %q is missing", adrDirectoryPath)
	}
	if err != nil {
		return fmt.Errorf("open ADR directory %q: %w", adrDirectoryPath, err)
	}
	defer func() { _ = directory.Close() }()

	entries, err := directory.ReadDir(-1)
	if err != nil {
		return fmt.Errorf("read ADR directory %q: %w", adrDirectoryPath, err)
	}
	sort.Slice(entries, func(i, j int) bool { return entries[i].Name() < entries[j].Name() })
	for _, entry := range entries {
		if entry.IsDir() || filepath.Ext(entry.Name()) != ".md" {
			continue
		}
		relativePath := filepath.ToSlash(filepath.Join(adrDirectoryPath, entry.Name()))
		if err := rejectRootedSymlinks(root, relativePath, "ADR path"); err != nil {
			return err
		}
		content, err := root.ReadFile(filepath.FromSlash(relativePath))
		if err != nil {
			return fmt.Errorf("read ADR %q: %w", relativePath, err)
		}
		frontMatter, err := parseADR(relativePath, content)
		if err != nil {
			return err
		}
		if frontMatter.Status == string(capability.DivergenceAccepted) {
			expectedIDs, ok := referenced[relativePath]
			if !ok {
				return fmt.Errorf(
					"accepted ADR %q (%s) is unreferenced by an accepted manifest divergence",
					relativePath,
					frontMatter.ID,
				)
			}
			actualIDs := make(map[string]struct{}, len(frontMatter.DivergenceIDs))
			for _, divergenceID := range frontMatter.DivergenceIDs {
				if _, duplicate := actualIDs[divergenceID]; duplicate {
					return fmt.Errorf(
						"accepted ADR %q (%s) contains duplicate divergence id %q",
						relativePath,
						frontMatter.ID,
						divergenceID,
					)
				}
				actualIDs[divergenceID] = struct{}{}
			}
			if len(actualIDs) != len(expectedIDs) {
				return fmt.Errorf(
					"accepted ADR %q (%s) divergence_ids do not exactly match accepted manifest divergences",
					relativePath,
					frontMatter.ID,
				)
			}
			for divergenceID := range expectedIDs {
				if _, ok := actualIDs[divergenceID]; !ok {
					return fmt.Errorf(
						"accepted ADR %q (%s) divergence_ids do not exactly match accepted manifest divergences; missing %q",
						relativePath,
						frontMatter.ID,
						divergenceID,
					)
				}
			}
		}
	}
	return nil
}

func validateDivergenceADRInRoot(root *os.Root, divergence capability.Divergence) (adrFrontMatter, error) {
	if divergence.Status != capability.DivergenceAccepted {
		return adrFrontMatter{}, fmt.Errorf("divergence %q: status %q is not active", divergence.ID, divergence.Status)
	}
	if strings.TrimSpace(divergence.OwnerApprovalRef) == "" {
		return adrFrontMatter{}, fmt.Errorf("divergence %q: owner_approval_ref must not be blank", divergence.ID)
	}
	relativePath, err := validateADRRelativePath(divergence.ADR)
	if err != nil {
		return adrFrontMatter{}, fmt.Errorf("divergence %q: %w", divergence.ID, err)
	}
	if err := rejectRootedSymlinks(root, filepath.FromSlash(relativePath), "ADR path"); err != nil {
		return adrFrontMatter{}, fmt.Errorf("divergence %q: %w", divergence.ID, err)
	}
	content, err := root.ReadFile(filepath.FromSlash(relativePath))
	if errors.Is(err, os.ErrNotExist) {
		return adrFrontMatter{}, fmt.Errorf("divergence %q: missing ADR %q", divergence.ID, relativePath)
	}
	if err != nil {
		return adrFrontMatter{}, fmt.Errorf("divergence %q: read ADR %q: %w", divergence.ID, relativePath, err)
	}
	frontMatter, err := parseADR(relativePath, content)
	if err != nil {
		return adrFrontMatter{}, fmt.Errorf("divergence %q: %w", divergence.ID, err)
	}

	filenameID, err := adrIDFromPath(relativePath)
	if err != nil {
		return adrFrontMatter{}, fmt.Errorf("divergence %q: %w", divergence.ID, err)
	}
	if frontMatter.ID != filenameID {
		return adrFrontMatter{}, fmt.Errorf(
			"divergence %q: ADR id %q does not match filename id %q",
			divergence.ID,
			frontMatter.ID,
			filenameID,
		)
	}
	if frontMatter.Status != string(capability.DivergenceAccepted) {
		return adrFrontMatter{}, fmt.Errorf(
			"divergence %q: ADR %q status %q is not accepted",
			divergence.ID,
			relativePath,
			frontMatter.Status,
		)
	}
	if frontMatter.Owner != "wklken" {
		return adrFrontMatter{}, fmt.Errorf(
			"divergence %q: ADR %q owner %q must be wklken",
			divergence.ID,
			relativePath,
			frontMatter.Owner,
		)
	}
	if frontMatter.CompatibilityTarget != divergence.Compatibility {
		return adrFrontMatter{}, fmt.Errorf(
			"divergence %q: ADR compatibility_target %q does not match manifest value %q",
			divergence.ID,
			frontMatter.CompatibilityTarget,
			divergence.Compatibility,
		)
	}
	if frontMatter.OwnerApprovalRef != divergence.OwnerApprovalRef {
		return adrFrontMatter{}, fmt.Errorf(
			"divergence %q: ADR owner_approval_ref %q does not match manifest value %q",
			divergence.ID,
			frontMatter.OwnerApprovalRef,
			divergence.OwnerApprovalRef,
		)
	}
	count := 0
	for _, divergenceID := range frontMatter.DivergenceIDs {
		if divergenceID == divergence.ID {
			count++
		}
	}
	if count != 1 {
		return adrFrontMatter{}, fmt.Errorf(
			"divergence %q: ADR divergence_ids must contain the manifest divergence exactly once; found %d",
			divergence.ID,
			count,
		)
	}
	return frontMatter, nil
}

func validateADRRelativePath(relativePath string) (string, error) {
	if relativePath == "" || filepath.IsAbs(relativePath) || strings.Contains(relativePath, `\`) {
		return "", fmt.Errorf("ADR path %q must be a lexical repository-relative path", relativePath)
	}
	components := strings.Split(relativePath, "/")
	for _, component := range components {
		if component == "" || component == "." || component == ".." {
			return "", fmt.Errorf("ADR path %q must not contain empty, dot, or parent components", relativePath)
		}
	}
	if len(components) != 4 || strings.Join(components[:3], "/") != adrDirectoryPath {
		return "", fmt.Errorf("ADR path %q must be strictly inside %s/", relativePath, adrDirectoryPath)
	}
	if filepath.Ext(relativePath) != ".md" {
		return "", fmt.Errorf("ADR path %q must use the .md extension", relativePath)
	}
	if relativePath == adrTemplatePath {
		return "", fmt.Errorf("ADR path %q is the unreferenced proposal template", relativePath)
	}
	if _, err := adrIDFromPath(relativePath); err != nil {
		return "", err
	}
	return relativePath, nil
}

func adrIDFromPath(relativePath string) (string, error) {
	base := filepath.Base(filepath.FromSlash(relativePath))
	prefix, suffix, ok := strings.Cut(base, "-")
	if !ok || len(prefix) != 4 || suffix == "" || suffix == ".md" {
		return "", fmt.Errorf("ADR path %q must start with a four-digit ADR number and a name", relativePath)
	}
	if _, err := strconv.Atoi(prefix); err != nil {
		return "", fmt.Errorf("ADR path %q has non-numeric ADR prefix %q", relativePath, prefix)
	}
	return "ADR-" + prefix, nil
}

func parseADR(relativePath string, content []byte) (adrFrontMatter, error) {
	const opening = "---\n"
	const closing = "\n---\n"
	if !bytes.HasPrefix(content, []byte(opening)) {
		return adrFrontMatter{}, fmt.Errorf("ADR %q is missing YAML front matter", relativePath)
	}
	end := bytes.Index(content[len(opening):], []byte(closing))
	if end < 0 {
		return adrFrontMatter{}, fmt.Errorf("ADR %q has unterminated YAML front matter", relativePath)
	}
	frontMatterBytes := content[len(opening) : len(opening)+end]
	body := content[len(opening)+end+len(closing):]

	decoder := yaml.NewDecoder(bytes.NewReader(frontMatterBytes))
	decoder.KnownFields(true)
	var frontMatter adrFrontMatter
	if err := decoder.Decode(&frontMatter); err != nil {
		return adrFrontMatter{}, fmt.Errorf("decode ADR %q front matter: %w", relativePath, err)
	}
	var extra any
	if err := decoder.Decode(&extra); !errors.Is(err, io.EOF) {
		if err == nil {
			return adrFrontMatter{}, fmt.Errorf(
				"decode ADR %q front matter: multiple YAML documents are not supported",
				relativePath,
			)
		}
		return adrFrontMatter{}, fmt.Errorf("decode ADR %q front matter: %w", relativePath, err)
	}

	var fields map[string]any
	if err := yaml.Unmarshal(frontMatterBytes, &fields); err != nil {
		return adrFrontMatter{}, fmt.Errorf("decode ADR %q fields: %w", relativePath, err)
	}
	requiredFields := []string{
		"id", "title", "status", "compatibility_target", "divergence_ids", "owner", "owner_approval_ref", "date",
	}
	for _, field := range requiredFields {
		if _, ok := fields[field]; !ok {
			return adrFrontMatter{}, fmt.Errorf("ADR %q front matter is missing field %q", relativePath, field)
		}
	}
	if strings.TrimSpace(frontMatter.ID) == "" ||
		strings.TrimSpace(frontMatter.Title) == "" ||
		strings.TrimSpace(frontMatter.Status) == "" ||
		strings.TrimSpace(frontMatter.CompatibilityTarget) == "" ||
		strings.TrimSpace(frontMatter.Owner) == "" ||
		strings.TrimSpace(frontMatter.Date) == "" {
		return adrFrontMatter{}, fmt.Errorf("ADR %q front matter contains a blank required field", relativePath)
	}
	if frontMatter.Status != string(capability.DivergenceProposed) &&
		frontMatter.Status != string(capability.DivergenceAccepted) &&
		frontMatter.Status != string(capability.DivergenceRetired) {
		return adrFrontMatter{}, fmt.Errorf("ADR %q has unknown status %q", relativePath, frontMatter.Status)
	}
	requiredHeadings := []string{"# Context", "# Decision", "# Consequences", "# Evidence required to retire"}
	previous := -1
	for _, heading := range requiredHeadings {
		needle := []byte("\n" + heading + "\n")
		index := bytes.Index(append([]byte{'\n'}, body...), needle)
		if index < 0 || index <= previous {
			return adrFrontMatter{}, fmt.Errorf("ADR %q must contain ordered heading %q", relativePath, heading)
		}
		previous = index
	}
	return frontMatter, nil
}

func renderPluginsMarkdown(manifest *capability.Manifest) ([]byte, error) {
	if manifest == nil {
		return nil, errors.New("render plugins Markdown: manifest must not be nil")
	}
	profile, ok := manifest.Qualification(qualificationProfileName)
	if !ok {
		return nil, fmt.Errorf("render plugins Markdown: qualification profile %q is missing", qualificationProfileName)
	}
	counts := deriveCapabilityCounts(manifest)
	plugins := sortedCapabilities(manifest)

	var document bytes.Buffer
	document.WriteString(generatedDocumentPreamble)
	document.WriteString("\n# Plugin Capability Status\n\n")
	document.WriteString(
		"> This document is generated from the capability manifest. " +
			"Its rows are manifest projections, not proof; evidence states and references " +
			"identify the recorded qualification basis.\n\n",
	)
	document.WriteString("## Compatibility target\n\n")
	fmt.Fprintf(&document, "- Name: `%s`\n", markdownCell(manifest.Target.Name))
	fmt.Fprintf(&document, "- Version: `%s`\n", markdownCell(manifest.Target.Version))
	fmt.Fprintf(&document, "- Source commit: `%s`\n", markdownCell(manifest.Target.SourceCommit))
	fmt.Fprintf(&document, "- Image: `%s`\n", markdownCell(manifest.Target.Image))
	document.WriteString("\n## Manifest summary\n\n")
	fmt.Fprintf(&document, "- Capability rows: **%d**\n", counts.total)
	fmt.Fprintf(
		&document,
		"- APISIX defaults: **%d**; Go-applicable: **%d**; full: **%d**; "+
			"partial: **%d**; deferred: **%d**; not applicable: **%d**\n",
		counts.defaults,
		counts.applicableDefaults,
		counts.fullDefaults,
		counts.partialDefaults,
		counts.deferredDefaults,
		counts.notApplicableDefaults,
	)
	fmt.Fprintf(&document, "- Qualification `%s`: **%d/%d** required plugins qualified; required evidence: %s\n",
		markdownCell(profile.Name),
		counts.qualified,
		counts.required,
		markdownCell(evidenceKindList(profile.RequiredEvidence)),
	)
	document.WriteString("\n## Status semantics\n\n")
	document.WriteString(
		"Behavior status describes the implemented compatibility contract independently from evidence:\n\n",
	)
	document.WriteString("- **full**: the manifest records no known behavioral gap for the declared contract.\n")
	document.WriteString("- **partial**: the declared behavior has one or more explicit known gaps.\n")
	document.WriteString("- **deferred**: implementation is intentionally postponed.\n")
	document.WriteString("- **not_applicable**: the APISIX facility has no Go-plugin contract in this data plane.\n\n")
	document.WriteString(
		"Evidence states are independent for Schema, Unit, Converted upstream, Differential, Real dependency, Failure, and Recovery:\n\n",
	)
	document.WriteString("- **verified**: current auditable evidence is recorded.\n")
	document.WriteString("- **missing**: required evidence is not recorded.\n")
	document.WriteString("- **stale**: evidence exists but does not match the current compatibility target.\n")
	document.WriteString("- **flaky**: evidence exists but is not repeatably reliable.\n")
	document.WriteString("- **deferred**: evidence collection is intentionally postponed with an owner and reason.\n")
	document.WriteString("- **not_applicable**: the evidence dimension does not apply, with a concrete reason.\n")
	document.WriteString("\n## Capability rows\n\n")
	document.WriteString(
		"APISIX defaults are sorted first by name. Remaining Go extension entries follow by namespace and name.\n\n",
	)
	document.WriteString(
		"| Plugin | Namespace | APISIX default | Domains | Behavior status | Behavior summary | Known gaps | Platforms | Schema | Unit | Converted upstream | Differential | Real dependency | Failure | Recovery |\n",
	)
	document.WriteString(
		"| --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- |\n",
	)
	for _, plugin := range plugins {
		fmt.Fprintf(
			&document,
			"| `%s` | `%s` | %s | %s | **%s** | %s | %s | %s | %s | %s | %s | %s | %s | %s | %s |\n",
			markdownCell(plugin.Name),
			markdownCell(string(plugin.Namespace)),
			yesNo(plugin.APISIXDefault),
			markdownCell(domainList(plugin.Domains)),
			markdownCell(string(plugin.Behavior)),
			markdownCell(plugin.BehaviorSummary),
			renderKnownGaps(plugin.KnownGaps),
			markdownCell(strings.Join(plugin.SupportedPlatforms, ", ")),
			renderEvidenceClaim(plugin.Evidence.Schema),
			renderEvidenceClaim(plugin.Evidence.Unit),
			renderEvidenceClaim(plugin.Evidence.Upstream),
			renderEvidenceClaim(plugin.Evidence.Differential),
			renderEvidenceClaim(plugin.Evidence.RealDependency),
			renderEvidenceClaim(plugin.Evidence.Failure),
			renderEvidenceClaim(plugin.Evidence.Recovery),
		)
	}
	return document.Bytes(), nil
}

func renderReadmeSummary(manifest *capability.Manifest, locale readmeLocale) ([]byte, error) {
	if manifest == nil {
		return nil, errors.New("render README summary: manifest must not be nil")
	}
	if locale != readmeEnglish && locale != readmeChinese {
		return nil, fmt.Errorf("render README summary: unsupported locale %q", locale)
	}
	profile, ok := manifest.Qualification(qualificationProfileName)
	if !ok {
		return nil, fmt.Errorf("render README summary: qualification profile %q is missing", qualificationProfileName)
	}
	counts := deriveCapabilityCounts(manifest)
	plugins := sortedCapabilities(manifest)

	var summary bytes.Buffer
	if locale == readmeEnglish {
		fmt.Fprintf(&summary, "Target `%s` is Apache APISIX `%s` at `%s` (image `%s`).\n\n",
			manifest.Target.Name, manifest.Target.Version, manifest.Target.SourceCommit, manifest.Target.Image)
		fmt.Fprintf(
			&summary,
			"The manifest contains **%d** capability rows and **%d** APISIX defaults. Of the **%d** Go-applicable defaults, **%d** are full, **%d** are partial, and **%d** are deferred; **%d** defaults are not applicable to the Go plugin contract.\n\n",
			counts.total,
			counts.defaults,
			counts.applicableDefaults,
			counts.fullDefaults,
			counts.partialDefaults,
			counts.deferredDefaults,
			counts.notApplicableDefaults,
		)
		fmt.Fprintf(
			&summary,
			"Qualification profile `%s` currently qualifies **%d/%d** required plugins. Status is derived from behavior plus the required evidence dimensions, not registration counts.\n\n",
			profile.Name,
			counts.qualified,
			counts.required,
		)
		summary.WriteString("Explicit manifest gaps:\n")
	} else {
		fmt.Fprintf(&summary, "兼容目标 `%s` 为 Apache APISIX `%s`、源码提交 `%s`（镜像 `%s`）。\n\n",
			manifest.Target.Name, manifest.Target.Version, manifest.Target.SourceCommit, manifest.Target.Image)
		fmt.Fprintf(
			&summary,
			"能力清单包含 **%d** 条记录和 **%d** 个 APISIX 默认插件。"+
				"在 **%d** 个适用于 Go 的默认插件中，**%d** 个为完整实现，"+
				"**%d** 个为部分实现，**%d** 个为延期实现；"+
				"另有 **%d** 个默认插件不适用于 Go 插件契约。\n\n",
			counts.total,
			counts.defaults,
			counts.applicableDefaults,
			counts.fullDefaults,
			counts.partialDefaults,
			counts.deferredDefaults,
			counts.notApplicableDefaults,
		)
		fmt.Fprintf(&summary, "资格配置 `%s` 当前有 **%d/%d** 个必需插件通过。状态由行为和必需证据维度共同推导，而不是由注册数量推导。\n\n",
			profile.Name, counts.qualified, counts.required)
		summary.WriteString("清单中的明确差距：\n")
	}
	for _, plugin := range plugins {
		for _, gap := range plugin.KnownGaps {
			fmt.Fprintf(&summary, "- `%s` (`%s`): %s\n", plugin.Name, plugin.Namespace, gap)
		}
	}
	return bytes.TrimSuffix(summary.Bytes(), []byte("\n")), nil
}

func replaceGeneratedReadmeBlock(source, summary []byte) ([]byte, error) {
	if bytes.Count(source, []byte(generatedSummaryBegin)) != 1 ||
		bytes.Count(source, []byte(generatedSummaryEnd)) != 1 {
		return nil, errors.New("generated capability summary markers must each appear exactly once")
	}
	begin := bytes.Index(source, []byte(generatedSummaryBegin))
	end := bytes.Index(source, []byte(generatedSummaryEnd))
	if begin > end {
		return nil, errors.New("generated capability summary markers are out of order")
	}
	begin += len(generatedSummaryBegin)

	var replaced bytes.Buffer
	replaced.Write(source[:begin])
	replaced.WriteByte('\n')
	replaced.WriteString(generatedSummaryNotice)
	replaced.WriteByte('\n')
	replaced.Write(bytes.Trim(summary, "\n"))
	replaced.WriteByte('\n')
	replaced.Write(source[end:])
	return replaced.Bytes(), nil
}

func deriveCapabilityCounts(manifest *capability.Manifest) capabilityCounts {
	counts := capabilityCounts{total: len(manifest.Plugins)}
	for _, plugin := range manifest.Plugins {
		if !plugin.APISIXDefault {
			continue
		}
		counts.defaults++
		switch plugin.Behavior {
		case capability.BehaviorFull:
			counts.applicableDefaults++
			counts.fullDefaults++
		case capability.BehaviorPartial:
			counts.applicableDefaults++
			counts.partialDefaults++
		case capability.BehaviorDeferred:
			counts.applicableDefaults++
			counts.deferredDefaults++
		case capability.BehaviorNotApplicable:
			counts.notApplicableDefaults++
		}
	}
	profile, ok := manifest.Qualification(qualificationProfileName)
	if ok {
		counts.required = len(profile.RequiredPlugins)
		counts.qualified = len(manifest.QualifiedPlugins(profile.Name))
	}
	return counts
}

func sortedCapabilities(manifest *capability.Manifest) []capability.PluginCapability {
	plugins := append([]capability.PluginCapability(nil), manifest.Plugins...)
	sort.Slice(plugins, func(i, j int) bool {
		if plugins[i].APISIXDefault != plugins[j].APISIXDefault {
			return plugins[i].APISIXDefault
		}
		if plugins[i].APISIXDefault {
			return plugins[i].Name < plugins[j].Name
		}
		if plugins[i].Namespace != plugins[j].Namespace {
			return plugins[i].Namespace < plugins[j].Namespace
		}
		return plugins[i].Name < plugins[j].Name
	})
	return plugins
}

func markdownCell(value string) string {
	value = strings.ReplaceAll(value, "\r\n", "\n")
	value = strings.ReplaceAll(value, "|", `\|`)
	return strings.ReplaceAll(value, "\n", "<br>")
}

func renderKnownGaps(gaps []string) string {
	if len(gaps) == 0 {
		return "none"
	}
	rendered := make([]string, len(gaps))
	for index, gap := range gaps {
		rendered[index] = markdownCell(gap)
	}
	return strings.Join(rendered, "<br>")
}

func renderEvidenceClaim(claim capability.EvidenceClaim) string {
	refs := "none"
	if len(claim.Refs) != 0 {
		refs = strings.Join(claim.Refs, ", ")
	}
	reason := "none"
	if claim.Reason != "" {
		reason = claim.Reason
	}
	return fmt.Sprintf(
		"**%s**<br>owner: %s<br>reason: %s<br>refs: %s",
		markdownCell(string(claim.State)),
		markdownCell(claim.Owner),
		markdownCell(reason),
		markdownCell(refs),
	)
}

func evidenceKindList(kinds []capability.EvidenceKind) string {
	values := make([]string, len(kinds))
	for index, kind := range kinds {
		values[index] = string(kind)
	}
	return strings.Join(values, ", ")
}

func domainList(domains []capability.Domain) string {
	values := make([]string, len(domains))
	for index, domain := range domains {
		values[index] = string(domain)
	}
	return strings.Join(values, ", ")
}

func yesNo(value bool) string {
	if value {
		return "yes"
	}
	return "no"
}

func renderRegistry(manifest *capability.Manifest) ([]byte, error) {
	if manifest == nil {
		return nil, errors.New("render registry: manifest must not be nil")
	}

	type registryImport struct {
		path  string
		alias string
	}
	type registryFactory struct {
		key         string
		alias       string
		constructor string
	}

	importsByPath := make(map[string]string)
	pathsByAlias := make(map[string]string)
	factories := make([]registryFactory, 0)
	seenFactories := make(map[string]struct{})
	seenEntries := make(map[string]struct{})
	for _, plugin := range manifest.Plugins {
		if len(plugin.Factories) == 0 {
			continue
		}
		if _, exists := seenEntries[plugin.Name]; exists {
			return nil, fmt.Errorf("render registry: duplicate capability identity %q", plugin.Name)
		}
		seenEntries[plugin.Name] = struct{}{}
		if err := validateGeneratedFacts(plugin); err != nil {
			return nil, err
		}
		for _, factory := range plugin.Factories {
			if _, exists := seenFactories[factory.Key]; exists {
				return nil, fmt.Errorf("render registry: duplicate factory %q", factory.Key)
			}
			seenFactories[factory.Key] = struct{}{}
			if !token.IsIdentifier(factory.ImportAlias) {
				return nil, fmt.Errorf(
					"render registry: factory %q has invalid import alias %q",
					factory.Key,
					factory.ImportAlias,
				)
			}
			if !token.IsIdentifier(factory.Constructor) {
				return nil, fmt.Errorf(
					"render registry: factory %q has invalid constructor %q",
					factory.Key,
					factory.Constructor,
				)
			}
			if alias, exists := importsByPath[factory.ImportPath]; exists && alias != factory.ImportAlias {
				return nil, fmt.Errorf(
					"render registry: import %q uses aliases %q and %q",
					factory.ImportPath,
					alias,
					factory.ImportAlias,
				)
			}
			if path, exists := pathsByAlias[factory.ImportAlias]; exists && path != factory.ImportPath {
				return nil, fmt.Errorf(
					"render registry: import alias %q is shared by %q and %q",
					factory.ImportAlias,
					path,
					factory.ImportPath,
				)
			}
			importsByPath[factory.ImportPath] = factory.ImportAlias
			pathsByAlias[factory.ImportAlias] = factory.ImportPath
			factories = append(factories, registryFactory{
				key:         factory.Key,
				alias:       factory.ImportAlias,
				constructor: factory.Constructor,
			})
		}
	}

	imports := make([]registryImport, 0, len(importsByPath))
	for path, alias := range importsByPath {
		imports = append(imports, registryImport{path: path, alias: alias})
	}
	sort.Slice(imports, func(i, j int) bool {
		if imports[i].path == imports[j].path {
			return imports[i].alias < imports[j].alias
		}
		return imports[i].path < imports[j].path
	})
	sort.Slice(factories, func(i, j int) bool { return factories[i].key < factories[j].key })

	var source bytes.Buffer
	source.WriteString("// Code generated by go run ./cmd/capability-gen -write; DO NOT EDIT.\n\n")
	source.WriteString("package plugin\n\n")
	source.WriteString("// Imports are rendered from manifest Factory facts.\n")
	source.WriteString("import (\n")
	for _, imported := range imports {
		fmt.Fprintf(&source, "\t%s %s\n", imported.alias, strconv.Quote(imported.path))
	}
	source.WriteString(")\n\n")
	source.WriteString("var pluginRegistry = map[string]func() Plugin{\n")
	for _, factory := range factories {
		fmt.Fprintf(
			&source,
			"\t%s: func() Plugin { return %s },\n",
			strconv.Quote(factory.key),
			constructorExpression(factory.alias, factory.constructor),
		)
	}
	source.WriteString("}\n")

	formatted, err := format.Source(source.Bytes())
	if err != nil {
		return nil, fmt.Errorf("format generated registry: %w", err)
	}
	return formatted, nil
}

func validateGeneratedFacts(plugin capability.PluginCapability) error {
	for _, phase := range plugin.Phases {
		switch phase {
		case "rewrite", "consumer_rewrite", "access", "before_proxy", "header_filter",
			"body_filter", "log", "finalizer", "protocol":
		default:
			return fmt.Errorf("render registry: capability %q has unsupported phase %q", plugin.Name, phase)
		}
	}
	for _, scope := range plugin.Scopes {
		switch scope {
		case "system", "global_rule", "route", "service":
		default:
			return fmt.Errorf("render registry: capability %q has unsupported scope %q", plugin.Name, scope)
		}
	}
	return nil
}

func constructorExpression(alias, constructor string) string {
	if constructor == "Plugin" {
		return "&" + alias + "." + constructor + "{}"
	}
	return alias + "." + constructor + "()"
}

func writeOutputs(repoRoot string, outputs []generatedOutput) error {
	root, err := openOutputRoot(repoRoot)
	if err != nil {
		return err
	}
	defer func() { _ = root.Close() }()

	for _, output := range outputs {
		relativePath, err := containedOutputRelativePath(output.relativePath)
		if err != nil {
			return err
		}
		if err := rejectOutputSymlinks(root, relativePath); err != nil {
			return err
		}
		parent := filepath.Dir(relativePath)
		if parent != "." {
			if err := root.MkdirAll(parent, 0o755); err != nil {
				return fmt.Errorf("create output directory for %s: %w", output.relativePath, err)
			}
		}
		if err := rejectOutputSymlinks(root, relativePath); err != nil {
			return err
		}
		if err := root.WriteFile(relativePath, output.content, 0o644); err != nil {
			return fmt.Errorf("write %s: %w", output.relativePath, err)
		}
	}
	return nil
}

func checkOutputs(repoRoot string, outputs []generatedOutput) error {
	root, err := openOutputRoot(repoRoot)
	if err != nil {
		return err
	}
	defer func() { _ = root.Close() }()

	for _, output := range outputs {
		relativePath, err := containedOutputRelativePath(output.relativePath)
		if err != nil {
			return err
		}
		if err := rejectOutputSymlinks(root, relativePath); err != nil {
			return err
		}
		current, err := root.ReadFile(relativePath)
		if errors.Is(err, os.ErrNotExist) {
			return fmt.Errorf("%s: generated output is missing", output.relativePath)
		}
		if err != nil {
			return fmt.Errorf("read %s: %w", output.relativePath, err)
		}
		if !bytes.Equal(current, output.content) {
			return fmt.Errorf("%s: generated output is stale", output.relativePath)
		}
	}
	return nil
}

func readRootedFile(root *os.Root, relativePath string) ([]byte, error) {
	relativePath, err := containedOutputRelativePath(relativePath)
	if err != nil {
		return nil, err
	}
	if err := rejectOutputSymlinks(root, relativePath); err != nil {
		return nil, err
	}
	content, err := root.ReadFile(relativePath)
	if err != nil {
		return nil, fmt.Errorf("read %s: %w", relativePath, err)
	}
	return content, nil
}

func openOutputRoot(repoRoot string) (*os.Root, error) {
	rootPath, err := canonicalRepoRoot(repoRoot)
	if err != nil {
		return nil, err
	}
	root, err := os.OpenRoot(rootPath)
	if err != nil {
		return nil, fmt.Errorf("open repository root %q: %w", repoRoot, err)
	}
	return root, nil
}

func canonicalRepoRoot(repoRoot string) (string, error) {
	rootPath, err := filepath.Abs(filepath.Clean(repoRoot))
	if err != nil {
		return "", fmt.Errorf("clean repository root: %w", err)
	}
	rootPath, err = filepath.EvalSymlinks(rootPath)
	if err != nil {
		return "", fmt.Errorf("resolve repository root: %w", err)
	}
	return rootPath, nil
}

func containedOutputRelativePath(relativePath string) (string, error) {
	if filepath.IsAbs(relativePath) {
		return "", fmt.Errorf("output path %q escapes repository root", relativePath)
	}
	relative := filepath.Clean(filepath.FromSlash(relativePath))
	if relative == ".." || strings.HasPrefix(relative, ".."+string(filepath.Separator)) {
		return "", fmt.Errorf("output path %q escapes repository root", relativePath)
	}
	return relative, nil
}

func rejectOutputSymlinks(root *os.Root, relativePath string) error {
	return rejectRootedSymlinks(root, relativePath, "output path")
}

func rejectRootedSymlinks(root *os.Root, relativePath, pathKind string) error {
	currentPath := ""
	for component := range strings.SplitSeq(filepath.ToSlash(relativePath), "/") {
		if component == "" || component == "." {
			continue
		}
		currentPath = filepath.Join(currentPath, component)
		info, err := root.Lstat(currentPath)
		if errors.Is(err, os.ErrNotExist) {
			return nil
		}
		if err != nil {
			return fmt.Errorf("inspect %s %q: %w", pathKind, relativePath, err)
		}
		if info.Mode()&os.ModeSymlink != 0 {
			return fmt.Errorf("%s %q contains symbolic link %q", pathKind, relativePath, currentPath)
		}
	}
	return nil
}
