package main

import (
	"bytes"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"testing"

	"github.com/wklken/apisix-go/pkg/capability"
)

func TestRenderRegistryIsDeterministic(t *testing.T) {
	manifest, err := capability.Load()
	if err != nil {
		t.Fatal(err)
	}
	first, err := renderRegistry(manifest)
	if err != nil {
		t.Fatal(err)
	}
	second, err := renderRegistry(manifest)
	if err != nil {
		t.Fatal(err)
	}
	if !bytes.Equal(first, second) {
		t.Fatal("registry generation is nondeterministic")
	}
	normalized := bytes.Join(bytes.Fields(first), []byte(" "))
	if !bytes.Contains(normalized, []byte(`"request-id": func() Plugin { return &request_id.Plugin{} }`)) {
		t.Fatal("request-id constructor missing")
	}
}

func TestRenderRegistrySortsImportsAndFactories(t *testing.T) {
	manifest, err := capability.Load()
	if err != nil {
		t.Fatal(err)
	}
	generated, err := renderRegistry(manifest)
	if err != nil {
		t.Fatal(err)
	}

	aclImport := bytes.Index(generated, []byte(`"github.com/wklken/apisix-go/pkg/plugin/acl"`))
	aiImport := bytes.Index(generated, []byte(`"github.com/wklken/apisix-go/pkg/plugin/ai"`))
	if aclImport < 0 || aiImport < 0 || aclImport >= aiImport {
		t.Fatalf("imports are not sorted: acl=%d ai=%d", aclImport, aiImport)
	}
	aclFactory := bytes.Index(generated, []byte(`"acl":`))
	aiFactory := bytes.Index(generated, []byte(`"ai":`))
	if aclFactory < 0 || aiFactory < 0 || aclFactory >= aiFactory {
		t.Fatalf("factories are not sorted: acl=%d ai=%d", aclFactory, aiFactory)
	}
}

func TestValidateGeneratedFactsAcceptsExplicitConsumerScopes(t *testing.T) {
	plugin := capability.PluginCapability{
		Name:   "consumer-scoped",
		Scopes: []string{"consumer", "consumer_group"},
	}
	if err := validateGeneratedFacts(plugin); err != nil {
		t.Fatal(err)
	}
}

func TestRenderPluginsMarkdownSeparatesBehaviorAndEvidence(t *testing.T) {
	manifest := loadManifest(t)
	generated, err := renderPluginsMarkdown(manifest)
	if err != nil {
		t.Fatal(err)
	}

	for _, text := range []string{
		"Code generated by go run ./cmd/capability-gen -write; DO NOT EDIT.",
		"Behavior status",
		"Capabilities requiring attention",
		"Project divergences",
		"Capability index",
		"Schema",
		"Unit",
		"Converted upstream",
		"Differential",
		"Real dependency",
		"Failure",
	} {
		if !bytes.Contains(generated, []byte(text)) {
			t.Fatalf("generated plugins.md missing %q", text)
		}
	}
	if bytes.Contains(generated, []byte("owner:")) ||
		bytes.Contains(generated, []byte("refs:")) ||
		bytes.Contains(generated, []byte("| Behavior summary |")) {
		t.Fatal("generated plugins.md exposes audit-ledger detail in the human status view")
	}
	if len(generated) > 50_000 {
		t.Fatalf("generated plugins.md is %d bytes, want a concise document <= 50000 bytes", len(generated))
	}
	for lineNumber, line := range bytes.Split(generated, []byte("\n")) {
		if len(line) > 500 {
			t.Fatalf("generated plugins.md line %d is %d bytes, want <= 500", lineNumber+1, len(line))
		}
	}
	if bytes.Contains(generated, []byte("| Recovery |")) {
		t.Fatal("generated plugins.md must not project platform recovery onto plugin rows")
	}
	for _, field := range []string{
		manifest.Target.Name,
		manifest.Target.Version,
		manifest.Target.SourceCommit,
		manifest.Target.Image,
		"manifest remains authoritative",
	} {
		if !bytes.Contains(generated, []byte(field)) {
			t.Fatalf("generated plugins.md missing target/projection field %q", field)
		}
	}
}

func TestRenderPluginsMarkdownSortsDefaultsBeforeExtensions(t *testing.T) {
	manifest := loadManifest(t)
	generated, err := renderPluginsMarkdown(manifest)
	if err != nil {
		t.Fatal(err)
	}

	defaults := make([]capability.PluginCapability, 0)
	extensions := make([]capability.PluginCapability, 0)
	for _, plugin := range manifest.Plugins {
		if plugin.APISIXDefault {
			defaults = append(defaults, plugin)
		} else {
			extensions = append(extensions, plugin)
		}
	}
	sort.Slice(defaults, func(i, j int) bool { return defaults[i].Name < defaults[j].Name })
	sort.Slice(extensions, func(i, j int) bool {
		if extensions[i].Namespace != extensions[j].Namespace {
			return extensions[i].Namespace < extensions[j].Namespace
		}
		return extensions[i].Name < extensions[j].Name
	})
	positions := make([]int, 0, len(manifest.Plugins))
	for _, plugin := range defaults {
		row := []byte("| `" + plugin.Name + "` | `" + string(plugin.Namespace) + "` |")
		positions = append(positions, bytes.Index(generated, row))
	}
	for _, plugin := range extensions {
		row := []byte("| `" + plugin.Name + "` | `" + string(plugin.Namespace) + "` |")
		positions = append(positions, bytes.Index(generated, row))
	}
	for index, position := range positions {
		if position < 0 {
			t.Fatalf("sorted plugin row %d is missing", index)
		}
		if index > 0 && positions[index-1] >= position {
			t.Fatalf(
				"plugin rows are not in deterministic default/extension order at %d: %d >= %d",
				index,
				positions[index-1],
				position,
			)
		}
	}
}

func TestRenderPluginsMarkdownPreservesDivergenceLinks(t *testing.T) {
	manifest := loadManifest(t)
	generated, err := renderPluginsMarkdown(manifest)
	if err != nil {
		t.Fatal(err)
	}

	for _, divergence := range manifest.Divergences {
		if !bytes.Contains(generated, []byte("`"+divergence.ID+"`")) {
			t.Fatalf("generated plugins.md lost divergence %q", divergence.ID)
		}
		link := strings.TrimPrefix(divergence.ADR, "docs/")
		if !bytes.Contains(generated, []byte("("+link+")")) {
			t.Fatalf("generated plugins.md lost ADR link %q", link)
		}
	}
}

func TestRenderPluginsMarkdownPreservesGapsAndEvidenceLegends(t *testing.T) {
	manifest := loadManifest(t)
	generated, err := renderPluginsMarkdown(manifest)
	if err != nil {
		t.Fatal(err)
	}

	for _, state := range []string{"stale", "flaky", "deferred"} {
		if !bytes.Contains(generated, []byte("**"+state+"**")) {
			t.Fatalf("generated plugins.md does not define %q evidence", state)
		}
	}
	for _, plugin := range manifest.Plugins {
		for _, gap := range plugin.KnownGaps {
			if !bytes.Contains(generated, []byte(markdownCell(gap))) {
				t.Fatalf("generated plugins.md lost gap for %s: %q", plugin.Name, gap)
			}
		}
	}
	if bytes.Contains(generated, []byte("100%")) {
		t.Fatal("generated plugins.md makes a false 100% claim")
	}
}

func TestRenderReadmeSummaryLocalesShareManifestFacts(t *testing.T) {
	manifest := loadManifest(t)
	english, err := renderReadmeSummary(manifest, readmeEnglish)
	if err != nil {
		t.Fatal(err)
	}
	chinese, err := renderReadmeSummary(manifest, readmeChinese)
	if err != nil {
		t.Fatal(err)
	}

	counts := deriveCapabilityCounts(manifest)
	facts := []string{
		manifest.Target.Name,
		manifest.Target.Version,
		manifest.Target.SourceCommit,
		fmt.Sprintf("%d", counts.total),
		fmt.Sprintf("%d", counts.defaults),
		fmt.Sprintf("%d", counts.applicableDefaults),
		fmt.Sprintf("%d", counts.fullDefaults),
		fmt.Sprintf("%d", counts.partialDefaults),
		fmt.Sprintf("%d", counts.notApplicableDefaults),
	}
	for _, fact := range facts {
		if !bytes.Contains(english, []byte(fact)) || !bytes.Contains(chinese, []byte(fact)) {
			t.Fatalf("localized summaries do not share derived fact %q", fact)
		}
	}
	for _, plugin := range manifest.Plugins {
		for _, gap := range plugin.KnownGaps {
			if !bytes.Contains(english, []byte(gap)) || !bytes.Contains(chinese, []byte(gap)) {
				t.Fatalf("localized summaries do not share gap for %s: %q", plugin.Name, gap)
			}
		}
	}
	if bytes.Contains(english, []byte("100%")) || bytes.Contains(chinese, []byte("100%")) {
		t.Fatal("localized summaries make a false 100% claim")
	}
}

func TestReplaceGeneratedReadmeBlockIsBounded(t *testing.T) {
	source := []byte("before\n" + generatedSummaryBegin + "\nold\n" + generatedSummaryEnd + "\nafter\n")
	summary := []byte("generated\nsummary")
	got, err := replaceGeneratedReadmeBlock(source, summary)
	if err != nil {
		t.Fatal(err)
	}
	want := []byte(
		"before\n" + generatedSummaryBegin + "\n" + generatedSummaryNotice + "\ngenerated\nsummary\n" + generatedSummaryEnd + "\nafter\n",
	)
	if !bytes.Equal(got, want) {
		t.Fatalf("replaceGeneratedReadmeBlock() = %q, want %q", got, want)
	}
}

func TestReplaceGeneratedReadmeBlockRejectsMissingOrDuplicateMarkers(t *testing.T) {
	tests := map[string][]byte{
		"missing": []byte("no generated block\n"),
		"duplicate begin": []byte(
			generatedSummaryBegin + "\n" + generatedSummaryBegin + "\n" + generatedSummaryEnd + "\n",
		),
		"duplicate end": []byte(
			generatedSummaryBegin + "\n" + generatedSummaryEnd + "\n" + generatedSummaryEnd + "\n",
		),
	}
	for name, source := range tests {
		t.Run(name, func(t *testing.T) {
			if _, err := replaceGeneratedReadmeBlock(source, []byte("summary")); err == nil {
				t.Fatal("replaceGeneratedReadmeBlock() error = nil, want marker rejection")
			}
		})
	}
}

func TestBuildOutputsRejectsReadmeSymlink(t *testing.T) {
	root := t.TempDir()
	manifest := loadManifest(t)
	writeManifestADRs(t, root, manifest)
	outside := t.TempDir()
	sentinel := filepath.Join(outside, "README.md")
	if err := os.WriteFile(sentinel, []byte("external sentinel"), 0o644); err != nil {
		t.Fatal(err)
	}
	if err := os.Symlink(sentinel, filepath.Join(root, "README.md")); err != nil {
		t.Skipf("creating symlink is unavailable: %v", err)
	}
	if _, err := buildOutputs(root, manifest); err == nil || !strings.Contains(err.Error(), "symbolic link") {
		t.Fatalf("buildOutputs() error = %v, want README symbolic-link rejection", err)
	}
	got, err := os.ReadFile(sentinel)
	if err != nil {
		t.Fatal(err)
	}
	if string(got) != "external sentinel" {
		t.Fatalf("external README changed: %q", got)
	}
}

func TestGeneratedDocumentationDriftIsChecked(t *testing.T) {
	root := t.TempDir()
	manifest := loadManifest(t)
	writeManifestADRs(t, root, manifest)
	for _, name := range []string{readmeOutputPath, readmeChineseOutputPath} {
		content := []byte("before\n" + generatedSummaryBegin + "\nold\n" + generatedSummaryEnd + "\nafter\n")
		if err := os.WriteFile(filepath.Join(root, name), content, 0o644); err != nil {
			t.Fatal(err)
		}
	}
	outputs, err := buildOutputs(root, manifest)
	if err != nil {
		t.Fatal(err)
	}
	if err := writeOutputs(root, outputs); err != nil {
		t.Fatal(err)
	}
	for _, name := range []string{pluginsOutputPath, readmeOutputPath, readmeChineseOutputPath} {
		t.Run(name, func(t *testing.T) {
			path := filepath.Join(root, filepath.FromSlash(name))
			current, err := os.ReadFile(path)
			if err != nil {
				t.Fatal(err)
			}
			current[0] ^= 1
			if err := os.WriteFile(path, current, 0o644); err != nil {
				t.Fatal(err)
			}
			if err := checkOutputs(root, outputs); err == nil ||
				!strings.Contains(err.Error(), "generated output is stale") {
				t.Fatalf("checkOutputs() error = %v, want generated documentation drift", err)
			}
			if err := writeOutputs(root, outputs); err != nil {
				t.Fatal(err)
			}
		})
	}
}

func TestValidateEvidenceRefsRejectsMissingFilesAndTestSymbols(t *testing.T) {
	root := t.TempDir()
	testFile := filepath.Join(root, "pkg", "plugin", "example", "plugin_test.go")
	if err := os.MkdirAll(filepath.Dir(testFile), 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(testFile, []byte(`package example

import "testing"

func TestExistingEvidence(t *testing.T) {}
`), 0o644); err != nil {
		t.Fatal(err)
	}

	manifestWithRef := func(ref string) *capability.Manifest {
		return &capability.Manifest{Plugins: []capability.PluginCapability{{
			Name: "example",
			Evidence: capability.Evidence{Unit: capability.EvidenceClaim{
				State: capability.EvidenceVerified,
				Refs:  []string{ref},
			}},
		}}}
	}

	for _, test := range []struct {
		name string
		ref  string
		want string
	}{
		{name: "missing file", ref: "pkg/plugin/example/missing_test.go", want: "does not exist"},
		{
			name: "missing test symbol",
			ref:  "pkg/plugin/example/plugin_test.go#TestMissingEvidence",
			want: "does not define test function",
		},
		{name: "path escape", ref: "../outside_test.go", want: "escapes repository root"},
	} {
		t.Run(test.name, func(t *testing.T) {
			err := validateEvidenceRefs(root, manifestWithRef(test.ref))
			if err == nil || !strings.Contains(err.Error(), test.want) {
				t.Fatalf("validateEvidenceRefs() error = %v, want %q", err, test.want)
			}
		})
	}

	if err := validateEvidenceRefs(
		root,
		manifestWithRef("pkg/plugin/example/plugin_test.go#TestExistingEvidence"),
	); err != nil {
		t.Fatalf("validateEvidenceRefs() error = %v", err)
	}
}

func TestBuildValidatedOutputsRejectsMissingEvidenceRefBeforeRendering(t *testing.T) {
	manifest := &capability.Manifest{Plugins: []capability.PluginCapability{{
		Name: "example",
		Evidence: capability.Evidence{Unit: capability.EvidenceClaim{
			State: capability.EvidenceVerified,
			Refs:  []string{"pkg/plugin/example/missing_test.go"},
		}},
	}}}

	_, err := buildValidatedOutputs(t.TempDir(), manifest)
	if err == nil || !strings.Contains(err.Error(), "does not exist") {
		t.Fatalf("buildValidatedOutputs() error = %v, want missing evidence rejection", err)
	}
}

func TestGovernedDocsDescribeOneRuntimeBehavior(t *testing.T) {
	read := func(path string) string {
		t.Helper()
		data, err := os.ReadFile(filepath.Join("..", "..", filepath.FromSlash(path)))
		if err != nil {
			t.Fatal(err)
		}
		return string(data)
	}

	for _, path := range []string{"README.md", "README.zh-CN.md", "docs/http-data-plane.md", "docs/configuration.md", "docs/design.md"} {
		content := read(path)
		if !strings.Contains(content, "APISIX") {
			t.Errorf("%s does not describe the APISIX contract", path)
		}
	}
}

func loadManifest(t *testing.T) *capability.Manifest {
	t.Helper()
	manifest, err := capability.Load()
	if err != nil {
		t.Fatal(err)
	}
	return manifest
}

func TestValidateDivergenceADRRequiresAcceptedOwnerDecision(t *testing.T) {
	valid := capability.Divergence{
		ID:               "DIV-001-example",
		Status:           capability.DivergenceAccepted,
		Target:           "apisix-3.17",
		ADR:              "docs/architecture/adr/0001-example.md",
		OwnerApprovalRef: "decisions 1-3",
	}

	tests := []struct {
		name       string
		divergence capability.Divergence
		content    string
		want       string
	}{
		{name: "missing ADR", divergence: valid, want: "missing ADR"},
		{
			name:       "proposed ADR",
			divergence: valid,
			content: validADRDocument(
				"ADR-0001",
				"proposed",
				[]string{valid.ID},
				"wklken",
				valid.Target,
				valid.OwnerApprovalRef,
			),
			want: "status",
		},
		{
			name:       "missing divergence ID",
			divergence: valid,
			content: validADRDocument(
				"ADR-0001",
				"accepted",
				nil,
				"wklken",
				valid.Target,
				valid.OwnerApprovalRef,
			),
			want: valid.ID,
		},
		{
			name:       "mismatched divergence ID",
			divergence: valid,
			content: validADRDocument(
				"ADR-0001",
				"accepted",
				[]string{"DIV-999-other"},
				"wklken",
				valid.Target,
				valid.OwnerApprovalRef,
			),
			want: valid.ID,
		},
		{
			name:       "duplicate divergence ID",
			divergence: valid,
			content: validADRDocument(
				"ADR-0001",
				"accepted",
				[]string{valid.ID, valid.ID},
				"wklken",
				valid.Target,
				valid.OwnerApprovalRef,
			),
			want: "exactly once",
		},
		{
			name:       "ADR ID filename mismatch",
			divergence: valid,
			content: validADRDocument(
				"ADR-9999",
				"accepted",
				[]string{valid.ID},
				"wklken",
				valid.Target,
				valid.OwnerApprovalRef,
			),
			want: "ADR-0001",
		},
		{
			name:       "compatibility target mismatch",
			divergence: valid,
			content: validADRDocument(
				"ADR-0001",
				"accepted",
				[]string{valid.ID},
				"wklken",
				"apisix-9.99",
				valid.OwnerApprovalRef,
			),
			want: "target",
		},
		{
			name:       "owner mismatch",
			divergence: valid,
			content: validADRDocument(
				"ADR-0001",
				"accepted",
				[]string{valid.ID},
				"agent",
				valid.Target,
				valid.OwnerApprovalRef,
			),
			want: "owner",
		},
		{
			name:       "approval mismatch",
			divergence: valid,
			content: validADRDocument(
				"ADR-0001",
				"accepted",
				[]string{valid.ID},
				"wklken",
				valid.Target,
				"decisions 4-6",
			),
			want: "owner_approval_ref",
		},
		{
			name:       "unknown front matter field",
			divergence: valid,
			content: strings.Replace(
				validADRDocument(
					"ADR-0001",
					"accepted",
					[]string{valid.ID},
					"wklken",
					valid.Target,
					valid.OwnerApprovalRef,
				),
				"date: 2026-08-23",
				"date: 2026-08-23\nunknown_field: rejected",
				1,
			),
			want: "unknown_field",
		},
		{
			name:       "missing date",
			divergence: valid,
			content: strings.Replace(
				validADRDocument(
					"ADR-0001",
					"accepted",
					[]string{valid.ID},
					"wklken",
					valid.Target,
					valid.OwnerApprovalRef,
				),
				"date: 2026-08-23\n",
				"",
				1,
			),
			want: "date",
		},
	}

	missingApproval := valid
	missingApproval.OwnerApprovalRef = ""
	tests = append(tests, struct {
		name       string
		divergence capability.Divergence
		content    string
		want       string
	}{
		name:       "missing owner approval reference",
		divergence: missingApproval,
		content:    validADRDocument("ADR-0001", "accepted", []string{valid.ID}, "wklken", valid.Target, ""),
		want:       "owner_approval_ref",
	})

	for _, test := range tests {
		t.Run(test.name, func(t *testing.T) {
			root := t.TempDir()
			if test.content != "" {
				writeADR(t, root, test.divergence.ADR, test.content)
			}
			err := validateDivergenceADR(root, test.divergence)
			if err == nil || !strings.Contains(err.Error(), test.want) {
				t.Fatalf("validateDivergenceADR() error = %v, want %q", err, test.want)
			}
		})
	}
}

func TestValidateDivergenceADRRejectsUnsafePaths(t *testing.T) {
	tests := []string{
		"/docs/architecture/adr/0001-example.md",
		"docs/architecture/adr/../0001-example.md",
		"docs/architecture/adr/0000-template.md",
		"docs/architecture/adr/0001-example.txt",
	}
	for _, path := range tests {
		t.Run(path, func(t *testing.T) {
			err := validateDivergenceADR(t.TempDir(), capability.Divergence{
				ID:               "DIV-001-example",
				Status:           capability.DivergenceAccepted,
				Target:           "apisix-3.17",
				ADR:              path,
				OwnerApprovalRef: "decisions 1-3",
			})
			if err == nil || !strings.Contains(err.Error(), "ADR path") {
				t.Fatalf("validateDivergenceADR() error = %v, want ADR path rejection", err)
			}
		})
	}
}

func TestValidateDivergenceADRRejectsManifestTargetMismatch(t *testing.T) {
	manifest := &capability.Manifest{
		Target: capability.Target{Name: "apisix-3.17"},
		Divergences: []capability.Divergence{{
			ID:               "DIV-001-example",
			Status:           capability.DivergenceAccepted,
			Target:           "apisix-9.99",
			ADR:              "docs/architecture/adr/0001-example.md",
			OwnerApprovalRef: "decisions 1-3",
		}},
	}
	err := validateDivergenceADRs(t.TempDir(), manifest)
	if err == nil || !strings.Contains(err.Error(), "DIV-001-example") ||
		!strings.Contains(err.Error(), "apisix-3.17") {
		t.Fatalf("validateDivergenceADRs() error = %v, want exact divergence and manifest target", err)
	}
}

func TestValidateDivergenceADRRejectsUnreferencedAcceptedADR(t *testing.T) {
	root := t.TempDir()
	manifest := testDivergenceManifest()
	writeManifestADRs(t, root, manifest)
	writeADR(t, root, "docs/architecture/adr/0099-unreferenced.md", validADRDocument(
		"ADR-0099", "accepted", []string{"DIV-099-unreferenced"}, "wklken", "apisix-3.17", "decisions 99",
	))
	err := validateDivergenceADRs(root, manifest)
	if err == nil || !strings.Contains(err.Error(), "ADR-0099") || !strings.Contains(err.Error(), "unreferenced") {
		t.Fatalf("validateDivergenceADRs() error = %v, want unreferenced accepted ADR", err)
	}
}

func TestValidateDivergenceADRRejectsMismatchedLedgerList(t *testing.T) {
	root := t.TempDir()
	manifest := testDivergenceManifest()
	writeManifestADRs(t, root, manifest)
	first := manifest.Divergences[0]
	writeADR(t, root, first.ADR, validADRDocument(
		"ADR-0001",
		"accepted",
		[]string{first.ID, "DIV-999-unapproved"},
		"wklken",
		first.Target,
		first.OwnerApprovalRef,
	))
	err := validateDivergenceADRs(root, manifest)
	if err == nil || !strings.Contains(err.Error(), "ADR-0001") || !strings.Contains(err.Error(), "exactly match") {
		t.Fatalf("validateDivergenceADRs() error = %v, want exact divergence ledger mismatch", err)
	}
}

func TestValidateDivergenceADRRejectsSymlinksWithoutChangingExternalFile(t *testing.T) {
	for _, test := range []struct {
		name string
		link func(t *testing.T, root, outside, relativePath string)
	}{
		{
			name: "ADR file",
			link: func(t *testing.T, root, outside, relativePath string) {
				t.Helper()
				if err := os.MkdirAll(filepath.Join(root, filepath.Dir(relativePath)), 0o755); err != nil {
					t.Fatal(err)
				}
				if err := os.Symlink(filepath.Join(outside, "sentinel.md"), filepath.Join(root, relativePath)); err != nil {
					t.Skipf("creating symlink is unavailable: %v", err)
				}
			},
		},
		{
			name: "ADR directory",
			link: func(t *testing.T, root, outside, relativePath string) {
				t.Helper()
				if err := os.MkdirAll(filepath.Join(root, "docs", "architecture"), 0o755); err != nil {
					t.Fatal(err)
				}
				if err := os.Symlink(outside, filepath.Join(root, "docs", "architecture", "adr")); err != nil {
					t.Skipf("creating symlink is unavailable: %v", err)
				}
			},
		},
	} {
		t.Run(test.name, func(t *testing.T) {
			root := t.TempDir()
			outside := t.TempDir()
			first := testDivergenceManifest().Divergences[0]
			sentinelContent := validADRDocument(
				"ADR-0001",
				"accepted",
				[]string{first.ID},
				"wklken",
				"apisix-3.17",
				first.OwnerApprovalRef,
			)
			sentinelPath := filepath.Join(outside, "sentinel.md")
			if err := os.WriteFile(sentinelPath, []byte(sentinelContent), 0o644); err != nil {
				t.Fatal(err)
			}
			relativePath := filepath.FromSlash(first.ADR)
			test.link(t, root, outside, relativePath)

			err := validateDivergenceADR(root, first)
			if err == nil || !strings.Contains(err.Error(), "symbolic link") ||
				!strings.Contains(err.Error(), first.ID) {
				t.Fatalf("validateDivergenceADR() error = %v, want exact divergence symbolic-link rejection", err)
			}
			got, err := os.ReadFile(sentinelPath)
			if err != nil {
				t.Fatal(err)
			}
			if string(got) != sentinelContent {
				t.Fatalf("external sentinel changed: got %q", got)
			}
		})
	}
}

func TestValidateDivergenceADRValidThreeDecisionRepository(t *testing.T) {
	root := t.TempDir()
	manifest := testDivergenceManifest()
	writeManifestADRs(t, root, manifest)
	if err := validateDivergenceADRs(root, manifest); err != nil {
		t.Fatalf("validateDivergenceADRs() error = %v", err)
	}
}

func TestValidateDivergenceADRCODEOWNERSBoundary(t *testing.T) {
	data, err := os.ReadFile(filepath.Join("..", "..", ".github", "CODEOWNERS"))
	if err != nil {
		t.Fatal(err)
	}
	want := "/pkg/capability/manifest.yaml @wklken\n" +
		"/pkg/config/types.go @wklken\n" +
		"/docs/architecture/adr/ @wklken\n" +
		"/docs/plugins.md @wklken\n"
	if string(data) != want {
		t.Fatalf("CODEOWNERS = %q, want exact governance boundary %q", data, want)
	}
}

func testDivergenceManifest() *capability.Manifest {
	return &capability.Manifest{
		Target: capability.Target{Name: "apisix-3.17"},
		Divergences: []capability.Divergence{
			{
				ID:               "DIV-001-go-native-extension-identity",
				Status:           capability.DivergenceAccepted,
				Target:           "apisix-3.17",
				ADR:              "docs/architecture/adr/0001-compatibility-governance.md",
				OwnerApprovalRef: "decisions 1-42",
			},
			{
				ID:               "DIV-003-platform-artifact-policy",
				Status:           capability.DivergenceAccepted,
				Target:           "apisix-3.17",
				ADR:              "docs/architecture/adr/0003-platform-support.md",
				OwnerApprovalRef: "decisions 107, 118-130",
			},
		},
	}
}

func writeManifestADRs(t *testing.T, root string, manifest *capability.Manifest) {
	t.Helper()
	for _, divergence := range manifest.Divergences {
		if divergence.Status != capability.DivergenceAccepted {
			continue
		}
		base := filepath.Base(filepath.FromSlash(divergence.ADR))
		number := strings.SplitN(base, "-", 2)[0]
		writeADR(t, root, divergence.ADR, validADRDocument(
			"ADR-"+number,
			"accepted",
			[]string{divergence.ID},
			"wklken",
			divergence.Target,
			divergence.OwnerApprovalRef,
		))
	}
}

func writeADR(t *testing.T, root, relativePath, content string) {
	t.Helper()
	path := filepath.Join(root, filepath.FromSlash(relativePath))
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
		t.Fatal(err)
	}
}

func validADRDocument(id, status string, divergenceIDs []string, owner, target, approval string) string {
	quotedIDs := make([]string, len(divergenceIDs))
	for index, divergenceID := range divergenceIDs {
		quotedIDs[index] = fmt.Sprintf("%q", divergenceID)
	}
	return fmt.Sprintf(`---
id: %s
title: Test divergence
status: %s
target: %s
divergence_ids: [%s]
owner: %s
owner_approval_ref: %q
date: 2026-08-23
---

# Context

Pinned behavior.

# Decision

Exact decision.

# Consequences

Known consequences.

# Evidence required to retire

Exact retirement evidence.
`, id, status, target, strings.Join(quotedIDs, ", "), owner, approval)
}

func TestCheckDetectsDrift(t *testing.T) {
	manifest, err := capability.Load()
	if err != nil {
		t.Fatal(err)
	}
	generated, err := renderRegistry(manifest)
	if err != nil {
		t.Fatal(err)
	}
	outputs := []generatedOutput{{relativePath: registryOutputPath, content: generated}}
	root := t.TempDir()
	if err := writeOutputs(root, outputs); err != nil {
		t.Fatal(err)
	}

	path := filepath.Join(root, filepath.FromSlash(registryOutputPath))
	drifted := append([]byte(nil), generated...)
	drifted[0] ^= 1
	if err := os.WriteFile(path, drifted, 0o644); err != nil {
		t.Fatal(err)
	}
	if err := checkOutputs(root, outputs); err == nil {
		t.Fatal("checkOutputs() error = nil, want generated drift")
	} else if got, want := err.Error(), registryOutputPath+": generated output is stale"; got != want {
		t.Fatalf("checkOutputs() error = %q, want %q", got, want)
	}
}

func TestCheckRejectsOutputPathEscape(t *testing.T) {
	err := checkOutputs(t.TempDir(), []generatedOutput{{
		relativePath: "../registry_gen.go",
		content:      []byte("generated"),
	}})
	if err == nil || !strings.Contains(err.Error(), "escapes repository root") {
		t.Fatalf("checkOutputs() error = %v, want repository escape rejection", err)
	}
}

func TestOutputsRejectDirectorySymlink(t *testing.T) {
	for _, operation := range []struct {
		name string
		run  func(string, []generatedOutput) error
	}{
		{name: "check", run: checkOutputs},
		{name: "write", run: writeOutputs},
	} {
		t.Run(operation.name, func(t *testing.T) {
			root := t.TempDir()
			outside := t.TempDir()
			sentinelPath := filepath.Join(outside, "registry_gen.go")
			sentinel := []byte("external sentinel")
			if err := os.WriteFile(sentinelPath, sentinel, 0o644); err != nil {
				t.Fatal(err)
			}
			if err := os.MkdirAll(filepath.Join(root, "pkg"), 0o755); err != nil {
				t.Fatal(err)
			}
			if err := os.Symlink(outside, filepath.Join(root, "pkg", "plugin")); err != nil {
				t.Skipf("creating symlink is unavailable: %v", err)
			}

			err := operation.run(root, []generatedOutput{{
				relativePath: registryOutputPath,
				content:      []byte("generated"),
			}})
			if err == nil || !strings.Contains(err.Error(), "symbolic link") {
				t.Fatalf("operation error = %v, want symbolic-link rejection", err)
			}
			got, err := os.ReadFile(sentinelPath)
			if err != nil {
				t.Fatal(err)
			}
			if !bytes.Equal(got, sentinel) {
				t.Fatalf("external sentinel changed: got %q, want %q", got, sentinel)
			}
		})
	}
}

func TestOutputsRejectFinalFileSymlink(t *testing.T) {
	for _, operation := range []struct {
		name string
		run  func(string, []generatedOutput) error
	}{
		{name: "check", run: checkOutputs},
		{name: "write", run: writeOutputs},
	} {
		t.Run(operation.name, func(t *testing.T) {
			root := t.TempDir()
			outside := t.TempDir()
			sentinelPath := filepath.Join(outside, "registry_gen.go")
			sentinel := []byte("external sentinel")
			if err := os.WriteFile(sentinelPath, sentinel, 0o644); err != nil {
				t.Fatal(err)
			}
			outputDir := filepath.Join(root, "pkg", "plugin")
			if err := os.MkdirAll(outputDir, 0o755); err != nil {
				t.Fatal(err)
			}
			if err := os.Symlink(sentinelPath, filepath.Join(outputDir, "registry_gen.go")); err != nil {
				t.Skipf("creating symlink is unavailable: %v", err)
			}

			err := operation.run(root, []generatedOutput{{
				relativePath: registryOutputPath,
				content:      []byte("generated"),
			}})
			if err == nil || !strings.Contains(err.Error(), "symbolic link") {
				t.Fatalf("operation error = %v, want symbolic-link rejection", err)
			}
			got, err := os.ReadFile(sentinelPath)
			if err != nil {
				t.Fatal(err)
			}
			if !bytes.Equal(got, sentinel) {
				t.Fatalf("external sentinel changed: got %q, want %q", got, sentinel)
			}
		})
	}
}
