package main

import (
	"bytes"
	"errors"
	"flag"
	"fmt"
	"go/format"
	"go/token"
	"io"
	"os"
	"path/filepath"
	"sort"
	"strconv"
	"strings"

	"github.com/wklken/apisix-go/pkg/capability"
)

const registryOutputPath = "pkg/plugin/registry_gen.go"

type generatedOutput struct {
	relativePath string
	content      []byte
}

func main() {
	if err := run(os.Args[1:], os.Stderr); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}

func run(args []string, stderr io.Writer) error {
	flags := flag.NewFlagSet("capability-gen", flag.ContinueOnError)
	flags.SetOutput(stderr)
	repoRoot := flags.String("repo-root", ".", "repository root containing generated outputs")
	check := flags.Bool("check", false, "fail when generated outputs differ from disk")
	write := flags.Bool("write", false, "write generated outputs")
	if err := flags.Parse(args); err != nil {
		return err
	}
	if flags.NArg() != 0 {
		return fmt.Errorf("unexpected arguments: %s", strings.Join(flags.Args(), " "))
	}
	if *check == *write {
		return errors.New("exactly one of -check or -write must be set")
	}

	manifest, err := capability.Load()
	if err != nil {
		return fmt.Errorf("load capability manifest: %w", err)
	}
	registry, err := renderRegistry(manifest)
	if err != nil {
		return err
	}
	outputs := []generatedOutput{{relativePath: registryOutputPath, content: registry}}
	if *write {
		return writeOutputs(*repoRoot, outputs)
	}
	return checkOutputs(*repoRoot, outputs)
}

func renderRegistry(manifest *capability.Manifest) ([]byte, error) {
	if manifest == nil {
		return nil, errors.New("render registry: manifest must not be nil")
	}

	type registryImport struct {
		path  string
		alias string
	}
	type registryFactory struct {
		key         string
		alias       string
		constructor string
	}

	importsByPath := make(map[string]string)
	pathsByAlias := make(map[string]string)
	factories := make([]registryFactory, 0)
	entries := make([]capability.PluginCapability, 0)
	seenFactories := make(map[string]struct{})
	seenEntries := make(map[string]struct{})
	for _, plugin := range manifest.Plugins {
		if len(plugin.Factories) == 0 {
			continue
		}
		if _, exists := seenEntries[plugin.Name]; exists {
			return nil, fmt.Errorf("render registry: duplicate capability identity %q", plugin.Name)
		}
		seenEntries[plugin.Name] = struct{}{}
		if err := validateGeneratedFacts(plugin); err != nil {
			return nil, err
		}
		entries = append(entries, plugin)

		for _, factory := range plugin.Factories {
			if _, exists := seenFactories[factory.Key]; exists {
				return nil, fmt.Errorf("render registry: duplicate factory %q", factory.Key)
			}
			seenFactories[factory.Key] = struct{}{}
			if !token.IsIdentifier(factory.ImportAlias) {
				return nil, fmt.Errorf(
					"render registry: factory %q has invalid import alias %q",
					factory.Key,
					factory.ImportAlias,
				)
			}
			if !token.IsIdentifier(factory.Constructor) {
				return nil, fmt.Errorf(
					"render registry: factory %q has invalid constructor %q",
					factory.Key,
					factory.Constructor,
				)
			}
			if alias, exists := importsByPath[factory.ImportPath]; exists && alias != factory.ImportAlias {
				return nil, fmt.Errorf(
					"render registry: import %q uses aliases %q and %q",
					factory.ImportPath,
					alias,
					factory.ImportAlias,
				)
			}
			if path, exists := pathsByAlias[factory.ImportAlias]; exists && path != factory.ImportPath {
				return nil, fmt.Errorf(
					"render registry: import alias %q is shared by %q and %q",
					factory.ImportAlias,
					path,
					factory.ImportPath,
				)
			}
			importsByPath[factory.ImportPath] = factory.ImportAlias
			pathsByAlias[factory.ImportAlias] = factory.ImportPath
			factories = append(factories, registryFactory{
				key:         factory.Key,
				alias:       factory.ImportAlias,
				constructor: factory.Constructor,
			})
		}
	}

	imports := make([]registryImport, 0, len(importsByPath))
	for path, alias := range importsByPath {
		imports = append(imports, registryImport{path: path, alias: alias})
	}
	sort.Slice(imports, func(i, j int) bool {
		if imports[i].path == imports[j].path {
			return imports[i].alias < imports[j].alias
		}
		return imports[i].path < imports[j].path
	})
	sort.Slice(factories, func(i, j int) bool { return factories[i].key < factories[j].key })
	sort.Slice(entries, func(i, j int) bool { return entries[i].Name < entries[j].Name })

	var source bytes.Buffer
	source.WriteString("// Code generated by go run ./cmd/capability-gen -write; DO NOT EDIT.\n\n")
	source.WriteString("package plugin\n\n")
	source.WriteString("// Imports are rendered from manifest Factory facts.\n")
	source.WriteString("import (\n")
	for _, imported := range imports {
		fmt.Fprintf(&source, "\t%s %s\n", imported.alias, strconv.Quote(imported.path))
	}
	source.WriteString(")\n\n")
	source.WriteString("var pluginRegistry = map[string]func() Plugin{\n")
	for _, factory := range factories {
		fmt.Fprintf(
			&source,
			"\t%s: func() Plugin { return %s },\n",
			strconv.Quote(factory.key),
			constructorExpression(factory.alias, factory.constructor),
		)
	}
	source.WriteString("}\n\n")
	source.WriteString("func generatedCapabilityManifestEntries() map[string]capabilityManifestEntry {\n")
	source.WriteString("\treturn map[string]capabilityManifestEntry{\n")
	for _, entry := range entries {
		fmt.Fprintf(&source, "\t\t%s: {\n", strconv.Quote(entry.Name))
		fmt.Fprintf(&source, "\t\t\tphases: %s,\n", stringSliceLiteral(entry.Phases))
		fmt.Fprintf(&source, "\t\t\tscopes: %s,\n", stringSliceLiteral(entry.Scopes))
		source.WriteString("\t\t},\n")
	}
	source.WriteString("\t}\n")
	source.WriteString("}\n")

	formatted, err := format.Source(source.Bytes())
	if err != nil {
		return nil, fmt.Errorf("format generated registry: %w", err)
	}
	return formatted, nil
}

func validateGeneratedFacts(plugin capability.PluginCapability) error {
	for _, phase := range plugin.Phases {
		switch phase {
		case "rewrite", "consumer_rewrite", "access", "before_proxy", "header_filter",
			"body_filter", "log", "finalizer", "protocol":
		default:
			return fmt.Errorf("render registry: capability %q has unsupported phase %q", plugin.Name, phase)
		}
	}
	for _, scope := range plugin.Scopes {
		switch scope {
		case "system", "global_rule", "route", "service":
		default:
			return fmt.Errorf("render registry: capability %q has unsupported scope %q", plugin.Name, scope)
		}
	}
	return nil
}

func constructorExpression(alias, constructor string) string {
	if constructor == "Plugin" {
		return "&" + alias + "." + constructor + "{}"
	}
	return alias + "." + constructor + "()"
}

func stringSliceLiteral(values []string) string {
	quoted := make([]string, len(values))
	for index, value := range values {
		quoted[index] = strconv.Quote(value)
	}
	return "[]string{" + strings.Join(quoted, ", ") + "}"
}

func writeOutputs(repoRoot string, outputs []generatedOutput) error {
	for _, output := range outputs {
		path, err := containedOutputPath(repoRoot, output.relativePath)
		if err != nil {
			return err
		}
		if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
			return fmt.Errorf("create output directory for %s: %w", output.relativePath, err)
		}
		if err := os.WriteFile(path, output.content, 0o644); err != nil {
			return fmt.Errorf("write %s: %w", output.relativePath, err)
		}
	}
	return nil
}

func checkOutputs(repoRoot string, outputs []generatedOutput) error {
	for _, output := range outputs {
		path, err := containedOutputPath(repoRoot, output.relativePath)
		if err != nil {
			return err
		}
		current, err := os.ReadFile(path)
		if errors.Is(err, os.ErrNotExist) {
			return fmt.Errorf("%s: generated output is missing", output.relativePath)
		}
		if err != nil {
			return fmt.Errorf("read %s: %w", output.relativePath, err)
		}
		if !bytes.Equal(current, output.content) {
			return fmt.Errorf("%s: generated output is stale", output.relativePath)
		}
	}
	return nil
}

func containedOutputPath(repoRoot, relativePath string) (string, error) {
	root, err := filepath.Abs(filepath.Clean(repoRoot))
	if err != nil {
		return "", fmt.Errorf("clean repository root: %w", err)
	}
	if filepath.IsAbs(relativePath) {
		return "", fmt.Errorf("output path %q escapes repository root", relativePath)
	}
	path := filepath.Clean(filepath.Join(root, filepath.FromSlash(relativePath)))
	relative, err := filepath.Rel(root, path)
	if err != nil {
		return "", fmt.Errorf("resolve output path %q: %w", relativePath, err)
	}
	if relative == ".." || strings.HasPrefix(relative, ".."+string(filepath.Separator)) {
		return "", fmt.Errorf("output path %q escapes repository root", relativePath)
	}
	return path, nil
}
