package main

import (
	"bytes"
	"crypto/sha256"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"testing"

	"github.com/wklken/apisix-go/pkg/capability"
)

func TestRenderRegistryIsDeterministic(t *testing.T) {
	manifest, err := capability.Load()
	if err != nil {
		t.Fatal(err)
	}
	first, err := renderRegistry(manifest)
	if err != nil {
		t.Fatal(err)
	}
	second, err := renderRegistry(manifest)
	if err != nil {
		t.Fatal(err)
	}
	if !bytes.Equal(first, second) {
		t.Fatal("registry generation is nondeterministic")
	}
	normalized := bytes.Join(bytes.Fields(first), []byte(" "))
	if !bytes.Contains(normalized, []byte(`"request-id": func() Plugin { return &request_id.Plugin{} }`)) {
		t.Fatal("request-id constructor missing")
	}
}

func TestRenderRegistrySortsImportsAndFactories(t *testing.T) {
	manifest, err := capability.Load()
	if err != nil {
		t.Fatal(err)
	}
	generated, err := renderRegistry(manifest)
	if err != nil {
		t.Fatal(err)
	}

	aclImport := bytes.Index(generated, []byte(`"github.com/wklken/apisix-go/pkg/plugin/acl"`))
	aiImport := bytes.Index(generated, []byte(`"github.com/wklken/apisix-go/pkg/plugin/ai"`))
	if aclImport < 0 || aiImport < 0 || aclImport >= aiImport {
		t.Fatalf("imports are not sorted: acl=%d ai=%d", aclImport, aiImport)
	}
	aclFactory := bytes.Index(generated, []byte(`"acl":`))
	aiFactory := bytes.Index(generated, []byte(`"ai":`))
	if aclFactory < 0 || aiFactory < 0 || aclFactory >= aiFactory {
		t.Fatalf("factories are not sorted: acl=%d ai=%d", aclFactory, aiFactory)
	}
}

func TestRenderPluginsMarkdownSeparatesBehaviorAndEvidence(t *testing.T) {
	manifest := loadManifest(t)
	generated, err := renderPluginsMarkdown(manifest)
	if err != nil {
		t.Fatal(err)
	}

	for _, text := range []string{
		"Code generated by go run ./cmd/capability-gen -write; DO NOT EDIT.",
		"Behavior status",
		"Schema",
		"Unit",
		"Converted upstream",
		"Differential",
		"Real dependency",
		"Failure",
		"Recovery",
	} {
		if !bytes.Contains(generated, []byte(text)) {
			t.Fatalf("generated plugins.md missing %q", text)
		}
	}
	for _, field := range []string{
		manifest.Target.Name,
		manifest.Target.Version,
		manifest.Target.SourceCommit,
		manifest.Target.Image,
		"manifest projections, not proof",
	} {
		if !bytes.Contains(generated, []byte(field)) {
			t.Fatalf("generated plugins.md missing target/projection field %q", field)
		}
	}
}

func TestRenderPluginsMarkdownSortsDefaultsBeforeExtensions(t *testing.T) {
	manifest := loadManifest(t)
	generated, err := renderPluginsMarkdown(manifest)
	if err != nil {
		t.Fatal(err)
	}

	defaults := make([]capability.PluginCapability, 0)
	extensions := make([]capability.PluginCapability, 0)
	for _, plugin := range manifest.Plugins {
		if plugin.APISIXDefault {
			defaults = append(defaults, plugin)
		} else {
			extensions = append(extensions, plugin)
		}
	}
	sort.Slice(defaults, func(i, j int) bool { return defaults[i].Name < defaults[j].Name })
	sort.Slice(extensions, func(i, j int) bool {
		if extensions[i].Namespace != extensions[j].Namespace {
			return extensions[i].Namespace < extensions[j].Namespace
		}
		return extensions[i].Name < extensions[j].Name
	})
	positions := make([]int, 0, len(manifest.Plugins))
	for _, plugin := range defaults {
		row := []byte("| `" + plugin.Name + "` | `" + string(plugin.Namespace) + "` |")
		positions = append(positions, bytes.Index(generated, row))
	}
	for _, plugin := range extensions {
		row := []byte("| `" + plugin.Name + "` | `" + string(plugin.Namespace) + "` |")
		positions = append(positions, bytes.Index(generated, row))
	}
	for index, position := range positions {
		if position < 0 {
			t.Fatalf("sorted plugin row %d is missing", index)
		}
		if index > 0 && positions[index-1] >= position {
			t.Fatalf(
				"plugin rows are not in deterministic default/extension order at %d: %d >= %d",
				index,
				positions[index-1],
				position,
			)
		}
	}
}

func TestRenderPluginsMarkdownPreservesGapsAndEvidenceLegends(t *testing.T) {
	manifest := loadManifest(t)
	generated, err := renderPluginsMarkdown(manifest)
	if err != nil {
		t.Fatal(err)
	}

	for _, state := range []string{"stale", "flaky", "deferred"} {
		if !bytes.Contains(generated, []byte("**"+state+"**")) {
			t.Fatalf("generated plugins.md does not define %q evidence", state)
		}
	}
	for _, plugin := range manifest.Plugins {
		for _, gap := range plugin.KnownGaps {
			if !bytes.Contains(generated, []byte(markdownCell(gap))) {
				t.Fatalf("generated plugins.md lost gap for %s: %q", plugin.Name, gap)
			}
		}
	}
	if bytes.Contains(generated, []byte("100%")) {
		t.Fatal("generated plugins.md makes a false 100% claim")
	}
}

func TestRenderReadmeSummaryLocalesShareManifestFacts(t *testing.T) {
	manifest := loadManifest(t)
	english, err := renderReadmeSummary(manifest, readmeEnglish)
	if err != nil {
		t.Fatal(err)
	}
	chinese, err := renderReadmeSummary(manifest, readmeChinese)
	if err != nil {
		t.Fatal(err)
	}

	counts := deriveCapabilityCounts(manifest)
	facts := []string{
		manifest.Target.Name,
		manifest.Target.Version,
		manifest.Target.SourceCommit,
		fmt.Sprintf("%d", counts.total),
		fmt.Sprintf("%d", counts.defaults),
		fmt.Sprintf("%d", counts.applicableDefaults),
		fmt.Sprintf("%d", counts.fullDefaults),
		fmt.Sprintf("%d", counts.partialDefaults),
		fmt.Sprintf("%d", counts.notApplicableDefaults),
		fmt.Sprintf("%d/%d", counts.qualified, counts.required),
	}
	for _, fact := range facts {
		if !bytes.Contains(english, []byte(fact)) || !bytes.Contains(chinese, []byte(fact)) {
			t.Fatalf("localized summaries do not share derived fact %q", fact)
		}
	}
	for _, plugin := range manifest.Plugins {
		for _, gap := range plugin.KnownGaps {
			if !bytes.Contains(english, []byte(gap)) || !bytes.Contains(chinese, []byte(gap)) {
				t.Fatalf("localized summaries do not share gap for %s: %q", plugin.Name, gap)
			}
		}
	}
	if bytes.Contains(english, []byte("100%")) || bytes.Contains(chinese, []byte("100%")) {
		t.Fatal("localized summaries make a false 100% claim")
	}
}

func TestReplaceGeneratedReadmeBlockIsBounded(t *testing.T) {
	source := []byte("before\n" + generatedSummaryBegin + "\nold\n" + generatedSummaryEnd + "\nafter\n")
	summary := []byte("generated\nsummary")
	got, err := replaceGeneratedReadmeBlock(source, summary)
	if err != nil {
		t.Fatal(err)
	}
	want := []byte(
		"before\n" + generatedSummaryBegin + "\n" + generatedSummaryNotice + "\ngenerated\nsummary\n" + generatedSummaryEnd + "\nafter\n",
	)
	if !bytes.Equal(got, want) {
		t.Fatalf("replaceGeneratedReadmeBlock() = %q, want %q", got, want)
	}
}

func TestReplaceGeneratedReadmeBlockRejectsMissingOrDuplicateMarkers(t *testing.T) {
	tests := map[string][]byte{
		"missing": []byte("no generated block\n"),
		"duplicate begin": []byte(
			generatedSummaryBegin + "\n" + generatedSummaryBegin + "\n" + generatedSummaryEnd + "\n",
		),
		"duplicate end": []byte(
			generatedSummaryBegin + "\n" + generatedSummaryEnd + "\n" + generatedSummaryEnd + "\n",
		),
	}
	for name, source := range tests {
		t.Run(name, func(t *testing.T) {
			if _, err := replaceGeneratedReadmeBlock(source, []byte("summary")); err == nil {
				t.Fatal("replaceGeneratedReadmeBlock() error = nil, want marker rejection")
			}
		})
	}
}

func TestBuildOutputsRejectsReadmeSymlink(t *testing.T) {
	root := t.TempDir()
	outside := t.TempDir()
	sentinel := filepath.Join(outside, "README.md")
	if err := os.WriteFile(sentinel, []byte("external sentinel"), 0o644); err != nil {
		t.Fatal(err)
	}
	if err := os.Symlink(sentinel, filepath.Join(root, "README.md")); err != nil {
		t.Skipf("creating symlink is unavailable: %v", err)
	}
	if _, err := buildOutputs(root, loadManifest(t)); err == nil || !strings.Contains(err.Error(), "symbolic link") {
		t.Fatalf("buildOutputs() error = %v, want README symbolic-link rejection", err)
	}
	got, err := os.ReadFile(sentinel)
	if err != nil {
		t.Fatal(err)
	}
	if string(got) != "external sentinel" {
		t.Fatalf("external README changed: %q", got)
	}
}

func TestGeneratedDocumentationDriftIsChecked(t *testing.T) {
	root := t.TempDir()
	for _, name := range []string{readmeOutputPath, readmeChineseOutputPath} {
		content := []byte("before\n" + generatedSummaryBegin + "\nold\n" + generatedSummaryEnd + "\nafter\n")
		if err := os.WriteFile(filepath.Join(root, name), content, 0o644); err != nil {
			t.Fatal(err)
		}
	}
	outputs, err := buildOutputs(root, loadManifest(t))
	if err != nil {
		t.Fatal(err)
	}
	if err := writeOutputs(root, outputs); err != nil {
		t.Fatal(err)
	}
	for _, name := range []string{pluginsOutputPath, readmeOutputPath, readmeChineseOutputPath} {
		t.Run(name, func(t *testing.T) {
			path := filepath.Join(root, filepath.FromSlash(name))
			current, err := os.ReadFile(path)
			if err != nil {
				t.Fatal(err)
			}
			current[0] ^= 1
			if err := os.WriteFile(path, current, 0o644); err != nil {
				t.Fatal(err)
			}
			if err := checkOutputs(root, outputs); err == nil ||
				!strings.Contains(err.Error(), "generated output is stale") {
				t.Fatalf("checkOutputs() error = %v, want generated documentation drift", err)
			}
			if err := writeOutputs(root, outputs); err != nil {
				t.Fatal(err)
			}
		})
	}
}

func TestArchivedPluginsSnapshotIntegrity(t *testing.T) {
	archivePath := filepath.Join("..", "..", "docs", "history", "plugins-2026-08-23.md")
	archived, err := os.ReadFile(archivePath)
	if err != nil {
		t.Fatal(err)
	}
	banner := []byte(
		"> Historical snapshot archived during the 2026-08-23 capability-manifest cutover.\n" +
			"> It is evidence of prior project claims, not the current source of truth.\n" +
			"> Current generated status: [`docs/plugins.md`](../plugins.md).\n",
	)
	if !bytes.HasPrefix(archived, banner) {
		t.Fatalf("archive does not begin with exact three-line banner: %q", archived[:min(len(archived), len(banner))])
	}
	tail := archived[len(banner):]
	if got, want := len(tail), 53912; got != want {
		t.Fatalf("archive tail size = %d, want %d", got, want)
	}
	got := fmt.Sprintf("%x", sha256.Sum256(tail))
	want := "54c6ef75d33b8e88d8473941b5219846c6fc4596e2d00e1904bfec819092f825"
	if got != want {
		t.Fatalf("archive tail SHA-256 = %s, want %s", got, want)
	}
}

func loadManifest(t *testing.T) *capability.Manifest {
	t.Helper()
	manifest, err := capability.Load()
	if err != nil {
		t.Fatal(err)
	}
	return manifest
}

func TestCheckDetectsDrift(t *testing.T) {
	manifest, err := capability.Load()
	if err != nil {
		t.Fatal(err)
	}
	generated, err := renderRegistry(manifest)
	if err != nil {
		t.Fatal(err)
	}
	outputs := []generatedOutput{{relativePath: registryOutputPath, content: generated}}
	root := t.TempDir()
	if err := writeOutputs(root, outputs); err != nil {
		t.Fatal(err)
	}

	path := filepath.Join(root, filepath.FromSlash(registryOutputPath))
	drifted := append([]byte(nil), generated...)
	drifted[0] ^= 1
	if err := os.WriteFile(path, drifted, 0o644); err != nil {
		t.Fatal(err)
	}
	if err := checkOutputs(root, outputs); err == nil {
		t.Fatal("checkOutputs() error = nil, want generated drift")
	} else if got, want := err.Error(), registryOutputPath+": generated output is stale"; got != want {
		t.Fatalf("checkOutputs() error = %q, want %q", got, want)
	}
}

func TestCheckRejectsOutputPathEscape(t *testing.T) {
	err := checkOutputs(t.TempDir(), []generatedOutput{{
		relativePath: "../registry_gen.go",
		content:      []byte("generated"),
	}})
	if err == nil || !strings.Contains(err.Error(), "escapes repository root") {
		t.Fatalf("checkOutputs() error = %v, want repository escape rejection", err)
	}
}

func TestOutputsRejectDirectorySymlink(t *testing.T) {
	for _, operation := range []struct {
		name string
		run  func(string, []generatedOutput) error
	}{
		{name: "check", run: checkOutputs},
		{name: "write", run: writeOutputs},
	} {
		t.Run(operation.name, func(t *testing.T) {
			root := t.TempDir()
			outside := t.TempDir()
			sentinelPath := filepath.Join(outside, "registry_gen.go")
			sentinel := []byte("external sentinel")
			if err := os.WriteFile(sentinelPath, sentinel, 0o644); err != nil {
				t.Fatal(err)
			}
			if err := os.MkdirAll(filepath.Join(root, "pkg"), 0o755); err != nil {
				t.Fatal(err)
			}
			if err := os.Symlink(outside, filepath.Join(root, "pkg", "plugin")); err != nil {
				t.Skipf("creating symlink is unavailable: %v", err)
			}

			err := operation.run(root, []generatedOutput{{
				relativePath: registryOutputPath,
				content:      []byte("generated"),
			}})
			if err == nil || !strings.Contains(err.Error(), "symbolic link") {
				t.Fatalf("operation error = %v, want symbolic-link rejection", err)
			}
			got, err := os.ReadFile(sentinelPath)
			if err != nil {
				t.Fatal(err)
			}
			if !bytes.Equal(got, sentinel) {
				t.Fatalf("external sentinel changed: got %q, want %q", got, sentinel)
			}
		})
	}
}

func TestOutputsRejectFinalFileSymlink(t *testing.T) {
	for _, operation := range []struct {
		name string
		run  func(string, []generatedOutput) error
	}{
		{name: "check", run: checkOutputs},
		{name: "write", run: writeOutputs},
	} {
		t.Run(operation.name, func(t *testing.T) {
			root := t.TempDir()
			outside := t.TempDir()
			sentinelPath := filepath.Join(outside, "registry_gen.go")
			sentinel := []byte("external sentinel")
			if err := os.WriteFile(sentinelPath, sentinel, 0o644); err != nil {
				t.Fatal(err)
			}
			outputDir := filepath.Join(root, "pkg", "plugin")
			if err := os.MkdirAll(outputDir, 0o755); err != nil {
				t.Fatal(err)
			}
			if err := os.Symlink(sentinelPath, filepath.Join(outputDir, "registry_gen.go")); err != nil {
				t.Skipf("creating symlink is unavailable: %v", err)
			}

			err := operation.run(root, []generatedOutput{{
				relativePath: registryOutputPath,
				content:      []byte("generated"),
			}})
			if err == nil || !strings.Contains(err.Error(), "symbolic link") {
				t.Fatalf("operation error = %v, want symbolic-link rejection", err)
			}
			got, err := os.ReadFile(sentinelPath)
			if err != nil {
				t.Fatal(err)
			}
			if !bytes.Equal(got, sentinel) {
				t.Fatalf("external sentinel changed: got %q, want %q", got, sentinel)
			}
		})
	}
}
